language: node_js
node_js: '6.0'
before_install:
- chmod +x ./.build_scripts/deploy.sh
install:
- npm install
- cd validator && npm install
- cd ..
script:
- git diff HEAD~1 --name-only | grep datasets | cat > .build_scripts/ids.txt
- npm test
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: master
