name = "bigged161"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
category= ["education"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Schools list", "Governmental and nongovernmental", "Boys and girls"]

[[keywords]]
lang = "fa" 
wordlist = ["لیست مدارس کشور", "دولتی و غیردولتی", "پسرانه و دخترانه"]

[author]
web = "http://madreseha.ir/Default.aspx?tabid=82"

  [[author.name]] 
  lang = "fa"
  text = "گروه مهندسی بهنام ایده گستر"

  [[author.name]]
  lang = "en"
  text = "Behnam Ideh Gostar Group"

[[title]]
lang = "en" 
text = "List of schools in Iran based on gender and provinces" 

[[title]]
lang = "fa"
text = "لیست مدرسه‌های ایران به تفکیک جنسیت و استان‌ها"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی گروه مهندسی بهنام ایده گستر گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of Behnam Ideh Gostar Group."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/bigged161fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/bigged161en.csv"
  
  code = "https://github.com/iranopendata/ingest/blob/master/python/schools.py"

  [[resources.title]]
  lang = "en" 
  text = "List of schools in Iran based on gender and provinces"

  [[resources.title]]
  lang = "fa"
  text = "لیست مدرسه‌های ایران به تفکیک جنسیت و استان‌ها"

  [[resources.sources]]
  name = "Behnam Ideh Gostar Group" 
  web = "http://madreseha.ir/Default.aspx?tabid=82" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "School Name"
      type = "string"

      [[resources.schema.fields]]
      name = "School Grade"
      type = "string"

      [[resources.schema.fields]]
      name = "Type of the school"
      type = "string"

      [[resources.schema.fields]]
      name = "Gender"
      type = "string"

      [[resources.schema.fields]]
      name = "Address"
      type = "string"

      [[resources.schema.fields]]
      name = "Telephone"
      type = "string"


