name = "cbibf179"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1387 ,  1389] 
category= ["banking", "economics", "energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["GDP at base prices", "GDP without oil", "Value added in oil sector", "Value added in agriculture", "Value added in industry and mining sector", "Value added in construction sector", "Value added in the services sector", "GDP at market prices", "Private consumption costs", "Government consumption spending", "Total gross fixed capital formation", "Net exports", "National income", "Gross national savings"]

[[keywords]]
lang = "fa" 
wordlist = ["توليد ناخالص داخلی به قيمت پايه", "تولید ناخالص داخلی بدون نفت", "ارزش افزوده در بخش نفت", "ارزش افزوده در بخش کشاورزی", "ارزش افزوده در بخش صنعت و معدن", "ارزش افزوده در بخش ساختمان", "ارزش افزوده در بخش خدمات", "توليد ناخالص داخلی به قيمت بازار", "هزینه‌های مصرفی خصوصی", "هزینه‌های مصرفی دولتی", "تشکيل سرمايه ثابت ناخالص کل", "خالص صادرات", "درآمد ملی", "پس انداز ناخالص ملی"]

[author]
web = "http://cbi.ir/datedlist/9445.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Cenral Bank of Iran"

[[title]]
lang = "en" 
text = "National Accounts at current prices in the years 1387 to 1389" 

[[title]]
lang = "fa"
text = "حساب‌های ملی به قیمت‌های جاری در سال‌های ۱۳۸۷ تا ۱۳۸۹"

[[description]]
lang = "fa"
text = "این داده از صفحه ۲ و ۴، شاخص‌های عمده اقتصادی سال ١٣۹۰، استخراج شده است. (نماگرهای اقتصادی شماره ۶۷، سه ماهه چهارم سال ۱۳۹۰)"

[[description]]
lang = "en"
text = "Dataset exctracted from pages 2 and 4, Main economic indicators in 1390."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf179fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf179en.csv"

  [[resources.title]]
  lang = "en" 
  text = "National Accounts at current prices in the years 1387 to 1389"

  [[resources.title]]
  lang = "fa"
  text = "حساب‌های ملی به قیمت‌های جاری در سال‌های ۱۳۸۷ تا ۱۳۸۹"

  [[resources.sources]]
  name = "Cenral Bank of Iran" 
  web = "http://cbi.ir/datedlist/9445.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year and Period"
      type = "string"

      [[resources.schema.fields]]
      name = "GDP at basic prices"
      type = "string"

      [[resources.schema.fields]]
      name = "GDP without oil"
      type = "string"

      [[resources.schema.fields]]
      name = "Value added in oil sector"
      type = "string"

      [[resources.schema.fields]]
      name = "Value added in agriculture"
      type = "string"

      [[resources.schema.fields]]
      name = "value added in industries and minings sector "
      type = "string"

      [[resources.schema.fields]]
      name = "value added in industry and mining sector "
      type = "string"

      [[resources.schema.fields]]
      name = "value added in the construction sector"
      type = "string"

      [[resources.schema.fields]]
      name = "Value added in the services sector"
      type = "string"

      [[resources.schema.fields]]
      name = "GDP at market prices"
      type = "string"

      [[resources.schema.fields]]
      name = "Private consumption expenditure"
      type = "string"

      [[resources.schema.fields]]
      name = "Government consumption expenditure"
      type = "string"

      [[resources.schema.fields]]
      name = "Private gross fixed capital formation - Machinery"
      type = "string"

      [[resources.schema.fields]]
      name = "Private gross fixed capital formation - building"
      type = "string"

      [[resources.schema.fields]]
      name = "Government gross fixed capital formation - Machinery"
      type = "string"

      [[resources.schema.fields]]
      name = "Government gross fixed capital formation - building"
      type = "string"

      [[resources.schema.fields]]
      name = "Total gross fixed capital formation"
      type = "string"

      [[resources.schema.fields]]
      name = "Net exports"
      type = "string"

      [[resources.schema.fields]]
      name = "National income"
      type = "string"


