name = "cbibf1714"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385 ,  1394] 
category= ["budget"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["tax", "income"]

[[keywords]]
lang = "fa" 
wordlist = ["مالیات", "درآمد"]

[author]
web = "https://databank.mefa.ir/IPDA_DashBoard/EconoDashBoard.aspx?from=1385&to=1396&f=1&d=2&indicators=339,349,352,351,350,348,353,354"

  [[author.name]] 
  lang = "fa"
  text = "وزارت امور اقتصادی و دارایی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Economic Affairs and finance"

[[title]]
lang = "en" 
text = "directly and indirectly tax revenues from 1385 to 1395" 

[[title]]
lang = "fa"
text = "درآمدهای مالیاتی به تفکیک مستقیم و غیر مستقیم از سال ۱۳۸۵ تا ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصادی و دارایی گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/cbibf1714fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/cbibf1714en.csv"

  [[resources.title]]
  lang = "en" 
  text = "directly and indirectly tax revenues from 1385 to 1395"

  [[resources.title]]
  lang = "fa"
  text = "درآمدهای مالیاتی به تفکیک مستقیم و غیر مستقیم از سال ۱۳۸۵ تا ۱۳۹۵"

  [[resources.sources]]
  name = "Ministry of Economic Affairs and finance" 
  web = "https://databank.mefa.ir/IPDA_DashBoard/EconoDashBoard.aspx?from=1385&to=1396&f=1&d=2&indicators=339,349,352,351,350,348,353,354" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "subject"
      type = "string"

      [[resources.schema.fields]]
      name = "1385"
      type = "string"

      [[resources.schema.fields]]
      name = "1386"
      type = "string"

      [[resources.schema.fields]]
      name = "1387"
      type = "string"

      [[resources.schema.fields]]
      name = "1388"
      type = "string"

      [[resources.schema.fields]]
      name = "1389"
      type = "string"

      [[resources.schema.fields]]
      name = "1390"
      type = "string"

      [[resources.schema.fields]]
      name = "1391"
      type = "string"

      [[resources.schema.fields]]
      name = "1392"
      type = "string"

      [[resources.schema.fields]]
      name = "1393"
      type = "string"

      [[resources.schema.fields]]
      name = "1394"
      type = "string"

      [[resources.schema.fields]]
      name = "1395"
      type = "string"


