name = "cbibf177"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [ 1391 ,  1394] 
category= ["banking", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Monetary Base", "Currency in the hands of people", "Demand deposits, total deposits of non-governmental sector", "Liquidity", "Office of Foreign Assets", "Private sector debt to banks", "Public sector debt in the banking system", "Government debt to the central bank", "Bank debt", "Liability companies and public institutions to the central bank", "Companies and public institutions debt to banks", "The banking system demands from the public and private sectors", "Public sector deposits with the banking system - Government", "Public sector deposits with the banking system - companies and public institutions", "Bank deposits at the central bank - legal"]

[[keywords]]
lang = "fa" 
wordlist = ["پايه پولی", "اسکناس و مسکوک در دست اشخاص", "سپرده‌های ديداری , غيرديداری کل سپرده‌های بخش غيردولتی", "نقدينگی", "دارايی‌های خارجی بانک‌ها", "بدهی بخش غيردولتی به بانک‌ها", "بدهی بخش دولتی به سيستم بانکی", "بدهی دولت به بانک مرکزی", "بدهی دولت به بانک‌ها", "بدهی شرکت‌ها و موسسات دولتی به بانک مرکزی", "بدهی شرکت‌ها و موسسات دولتی به بانک‌ها", "مطالبات سيستم بانکی از بخش‌های دولتی و غيردولتی", "سپرده‌های بخش دولتی نزد سيستم بانکی - دولت", "سپرده‌های بخش دولتی نزد سيستم بانکی - شرکت‌ها و موسسات دولتی", "سپرده‌های بانک‌ها نزد بانک مرکزی - قانونی"]

[author]
web = "http://cbi.ir/datedlist/15532.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Cenral Bank of Iran"

[[title]]
lang = "en" 
text = "Monetary and credit variables between 1391 to 1394" 

[[title]]
lang = "fa"
text = "متغیرهای پولی و اعتباری در سال‌های ۱۳۹۱ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحات ۱۷ تا ۲۰، شاخص‌های عمده اقتصادی سال ١٣۹۵، استخراج شده است.(نماگرهای اقتصادی شماره ۸۵، سه ماهه دوم سال ۱۳۹۵)"

[[description]]
lang = "en"
text = "Dataset exctracted from pages 17 to 20, Main economic indicators in 1395."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf177fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf177en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Monetary and credit variables between 1391 to 1394"

  [[resources.title]]
  lang = "fa"
  text = "متغیرهای پولی و اعتباری در سال‌های ۱۳۹۱ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Cenral Bank of Iran" 
  web = "http://cbi.ir/datedlist/15532.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year and Period"
      type = "string"

      [[resources.schema.fields]]
      name = "Monetary Base"
      type = "string"

      [[resources.schema.fields]]
      name = "Monetary"
      type = "string"

      [[resources.schema.fields]]
      name = "Currency in the hands of people"
      type = "string"

      [[resources.schema.fields]]
      name = "Current Deposits"
      type = "string"

      [[resources.schema.fields]]
      name = "Saving Deposits (Quasi-money)"
      type = "string"

      [[resources.schema.fields]]
      name = "Total private sector deposits"
      type = "string"

      [[resources.schema.fields]]
      name = "Liquidity"
      type = "string"

      [[resources.schema.fields]]
      name = "Net foreign assets - Central Bank"
      type = "string"

      [[resources.schema.fields]]
      name = "Net foreign assets – Banks"
      type = "string"

      [[resources.schema.fields]]
      name = "Net foreign assets - the banking system"
      type = "string"

      [[resources.schema.fields]]
      name = "Private sector debt to the bank - commercial banks"
      type = "string"

      [[resources.schema.fields]]
      name = "Private sector debt to the bank - specialized banks"
      type = "string"

      [[resources.schema.fields]]
      name = "Debt private sector banks - Bank"
      type = "string"

      [[resources.schema.fields]]
      name = "Public sector debt in the banking system"
      type = "string"

      [[resources.schema.fields]]
      name = "Government debt to the central bank"
      type = "string"

      [[resources.schema.fields]]
      name = "Government debt to banks"
      type = "string"

      [[resources.schema.fields]]
      name = "Liability companies and public institutions debt to the central bank"
      type = "string"

      [[resources.schema.fields]]
      name = "Companies and public institutions debt to banks"
      type = "string"

      [[resources.schema.fields]]
      name = "The banking system demands from the public and private sectors"
      type = "string"

      [[resources.schema.fields]]
      name = "Public sector deposits with the banking system - Government"
      type = "string"

      [[resources.schema.fields]]
      name = "Public sector deposits with the banking system - companies and public institutions"
      type = "string"

      [[resources.schema.fields]]
      name = "Banknotes and coins issued"
      type = "string"

      [[resources.schema.fields]]
      name = "Currency to banks"
      type = "string"

      [[resources.schema.fields]]
      name = "Bank deposits at the central bank - legal"
      type = "string"

      [[resources.schema.fields]]
      name = "Bank deposits at the central bank - Meet"
      type = "string"

      [[resources.schema.fields]]
      name = "Central bank to bank debt - commercial banks"
      type = "string"


