name = "cbibf174"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385, 1390] 
category= ["Banking", "Employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Inflation", "Inflation of goods and services", "Food and beverage inflation", "Health inflation", "Education Inflation"]

[[keywords]]
lang = "fa" 
wordlist = ["تورم", "شاخص قیمت کالاها و خدمات", "شاخص قیمت خوراکی‌ها و آشامیدنی‌ها", "شاخص قیمت بهداشت ودرمان", "شاخص قیمت تحصیل"]

[author]
web = "http://www.cbi.ir/page/10057.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Cenral Bank of Iran"

[[title]]
lang = "en" 
text = "The price index (Inflation rate) of consumer goods and services in urban areas of Iran in 1385 to 1390" 

[[title]]
lang = "fa"
text = "شاخص بهای کالاها و خدمات مصرفی (تورم) در مناطق شهری ایران در طی سال‌های ۱۳۸۵ تا ۱۳۹۰"

[[description]]
lang = "fa"
text = "این مجموعه داده به عنوان خلاصه نتايج شاخص بهای كالاها و خدمات مصرفی در مناطق شهری ايران ۱۳۹۰، از صفحه ۲ ، شاخص بهای كالاها وخدمات مصرفی در مناطق شهری ايران 
دی ماه ١٣٩۰، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset of Summary price index of consumer goods and services in urban areas of Iran 1390, exctracted from page 2 of The index of consumer prices of goods and services in urban areas of Iran in 1390."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf174fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf174en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The price index (Inflation rate) of consumer goods and services in urban areas of Iran in 1385 to 1390"

  [[resources.title]]
  lang = "fa"
  text = "شاخص بهای کالاها و خدمات مصرفی (تورم) در مناطق شهری ایران در طی سال‌های ۱۳۸۵ تا ۱۳۹۰"

  [[resources.sources]]
  name = "Cenral Bank of Iran" 
  web = "http://www.cbi.ir/page/10057.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Group"
      type = "string"

      [[resources.schema.fields]]
      name = "Percent change of 1390 to 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Percent change of 1389 to 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Percent change of 1388 to 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Percent change of 1387 to 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Percent change of 1386 to 1385"
      type = "string"


