name = "cbibf1713"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1387] 
category= ["banking"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["interest rate", "savings", "long time", "short term", "banking facilities", "governmental", "NGOs"]

[[keywords]]
lang = "fa" 
wordlist = ["نرخ سود", "تسهیلات", "سپرده", "بلند مدت", "کوتاه مدت", "تسهیلات", "دولتی", "غیر دولتی"]

[author]
web = "http://cbi.ir/page/6511.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Cenral Bank of Iran"

[[title]]
lang = "en" 
text = "Banks interest rates from 1384 to 1387" 

[[title]]
lang = "fa"
text = "نرخ‌های سود بانکی از سال ۱۳۸۴ تا ۱۳۸۷"

[[description]]
lang = "fa"
text = "این داده از صفحه ۱۶ جدول ۲، شاخص‌های عمده اقتصادی سه ماهه چهارم سال ۱۳۸۷، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the table 2 on page 16, Major economic indicators for the second quarter of 1387."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf1713fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bf/cbibf1713en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Interest rates from 1384 to 1387"

  [[resources.title]]
  lang = "fa"
  text = "نرخ‌های سود بانکی از سال ۱۳۸۴ تا ۱۳۸۷"

  [[resources.sources]]
  name = "Cenral Bank of Iran" 
  web = "http://cbi.ir/page/6511.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Title"
      type = "string"

      [[resources.schema.fields]]
      name = "Interest rates on deferred investment deposits,  accounts – normal short term -percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Interest rates on deferred investment deposits,  accounts –special short term -percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Interest rates on deferred investment deposits,  accounts –one year term -percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Interest rates on deferred investment deposits,  accounts –two years term -percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Interest rates on deferred investment deposits,  accounts –three years term -percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Interest rates on deferred investment deposits,  accounts –four years term -percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Interest rates on deferred investment deposits,  accounts –five years term -percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Facilities loan interest rate - industry and mining - percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Facilities loan interest rate - Building and Housing - Housing Savings Fund at  Bank Maskan – percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Facilities loan interest rate - Building and Housing – Others – percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Facilities loan interest rate – Agriculture – percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Facilities loan interest rate – trade, services and miscellaneous – percentage per annum"
      type = "string"

      [[resources.schema.fields]]
      name = "Facilities loan interest rate – exports – percentage per annum"
      type = "string"


