name = "cbiehe1626"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385, 1394] 
category= ["employment", "housing", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Housing", "Household budget"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن", "بودجه خانوار"]

[author]
web = "http://www.cbi.ir/page/15187.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "Average annual gross household spending during the years 1385 to 1394 the cost breakdown of the different groups" 

[[title]]
lang = "fa"
text = "متوسط هزینه ناخالص سالانه یک خانوار به تفکیک گروه‌های مختلف هزینه طی سال‌های ۱۳۸۵ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱ در صفحه ۱۶، نتایج بررسی بودجه خانوار در مناطق شهری ایران سال ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 1 on page 16, The results of 1394 survey of household spending in urban areas."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1626fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1626en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Average annual gross household spending during the years 1385 to 1394 the cost breakdown of the different groups"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزینه ناخالص سالانه یک خانوار به تفکیک گروه‌های مختلف هزینه طی سال‌های ۱۳۸۵ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://www.cbi.ir/page/15187.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Price groups and Years"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1385) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1385)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1386) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1386)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1387) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1387)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1388) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1388)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1389) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1389)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1390) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1390)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1391) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1391)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1392) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1392)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1393) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1393)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1394) in Rials"
      type = "string"


