name = "cbies178"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/13423.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "average gross cost of one households divided by different price bands in different price classes in 1393" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار براي گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies178fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies178en.csv"

  [[resources.title]]
  lang = "en" 
  text = "average gross cost of one households divided by different price bands in different price classes in 1393"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار براي گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۳"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/13423.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "expenditure groups "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – average for a household"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories  - up to 43175200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from  43175201  to 60570300"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  60570301 to 84973600 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  84973601 to 119209000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  119209001 to 167237500"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from  167237501 to 234616300"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  234616301 to 329141700"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  329141701 to 461750800 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  461750801  to 647787200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  647787201  to 908776400 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  908776401  to 1274916500 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  1274916501  to 1788572000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  1788572001  to 2509176000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from  2509176001  to 3520106600"
      type = "string"


