name = "cbies175"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1386 ,  1395] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/16734.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "average gross cost of urban households divided by different price bands from 1386 to 1395" 

[[title]]
lang = "fa"
text = "متوسط هزینه ناخالص خانوار شهری به تفکیک گروه‌های مختلف هزینه طی سال‌های ۱۳۸۶ تا ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies175fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies175en.csv"

  [[resources.title]]
  lang = "en" 
  text = "average gross cost of urban households divided by different price bands from 1386 to 1395"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزینه ناخالص خانوار شهری به تفکیک گروه‌های مختلف هزینه طی سال‌های ۱۳۸۶ تا ۱۳۹۵"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/16734.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "price groups "
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "distribution percentage – 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "cost in IRR – 1395"
      type = "string"


