name = "cbies179"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1392] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/12254.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "average gross cost of one households divided by different price bands in different price classes in 1392" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار براي گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۲"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies179fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies179en.csv"

  [[resources.title]]
  lang = "en" 
  text = "average gross cost of one households divided by different price bands in different price classes in 1392"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار براي گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۲"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/12254.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "expenditure groups "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – average for a household"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – up to 29047300 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 29047301  to 42398700"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 42398701 to 61886900 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 61886901 to 90332800"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 90332801 to 131853600"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 131853601 to 192459100"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 192459101 to 280921600"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 280921601 to 410045200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 410045201  to 598519600 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 598519601  to 873624800 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 873624801  to 1275180200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 1275180201  to 1861307600 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 1861307601  to 2716844400 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 2716844401  to 3965622400"
      type = "string"


