name = "cbies176"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1395, 1395] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/16734.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "average gross cost of one households divided by different price bands in different price classes in 1395" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies176fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies176en.csv"

  [[resources.title]]
  lang = "en" 
  text = "average gross cost of one households divided by different price bands in different price classes in 1395"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۵"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/16734.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "expenditure groups "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – average for a household"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – up to 51168600"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 51168601 to 66944200"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 66944201 to 87583500"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 87583501 to 114586000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 114586001 to  149913500"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 149913501 to 196132800"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 196132801 to 256601700"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 256601701 to 335713500"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 335713501 to 439215900"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 439215901 to 574628800"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 574628801 to 751790300"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 751790301 to 983571700"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 983571701 to 1286812600"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 1286812601 to 1683544600"
      type = "string"


