name = "cbiehe1727"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1389, 1389] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Cost of household", "Price bands", "Deciles cost"]

[[keywords]]
lang = "fa" 
wordlist = ["هزینه خانوار", "گروه‌های هزینه", "دهک‌های هزینه"]

[author]
web = "http://www.cbi.ir/page/9157.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Cenral Bank of Iran"

[[title]]
lang = "en" 
text = "The average annual gross household expenditure based on different groups of costs in cost deciles in year 1389" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار به تفكيک گروه‌های مختلف هزينه در دهک‌های هزينه در سال ۱۳۸۹"

[[description]]
lang = "fa"
text = "این مجموعه داده از جدول شماره ۳۶ در صفحه ۶۵، نتایج بررسی بودجه خانوار در مناطق شهری ایران سال ۱۳۸۹ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 36 on page 65, Results household budget survey in urban areas of Iran in 1389."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1727fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1727en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average annual gross household expenditure based on different groups of costs in cost deciles in year 1389"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار به تفكيک گروه‌های مختلف هزينه در دهک‌های هزينه در سال ۱۳۸۹"

  [[resources.sources]]
  name = "Cenral Bank of Iran" 
  web = "http://www.cbi.ir/page/9157.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Price groups / cost deciles"
      type = "string"

      [[resources.schema.fields]]
      name = "The average for a household - cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Forth decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile – cost in Rial"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile – cost in Rial"
      type = "string"


