name = "cbiehe1627"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1376, 1385] 
category= ["employment", "housing", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Housing", "Household budget"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن", "بودجه خانوار"]

[author]
web = "http://www.cbi.ir/page/4730.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "Average annual gross household spending during the years 1376 to 1385 the cost breakdown of the different groups" 

[[title]]
lang = "fa"
text = "متوسط هزینه ناخالص سالانه یک خانوار به تفکیک گروه‌های مختلف هزینه طی سال‌های ۱۳۷۶ تا ۱۳۸۵"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱ در صفحه ۱۶، نتایج بررسی بودجه خانوار در مناطق شهری ایران سال ۱۳۸۵، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 1 on page 16, The results of 1385 survey of household spending in urban areas."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1627fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1627en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Average annual gross household spending during the years 1376 to 1385 the cost breakdown of the different groups"

  [[resources.title]]
  lang = "fa"
  text = "بررسی بودجه خانوار در مناطق شهری ایران، متوسط هزینه ناخالص سالانه یک خانوار به تفکیک گروه‌های مختلف هزینه طی سال‌های ۱۳۷۶ تا ۱۳۸۵"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://www.cbi.ir/page/4730.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Price groups and Years"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1376) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1376)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1377) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1377)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1378) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1378)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1379) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1379)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1380) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1380)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1381) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1381)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1382) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1382)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1383) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1383)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1384) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1384)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1385) in Rials"
      type = "string"


