name = "cbies177"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/15187.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "average gross cost of one households divided by different price bands in different price classes in 1394" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار براي گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies177fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies177en.csv"

  [[resources.title]]
  lang = "en" 
  text = "average gross cost of one households divided by different price bands in different price classes in 1394"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار براي گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/15187.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "expenditure groups "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – average for a household"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – up to 49811500"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 49811501 to69303600"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 69303601 to 96423300"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 96423301 to 134155300"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 134155301 to 186652700"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 186652701 to 259693100"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 259693101 361315500"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 361315501 to 502704500 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 502704501 to 699421500 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 699421501 to 973117200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 973117201 to 1353914900 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 1353914901  to 1883725300 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 1883725301 to 2620859600 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 2620859601  to 3646447400"
      type = "string"


