name = "cbiehe1625"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1393] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Household income", "Urban Areas", "Family economy", "Household expenditure"]

[[keywords]]
lang = "fa" 
wordlist = ["درامد خانوار", "مناطق شهری", "اقتصاد خانواده", "هزینه خانوار"]

[author]
web = "http://cbi.ir/page/13423.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "Household budget survey in urban areas of average annual gross household income and the share of income groups during the years 1393- 1384" 

[[title]]
lang = "fa"
text = "بررسی بودجه خانوار در مناطق شهری ايران- متوسط درآمد ناخالص سالانه يك خانوار و سهم گروه‌های مختلف درآمد طی سال‌های ۱۳۹۳- ۱۳۸۴"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۸ در صفحه ۲۶ نتایج بررسی بودجه خانوار در مناطق شهری ایران سال ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 8, page 26, of the Results household budget survey in urban areas of Iran in 1393."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1625fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1625en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Household budget survey in urban areas of average annual gross household income and the share of income groups during the years 1393- 1384"

  [[resources.title]]
  lang = "fa"
  text = "بررسي بودجه خانوار در مناطق شهري ايران متوسط درآمد ناخالص سالانه يك خانوار و سهم گروه هاي م ت   درآمد طي سال هاي 1393- 1384"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/13423.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Income groups and years"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1384"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1384"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Income 1393"
      type = "string"


