name = "cbiehe1719"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385 , 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Amount of annual consumption", "Urban household", "Food", "Beverages", "Tobacco"]

[[keywords]]
lang = "fa" 
wordlist = ["مقدار مصرف سالانه", "خانوار شهری", "خوراكی‌ها", "آشاميدنی‌ها", "دخانيات"]

[author]
web = "http://cbi.ir/page/15187.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Cenral Bank of Iran"

[[title]]
lang = "en" 
text = "The average annual consumption of some food items, beverages and tobacco of an urban household during the years 1385 - 1394" 

[[title]]
lang = "fa"
text = "متوسط مقدار مصرف سالانه برخی اقلام خوراكی‌ها، آشاميدنی‌ها و دخانيات يک خانوار شهری طی سال‌های ۱۳۸۵ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این مجموعه داده از جدول شماره ۶ در صفحه ۲۴، نتایج بررسی بودجه خانوار در مناطق شهری ایران سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 6 on page 24, Results household budget survey in urban areas of Iran in 1394."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1719fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1719en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average annual consumption of some food items, beverages and tobacco of an urban household during the years 1385 - 1394"

  [[resources.title]]
  lang = "fa"
  text = "متوسط مقدار مصرف سالانه برخی اقلام خوراكی‌ها، آشاميدنی‌ها و دخانيات يک خانوار شهری طی سال‌های ۱۳۸۵ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Cenral Bank of Iran" 
  web = "http://cbi.ir/page/15187.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Food items, beverages, tobacco / year"
      type = "string"

      [[resources.schema.fields]]
      name = "1385(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1386(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1387(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1388(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1389(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1390(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1391(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1392(Quantity in kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "1393(Quantity in kg)"
      type = "string"


