name = "cbies1714"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1387, 1387] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/6945.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "average annual gross household expenses for different income groups in gross income categories in 1387" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۸۷"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies1714fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies1714en.csv"

  [[resources.title]]
  lang = "en" 
  text = "average annual gross household expenses for different income groups in gross income categories in 1387"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۸۷"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/6945.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "expenditure groups "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – average for a household"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – up to 13097500  "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 13097501  to 17568000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 17568001 to 23565000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 23565001 to 31608000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 31608001 to 42398000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 42398001 to 56870000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 56870001 to 76280000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 76280001 to 102320000  "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 102320001  to 137240000  "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 137240001 to 184090000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 184090001 to 246930000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 246930001 to 331220000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 331220001 to 444270000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 444270001 to 595920000"
      type = "string"


