name = "cbies1711"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1390, 1390] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/10974.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "average annual gross household expenses for different income groups in gross income categories in 1390" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies1711fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies1711en.csv"

  [[resources.title]]
  lang = "en" 
  text = "average annual gross household expenses for different income groups in gross income categories in 1390"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۹۰"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/10974.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "expenditure groups "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – average for a household"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – up to 19435200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 19435201 to 26123000"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 26123001 to 35112200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 35112201 to  47194600"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 47194601 to 63434800"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 63434801 to  85263200"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 85263201 to  114603100"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 114603101 to 154039100  "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 154039101 to  207045300  "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 207045301 to  278291500 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 278291501 to  374054200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – from 374054201 to 502769700 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 502769701 to  675777300 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 675777301 to  908318500"
      type = "string"


