name = "cbiehe1624"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1393] 
category= ["employment", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Household expenditure", "Family economy", "Household income"]

[[keywords]]
lang = "fa" 
wordlist = ["هزینه خانوار", "اقتصاد خانواده", "درامد خانوار"]

[author]
web = "http://cbi.ir/page/13423.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "Average household annual net cost to the cost of separation of different groups during the years 1384 to 1393" 

[[title]]
lang = "fa"
text = "متوسط هزينه خالص سالانه يك خانوار به تفكيك گروه‌های مختلف هزينه طی سال‌های ۱۳۸۴ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۳ در صفحه ۲۰ نتایج بررسی بودجه خانوار در مناطق شهری ایران سال ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 3, page 20, of the Results household budget survey in urban areas of Iran in 1393."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1624fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/cbiehe1624en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Average household annual net cost to the cost of separation of different groups during the years 1384 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه خالص سالانه يك خانوار به تفكيك گروه‌های مختلف هزينه طی سال‌های ۱۳۸۴ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/13423.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Price groups and Years"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1384) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1384)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1385) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1385)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1386) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1386)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1387) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1387)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1388) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1388)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1389) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1389)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1390) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1390)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1391) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1391)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1392) in Rials"
      type = "string"

      [[resources.schema.fields]]
      name = "Distribution Rate (1392)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost (1393) in Rials"
      type = "string"


