name = "cbies1712"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1389, 1389] 
category= ["economics", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price bands", "relative poverty line"]

[[keywords]]
lang = "fa" 
wordlist = ["گروه‌های هزینه", "خط فقر نسبی"]

[author]
web = "http://cbi.ir/page/9157.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی ایران"

  [[author.name]]
  lang = "en"
  text = "Central Bank of Iran"

[[title]]
lang = "en" 
text = "Average annual gross household expenses for different income groups in gross income categories in 1389" 

[[title]]
lang = "fa"
text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۸۹"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی وزارت امور اقتصاد و دارایی، مديريت كل آمارهای اقتصادی، اداره آمار اقتصادی، دايره بررسی بودجه خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The Economic Affairs and Finance, the General Directorate of Economic Statistics, the Bureau of Economic Statistics, the Household Budget Survey Circle."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies1712fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/cbies1712en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Average annual gross household expenses for different income groups in gross income categories in 1389"

  [[resources.title]]
  lang = "fa"
  text = "متوسط هزينه ناخالص سالانه يک خانوار برای گروه‌های مختلف هزينه در طبقات هزينه ناخالص در سال ۱۳۸۹"

  [[resources.sources]]
  name = "Central Bank of Iran" 
  web = "http://cbi.ir/page/9157.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "expenditure groups "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – average for a household"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories – up to 14387200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 14387201 to 21935400"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 21935401 to 29342100 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 29342101 to 39303300"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 39303301 to 52410200"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 52410201 to 70422400"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 70422401 to 94245400"
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 94245401 to  124180800  "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 124180801 to  148901800  "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 148901801 to  224087000 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 224087001 to 302434200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 302434201 to 405095800 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 405095801 to 542249200 "
      type = "string"

      [[resources.schema.fields]]
      name = "expenditure categories - from 542249201 to 725838400"
      type = "string"


