name = "cbitd1734"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1387 ,  1390] 
category= ["trade", "energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["exports", "importation", "oil income", "oil exports", "non-oil exports", "trade balance"]

[[keywords]]
lang = "fa" 
wordlist = ["صادرات", "واردات", "درآمد نفت", "صادرات نفتی", "صادرات غیرنفتی", "تراز تجاری"]

[author]
web = "http://cbi.ir/page/10523.aspx"

  [[author.name]] 
  lang = "fa"
  text = "بانک مرکزی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Cenral Bank of Iran"

[[title]]
lang = "en" 
text = "Balance of payments - current account (exports and imports of Iran) between 1387 to 1390" 

[[title]]
lang = "fa"
text = "تراز پرداخت‌ها - حساب جاری (آمار صادرات و واردات ایران) سال ۱۳۸۷ تا ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از جدول صفحه ۱۳، شاخص‌های عمده اقتصادی سه ماهه چهارم سال ۱۳۹۰، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the table on page 13, Major economic indicators for the forth quarter of 1390."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/cbitd1734fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/cbitd1734en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Balance of payments - current account (exports and imports of Iran) between 1387 to 1390"

  [[resources.title]]
  lang = "fa"
  text = "تراز پرداخت‌ها - حساب جاری (آمار صادرات و واردات ایران) سال ۱۳۸۷ تا ۱۳۹۰"

  [[resources.sources]]
  name = "Cenral Bank of Iran" 
  web = "http://cbi.ir/page/10523.aspx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Export of goods (FOB) - oil exports (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Export of goods (FOB) - non-oil exports (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Export of goods (FOB) - Total (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Import of goods (FOB) - Gas and oil products (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Import of goods (FOB) - Other goods (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Import of goods (FOB) - Total (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Product accounts (net) (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Account Services - Exports of services (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Account Services - Imports of services (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Account Services - net (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Revenue Account – Receipt (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Revenue Account - Payments (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income - net (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = " Current Transfer Account – Receipt (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "The current transfer account – Payment (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "The current transfer account - net (million dollars)"
      type = "string"


