name = "iprcibgs1744"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1395, 1395] 
category= ["budget"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["budget", "budget settlement"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه", "تفریغ بودجه"]

[author]
web = "http://rc.majlis.ir/fa/report/show/1021290"

  [[author.name]] 
  lang = "fa"
  text = "مرکز پژوهش‌های مجلس شورای اسلامی"

  [[author.name]]
  lang = "en"
  text = "Islamic Parliament Research Center Of Iran"

[[title]]
lang = "en" 
text = "Budget settlement single article of budget law of the country in 1395" 

[[title]]
lang = "fa"
text = "تفريغ ماده واحده قانون بودجه سال ۱۳۹۵ كل کشور"

[[description]]
lang = "fa"
text = "این داده از سایت دیوان محاسبه کل کشور گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the website of Supreme Audit Court."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/iprcibgs1744fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/iprcibgs1744en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Budget settlement single article of budget law of the country in 1395"

  [[resources.title]]
  lang = "fa"
  text = "تفريغ ماده واحده قانون بودجه سال ۱۳۹۵ كل کشور"

  [[resources.sources]]
  name = "Islamic Parliament Research Center Of Iran" 
  web = "http://rc.majlis.ir/fa/report/show/1021290" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "title"
      type = "string"

      [[resources.schema.fields]]
      name = "لایحه (میلیارد ریال - درصد)"
      type = "string"

      [[resources.schema.fields]]
      name = "مصوب (میلیارد ریال – درصد)"
      type = "string"

      [[resources.schema.fields]]
      name = "تغییرات مجلس (میلیارد ریال – درصد)"
      type = "string"

      [[resources.schema.fields]]
      name = "عملکرد (میلیارد ریال – درصد)"
      type = "string"

      [[resources.schema.fields]]
      name = "میزان انحراف عملکرد از لایحه (میلیارد ریال – درصد)"
      type = "string"

      [[resources.schema.fields]]
      name = "میزان انحراف عملکرد از مصوب (میلیارد ریال – درصد)"
      type = "string"

      [[resources.schema.fields]]
      name = "درصد تحقق نسبت به لایحه (میلیارد ریال – درصد)"
      type = "string"


