name = "irmfbgs1733"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1391, 1391] 
category= ["budget"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Mostazafan foundation", "tax", "tax exemption"]

[[keywords]]
lang = "fa" 
wordlist = ["بنیاد مستضعفان", "مالیات", "معافیت مالیاتی"]

[author]
web = "http://www.irmf.ir/images/Financial/links/91.TIF"

  [[author.name]] 
  lang = "fa"
  text = "بنیاد مستضعفان انقلاب اسلامی"

  [[author.name]]
  lang = "en"
  text = "Islamic Revolution Mostazafan Foundation"

[[title]]
lang = "en" 
text = "Islamic Revolution Mostazafan Foundation - consolidated balance sheet 1391" 

[[title]]
lang = "fa"
text = "بنیاد مستضعفان انقلاب اسلامی - ترازنامه تلفیقی سال ۱۳۹۱"

[[description]]
lang = "fa"
text = "این داده از جدول صفحه شماره ۲ بنیاد مستضعفان انقلاب اسلامی، گزارش حسابرس مستقل و بازرس به انضمام صورت‌های مالی تلفیقی گروه و واحد اصلی برای سال مالی منتهی به ۳۰ اسفند ماه ۱۳۹۱ است."

[[description]]
lang = "en"
text = "Dataset extracted from page number 2 table of Islamic Republic of Mostazafan foundation, independent auditor and inspectorate report, including consolidated financial statements of the group and the main unit for the fiscal year ending 30th of esfand 1391."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/irmfbgs1733fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/irmfbgs1733en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Islamic Revolution Mostazafan Foundation - consolidated balance sheet 1391"

  [[resources.title]]
  lang = "fa"
  text = "بنیاد مستضعفان انقلاب اسلامی - ترازنامه تلفیقی سال ۱۳۹۱"

  [[resources.sources]]
  name = "Islamic Revolution Mostazafan Foundation" 
  web = "http://www.irmf.ir/images/Financial/links/91.TIF" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "subject"
      type = "string"

      [[resources.schema.fields]]
      name = "title"
      type = "string"

      [[resources.schema.fields]]
      name = "title description"
      type = "string"

      [[resources.schema.fields]]
      name = "1391/12/30 – million IRR"
      type = "string"


