name = "majes168"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1391, 1391] 
category= ["economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Sales amount of fertilizers", "Sales amont of chemical pesticides"]

[[keywords]]
lang = "fa" 
wordlist = ["فروش انواع کود", "فروش سموم شیمیایی"]

[author]
web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=71539e78-a50b-4043-923c-941e03db6091"

  [[author.name]] 
  lang = "fa"
  text = "وزارت جهاد کشاورزی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Agriculture-Jahad"

[[title]]
lang = "en" 
text = "The sale of a variety of chemical toxins into separate provinces in 1391" 

[[title]]
lang = "fa"
text = "ميزان فروش انواع سموم شيميايی به تفكيک استانی در سال ۱۳۹۱"

[[description]]
lang = "fa"
text = "این داده از جدول ۱-۳-۲ در صفحه ۵۳، جلد دوم آمارنامه کشاورزی سال ۱۳۹۱ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from 1-3-2 table on page 53, the second volume of agricultural statistics in 1391."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes168fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes168en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The sale of a variety of chemical toxins into separate provinces in 1391"

  [[resources.title]]
  lang = "fa"
  text = "ميزان فروش انواع سموم شيميايی به تفكيک استانی در سال ۱۳۹۱"

  [[resources.sources]]
  name = "Ministry of Agriculture-Jahad" 
  web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=71539e78-a50b-4043-923c-941e03db6091" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Total (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Insecticide (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Acaricides (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Fungicides (litres / kg)"
      type = "string"


