name = "majes166"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1393] 
category= ["economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Biological control of pests in agriculture", "Non-chemical control of pests in agriculture"]

[[keywords]]
lang = "fa" 
wordlist = ["مبارزه بیولوژیک آفات در زراعت", "مبارزه غیرشیمیایی آفات در زراعت"]

[author]
web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=7eee653c-da90-4b87-9784-b126f3a4f284"

  [[author.name]] 
  lang = "fa"
  text = "وزارت جهاد کشاورزی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Agriculture-Jahad"

[[title]]
lang = "en" 
text = "Non-chemical pest and disease battling performance in the years 1392 and 1393" 

[[title]]
lang = "fa"
text = "عملكرد مبارزه غير شيميايی با آفات و بيماری‌ها در سال‌های ۱۳۹۲ و ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول ۱-۴-۱۴ در صفحه ۷۴، جلد دوم آمارنامه کشاورزی سال ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset from 1-4-14 table on page 74, the second volume of agricultural statistics in 1393 has been extracted."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes166fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes166en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Non-chemical pest and disease battling performance in the years 1392 and 1393"

  [[resources.title]]
  lang = "fa"
  text = "عملكرد مبارزه غير شيميايی با آفات و بيماری‌ها در سال‌های ۱۳۹۲ و ۱۳۹۳"

  [[resources.sources]]
  name = "Ministry of Agriculture-Jahad" 
  web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=7eee653c-da90-4b87-9784-b126f3a4f284" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description / Year"
      type = "string"

      [[resources.schema.fields]]
      name = "1392"
      type = "string"


