name = "majes167"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1393] 
category= ["economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Sales amount of fertilizers", "Sales amont of chemical pesticides"]

[[keywords]]
lang = "fa" 
wordlist = ["فروش انواع کود", "فروش سموم شیمیایی"]

[author]
web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=7eee653c-da90-4b87-9784-b126f3a4f284"

  [[author.name]] 
  lang = "fa"
  text = "وزارت جهاد کشاورزی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Agriculture-Jahad"

[[title]]
lang = "en" 
text = "Sales amount of fertilizers and chemical pesticides in the years 1392 and 1393" 

[[title]]
lang = "fa"
text = "ميزان فروش انواع كود و سموم شيميايی در سال‌های ۱۳۹۲ و ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول ۱-۳-۱ در صفحه ۴۵، جلد دوم آمارنامه کشاورزی سال ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset from 1-3-1 table on page 45, the second volume of agricultural statistics in 1393 has been extracted."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes167fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes167en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Sales amount of fertilizers and chemical pesticides in the years 1392 and 1393"

  [[resources.title]]
  lang = "fa"
  text = "ميزان فروش انواع كود و سموم شيميايی در سال‌های ۱۳۹۲ و ۱۳۹۳"

  [[resources.sources]]
  name = "Ministry of Agriculture-Jahad" 
  web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=7eee653c-da90-4b87-9784-b126f3a4f284" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description / type"
      type = "string"

      [[resources.schema.fields]]
      name = "سال ۱۳۹۲"
      type = "string"


