name = "majes169"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1390, 1390] 
category= ["economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Chemical pesticides"]

[[keywords]]
lang = "fa" 
wordlist = ["سموم شیمیایی"]

[author]
web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=74b3ae39-269e-41ac-92af-97c1aa8b3992"

  [[author.name]] 
  lang = "fa"
  text = "وزارت جهاد کشاورزی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Agriculture-Jahad"

[[title]]
lang = "en" 
text = "The amount of pesticide sales figures by province in 1390" 

[[title]]
lang = "fa"
text = "ميزان فروش سموم شيميايی به تفكيک استان در سال ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از جدول ۱-۳-۲ در صفحه ۷۱، جلد دوم آمارنامه کشاورزی سال ۱۳۹۰ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset from 1-3-2 table on page 71, the second volume of agricultural statistics in 1390 has been extracted."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes169fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes169en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The amount of pesticide sales figures by province in 1390"

  [[resources.title]]
  lang = "fa"
  text = "ميزان فروش سموم شيميايی به تفكيک استان در سال ۱۳۹۰"

  [[resources.sources]]
  name = "Ministry of Agriculture-Jahad" 
  web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=74b3ae39-269e-41ac-92af-97c1aa8b3992" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Total (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Insecticide (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Acaricides (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Fungicides (litres / kg)"
      type = "string"


