name = "majes1611"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1388, 1388] 
category= ["economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Chemical pesticides"]

[[keywords]]
lang = "fa" 
wordlist = ["سموم شیمیایی"]

[author]
web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=ab04e9fe-a2e0-488b-9eb4-3bb19d99a24f"

  [[author.name]] 
  lang = "fa"
  text = "وزارت جهاد کشاورزی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Agriculture-Jahad"

[[title]]
lang = "en" 
text = "The amount of pesticide sales figures by province in 1388" 

[[title]]
lang = "fa"
text = "ميزان فروش سموم شيميايی به تفكيک استان در سال ۱۳۸۸"

[[description]]
lang = "fa"
text = "این داده از جدول ۱-۳-۲ در صفحه ۶۱، جلد دوم آمارنامه کشاورزی سال ۱۳۸۸ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset from 1-3-2 table on page 61, the second volume of agricultural statistics in 1388 has been extracted."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes1611fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/majes1611en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The amount of pesticide sales figures by province in 1388"

  [[resources.title]]
  lang = "fa"
  text = "ميزان فروش سموم شيميايی به تفكيک استان در سال ۱۳۸۸"

  [[resources.sources]]
  name = "Ministry of Agriculture-Jahad" 
  web = "http://www.maj.ir/Portal/File/ShowFile.aspx?ID=ab04e9fe-a2e0-488b-9eb4-3bb19d99a24f" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Total (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Insecticide (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Acaricides (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Fungicides (litres / kg)"
      type = "string"

      [[resources.schema.fields]]
      name = "Herbicide (liters / kg)"
      type = "string"


