name = "mmbgs1746-mashhad_municipality_annual_budget-1395"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1395, 1395] 
category= ["budget"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Mashhad", "budget", "municipality"]

[[keywords]]
lang = "fa" 
wordlist = ["مشهد", "بودجه", "شهرداری"]

[author]
web = "https://pbc.mashhad.ir//parameters/mashhad/modules/cdk/upload/content/regulations/1192/1471160376061i1u106pj065frlmgi4g4voh490.pdf"

  [[author.name]] 
  lang = "fa"
  text = "شهرداری مشهد"

  [[author.name]]
  lang = "en"
  text = "Mashhad municipality"

[[title]]
lang = "en" 
text = "Resources derived from the allocation of capital assets of Mashhad municipality according to clauses and components in 1395" 

[[title]]
lang = "fa"
text = "منابع حاصل از واگذاری دارایی‌های سرمایه‌ای شهرداری مشهد بر حسب بند و اجزا در سال ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۶ صفحه ۱۹ گزارش بودجه سال ۱۳۹۵ شهرداری مشهد گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 6 on page 19, the report of Mashhad municipality annual budget for 1395"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/mmbgs1746-mashhad_municipality_annual_budget-1395-fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/mmbgs1746-mashhad_municipality_annual_budget-1395-en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Resources derived from the allocation of capital assets of Mashhad municipality according to clauses and components in 1395"

  [[resources.title]]
  lang = "fa"
  text = "منابع حاصل از واگذاری دارایی‌های سرمایه‌ای شهرداری مشهد بر حسب بند و اجزا در سال ۱۳۹۵"

  [[resources.sources]]
  name = "Mashhad municipality" 
  web = "https://pbc.mashhad.ir//parameters/mashhad/modules/cdk/upload/content/regulations/1192/1471160376061i1u106pj065frlmgi4g4voh490.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "code"
      type = "string"

      [[resources.schema.fields]]
      name = "title"
      type = "string"

      [[resources.schema.fields]]
      name = "performance of year 1393  (thousand IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "approved of year 1394 (thousand IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "approved in 1395 – depositing of capital assets – cash (thousand IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "approved in 1395 – transfer of capitak assets – semi cash (thousand IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "total (thousand IRR)"
      type = "string"


