name = "mporgbgs167"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Budget for year 1394", "Budget for sectors"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه سال ۱۳۹۴", "بودجه وزارتخانه‌ها"]

[author]
web = "http://iod.dataset.s3.amazonaws.com/Sources/mporg71.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان مدیریت و برنامه‌ریزی کشور"

  [[author.name]]
  lang = "en"
  text = "Management and Planning Organisation of Iran"

[[title]]
lang = "en" 
text = "The executive budget summary for the year 1394" 

[[title]]
lang = "fa"
text = "خلاصه بودجه دستگاه‌های اجرایی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۷ در صفحات ۷۱ تا ۱۷۵، قانون بودجه سال ۱۳۹۴ کل کشور، این داده از جدول شماره ۷ در صفحات ۷۱ تا ۱۷۵، قانون بودجه سال ۱۳۹۴ کل کشور، استخراج شده است. در این مجموعه داده، تنها بودجه دستگاه‌های اصلی (بدون زیر مجموعه‌‌هایشان) آمده است.استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 7 on pages 71 to 175, The country's 1394 budget law. In this dataset, only the main executive agencies (without their subdivisions) are mentioned."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/mporgbgs167fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/mporgbgs167en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The executive budget summary for the year 1394"

  [[resources.title]]
  lang = "fa"
  text = "خلاصه بودجه دستگاه‌های اصلی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Management and Planning Organisation of Iran" 
  web = "http://iod.dataset.s3.amazonaws.com/Sources/mporg71.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Title / Device Code"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs / performance in 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs / approved in 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs /estimates 1394/ entitlement"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs /estimates 1394/ others"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs /estimates 1394/ total"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / dedicated 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Acquisition of capital assets"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Financial assets acquisition"
      type = "string"


