name = "mporgbgs1712"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1392] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Public budget", "Welfare and Social Security", "Environment", "Education"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه دولت", "بودجه عمومی", "رفاه و تامین اجتماعی", "محیط زیست", "آموزش و پرورش"]

[author]
web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1392.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان مدیریت و برنامه‌ریزی کشور"

  [[author.name]]
  lang = "en"
  text = "Management and Planning Organisation of Iran"

[[title]]
lang = "en" 
text = "Current and Capital Expenditures Estimates by Category in 1392" 

[[title]]
lang = "fa"
text = "برآورد اعتبارات هزينه‌ای و تملک دارایی‌های سرمایه‌ای بر حسب امور.فصل در سال ۱۳۹۲"

[[description]]
lang = "fa"
text = "این داده از جدول شماره  ۶ در صفحات ۹۴ و ۹۵، قانون بودجه سال ۱۳۹۲ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 6 on pages 94 to 95, The country's 1392 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/mporgbgs1712fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/mporgbgs1712en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Financial estimation of costs and acquisition of capital assets disaggregated by chapter and topic in 1392"

  [[resources.title]]
  lang = "fa"
  text = "برآورد اعتبارات هزينه ای و تملک دارايی های سرمايه ای بر حسب امورفصل در سال ۱۳۹۲"

  [[resources.sources]]
  name = "Management and Planning Organisation of Iran" 
  web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1392.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Classification number"
      type = "string"

      [[resources.schema.fields]]
      name = "Subject"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - of public resources - national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - of public resources - Provincial (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - from private sources - National (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - from private sources – Provincial (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - Total (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Acquisition of capital assets – national (million IRR) "
      type = "string"

      [[resources.schema.fields]]
      name = "Acquisition of capital assets – provincial (million IRR) "
      type = "string"

      [[resources.schema.fields]]
      name = "Acquisition of capital assets – total (million IRR) "
      type = "string"

      [[resources.schema.fields]]
      name = "Total – national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – provincial (million IRR)"
      type = "string"


