name = "mrudho164"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385, 1390] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Housing", "Empty units", "Housing supply", "Housing unused", "Empty housing units in urban areas", "Empty housing units in rural areas"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن", "واحدهای خالی", "عرضه مسکن", "مسکن بلا استفاده", "واحدهای مسکونی خالی در مناطق شهری", "واحدهای مسکونی خالی در مناطق روستایی"]

[author]
web = "http://www.pnu.ac.ir/portal/File/ShowFile.aspx?ID=4ffc4ba2-da33-4f59-b4ee-5de53bb3c0a11"

  [[author.name]] 
  lang = "fa"
  text = "وزارت راه و شهرسازی، سازمان ملی زمین و مسکن"

  [[author.name]]
  lang = "en"
  text = "Ministry of Road & Urban Development of Iran, The National Land & Housing Organisation"

[[title]]
lang = "en" 
text = "Estimation of empty houses in urban and rural areas in the years 1385 and 1390" 

[[title]]
lang = "fa"
text = "برآورد خانه‌های خالی در مناطق شهری و روستایی کشور در سال‌های ۱۳۸۵ و ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۴۸ در صفحه ۴۴، مطالعات بازنگری طرح جامع مسکن، سند راهبردی و چشم انداز کلان بخش مسکن در افق ۱۴۰۵ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset from table 48 on page 44, studies Reload comprehensive housing plan, Horizon 1405 strategic document and outlook for the housing sector overall has been extracted."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/mrudho164fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/mrudho164en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Estimation of empty houses in urban and rural areas in the years 1385 and 1390"

  [[resources.title]]
  lang = "fa"
  text = "برآورد خانه‌های خالی در مناطق شهری و روستایی کشور در سال‌های ۱۳۸۵ و ۱۳۹۰"

  [[resources.sources]]
  name = "Ministry of Road & Urban Development of Iran, The National Land & Housing Organisation" 
  web = "http://www.pnu.ac.ir/portal/File/ShowFile.aspx?ID=4ffc4ba2-da33-4f59-b4ee-5de53bb3c0a11" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "The entire country – 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "The entire country – 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas – 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas – 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas – 1385"
      type = "string"


