name = "mrudho1743-mehr_housing_applicants_divided_by_education_and_provinces-1392"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1392] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["mehr housing", "housing", "household", "education level"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن مهر", "مسکن", "خانوار", "سطح تحصیلات"]

[author]
web = "http://bit.ly/2zX2EQO"

  [[author.name]] 
  lang = "fa"
  text = "وزارت راه و شهرسازی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Road and Urban Development"

[[title]]
lang = "en" 
text = "Distribution of Mehr housing applicants divided by education level and provinces in 1392" 

[[title]]
lang = "fa"
text = "توزيع متقاضيان مسكن مهر بر حسب سطح تحصیلات و استان در سال ۱۳۹۲"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۸۱ صفحه ۳۵۷ گزارش شناخت، مستندسازی و ارزيابی برنامه مسكن مهر از سایت رسمی وزارت راه و شهرسازی گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 81, page 357, Report on the Recognition, Documentation and Evaluation of the Mehr Housing Program, from the official site of the Ministry of Roads and Urban Planning."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/mrudho1743-mehr_housing_applicants_divided_by_education_and_provinces-1392-en.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/mrudho1743-mehr_housing_applicants_divided_by_education_and_provinces-1392-fa.csv"

  [[resources.title]]
  lang = "en" 
  text = "Distribution of Mehr housing applicants divided by education level and provinces in 1392"

  [[resources.title]]
  lang = "fa"
  text = "توزيع متقاضيان مسكن مهر بر حسب سطح تحصیلات و استان در سال ۱۳۹۲"

  [[resources.sources]]
  name = "Ministry of Road and Urban Development" 
  web = "http://bit.ly/2zX2EQO" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "نام استان"
      type = "string"

      [[resources.schema.fields]]
      name = "بیسواد"
      type = "string"

      [[resources.schema.fields]]
      name = "زیر دیپلم"
      type = "string"

      [[resources.schema.fields]]
      name = "دیپلم یا معادل"
      type = "string"

      [[resources.schema.fields]]
      name = "دانشجو"
      type = "string"

      [[resources.schema.fields]]
      name = "فوق دیپلم یا معادل"
      type = "string"

      [[resources.schema.fields]]
      name = "لیسانس یا معادل"
      type = "string"

      [[resources.schema.fields]]
      name = "فوق لیسانس یا معادل"
      type = "string"

      [[resources.schema.fields]]
      name = "دکتری یا معادل"
      type = "string"

      [[resources.schema.fields]]
      name = "نامشخص"
      type = "string"


