name = "mrudho1746-mehr_housing_divided_by_cities_new_cities-1392"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1392] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Mehr housing", "housing", "household"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن مهر", "مسکن", "خانوار"]

[author]
web = "http://bit.ly/2zX2EQO"

  [[author.name]] 
  lang = "fa"
  text = "وزارت راه و شهرسازی جمهوری اسلامی ایران"

  [[author.name]]
  lang = "en"
  text = "Ministry of Road and Urban Development"

[[title]]
lang = "en" 
text = "Geographical distribution of Mehr housing divided by category in new cities in 1392" 

[[title]]
lang = "fa"
text = "توزیع جغرافیایی پروژه‌های مسکن مهر به تفکیک نوع در شهرهای جدید در سال ۱۳۹۲"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۴۴ صفحه ۳۲۰ گزارش شناخت، مستندسازی و ارزیابی مسکن مهر از سایت رسمی وزارت راه و شهرسازی گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 44, page 320 of the Report on Recognition, Documentation and Evaluation of Mehr Housing on the official website of the Ministry of Roads and Urban Planning."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/mrudho1746-mehr_housing_divided_by_cities_new_cities-1392-fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/mrudho1746-mehr_housing_divided_by_cities_new_cities-1392-en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Geographical distribution of Mehr housing divided by category in new cities in 1392"

  [[resources.title]]
  lang = "fa"
  text = "توزیع جغرافیایی پروژه‌های مسکن مهر به تفکیک نوع در شهرهای جدید در سال ۱۳۹۲"

  [[resources.sources]]
  name = "Ministry of Road and Urban Development" 
  web = "http://bit.ly/2zX2EQO" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "province name"
      type = "string"

      [[resources.schema.fields]]
      name = "cooperative residential units"
      type = "string"

      [[resources.schema.fields]]
      name = "three sided residential units"
      type = "string"

      [[resources.schema.fields]]
      name = "individual residential units"
      type = "string"


