name = "mrudtn173"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["transport", "energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["oil related imports", "non-oil imports", "total imports", "oil related exports", "non-oil exports", "total exports", "marine imports", "marine exports", "road imports", "road exports"]

[[keywords]]
lang = "fa" 
wordlist = ["واردات نفتی", "واردات غیر نفتی", "جمع واردات", "صادرات نفتی", "صادرات غیر نفتی", "جمع صادرات", "واردات دریایی", "صادرات دریایی", "واردات جاده‌ای", "صادرات جاده‌ای"]

[author]
web = "http://www.rmto.ir/Pages/SalnameAmari.aspx?RootFolder=%2FSalnameAmari%2Fسالنامه%20آماري%20%2D%20سال%201394&FolderCTID=0x012000FF1BA3D9B5EBFB4EB230D974D1674C47&View={92B8D111-2582-4324-B522-B8B4BA815A63}"

  [[author.name]] 
  lang = "fa"
  text = "وزارت راه و شهرسازی"

  [[author.name]]
  lang = "en"
  text = "Ministry of Road and Urban Development"

[[title]]
lang = "en" 
text = "Imports and exports of goods crossing the country's borders by type of transportation in 1394" 

[[title]]
lang = "fa"
text = "میزان واردات و صادرات کالا از مرزهای کشور برحسب نوع عبور در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از سالنامه آماری ۱۳۹۴،‌ فصل چهارم - حمل و نقل بین‌المللی،‌ جدول ۴-۱-۱ از سایت رسمی  وزارت راه و شهرسازی، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the Statistical Yearbook 1394, Chapter four - international transport, Table 4.1.1 from the official website of the Ministry of Roads and Urban Development."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/tn/scitn173fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/tn/scitn173en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Imports and exports of goods crossing the country's borders by type of transportation in 1394"

  [[resources.title]]
  lang = "fa"
  text = "میزان واردات و صادرات کالا از مرزهای کشور برحسب نوع عبور در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Ministry of Road and Urban Development" 
  web = "http://www.rmto.ir/Pages/SalnameAmari.aspx?RootFolder=%2FSalnameAmari%2Fسالنامه%20آماري%20%2D%20سال%201394&FolderCTID=0x012000FF1BA3D9B5EBFB4EB230D974D1674C47&View={92B8D111-2582-4324-B522-B8B4BA815A63}" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "Via sea – amount (ton)"
      type = "string"

      [[resources.schema.fields]]
      name = "Via sea – percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Via roads – amount (ton)"
      type = "string"

      [[resources.schema.fields]]
      name = "Via road – percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – amount (ton)"
      type = "string"


