name = "niopdcco171"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 

category= ["communications"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["CNG stations"]

[[keywords]]
lang = "fa" 
wordlist = ["جایگاه‌های CNG"]

[author]
web = "https://cng.niopdc.ir/fa/adresecng-آدرس-جایگاه-های-cng"

  [[author.name]] 
  lang = "fa"
  text = "شرکت ملی پخش فرآورده‌های نفتی ایران"

  [[author.name]]
  lang = "en"
  text = "National Oil Product Distribution Company"

[[title]]
lang = "en" 
text = "CNG stations list to regional breakdown" 

[[title]]
lang = "fa"
text = "لیست جایگاه‌های CNG به تفکیک منطقه‌ای"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی شرکت ملی پخش فرآورده‌های نفتی ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of National Oil Product Distribution Company."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/co/niopdcco171fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/co/niopdcco171en.csv"

  [[resources.title]]
  lang = "en" 
  text = "CNG stations list to regional breakdown"

  [[resources.title]]
  lang = "fa"
  text = "لیست جایگاه‌های CNG به تفکیک منطقه‌ای"

  [[resources.sources]]
  name = "National Oil Product Distribution Company" 
  web = "https://cng.niopdc.ir/fa/adresecng-آدرس-جایگاه-های-cng" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Area"
      type = "string"

      [[resources.schema.fields]]
      name = "Station name"
      type = "string"

      [[resources.schema.fields]]
      name = "City"
      type = "string"

      [[resources.schema.fields]]
      name = "Address"
      type = "string"


