name = "nocrhsp172"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["health", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Death", "Cause of death"]

[[keywords]]
lang = "fa" 
wordlist = ["مرگ و میر", "علت فوت"]

[author]
web = "https://www.sabteahval.ir/Upload/Modules/Contents/asset99/salnameh94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان ثبت احوال کشور"

  [[author.name]]
  lang = "en"
  text = "National organisation for civil registration"

[[title]]
lang = "en" 
text = "Number of deaths registered in 1394, disaggregated by causes of death and region" 

[[title]]
lang = "fa"
text = "فوت جاری ثبت شده در سال ۱۳۹۴ بر حسب علت فوت و به تفکیک استانی"

[[description]]
lang = "fa"
text = "این مجموعه داده از جدول شماره ۱۱ در صفحه ۲۳۶ و ۲۳۷ از سالنامه آمارهای جمعیتی سازمان ثبت احوال کشور ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 11, pages 236 and 237, of the National Organisation for Civil Registration 1394 Demographic Yearbook"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/hsp/nocrhsp172fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/hsp/nocrhsp172en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Number of deaths registered in 1394, disaggregated by causes of death and region"

  [[resources.title]]
  lang = "fa"
  text = "فوت جاری ثبت شده در سال ۱۳۹۴ بر حسب علت فوت و به تفکیک استانی"

  [[resources.sources]]
  name = "National organisation for civil registration" 
  web = "https://www.sabteahval.ir/Upload/Modules/Contents/asset99/salnameh94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Total death"
      type = "string"

      [[resources.schema.fields]]
      name = "Infections and Parasitic diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Cancer and Tumors"
      type = "string"

      [[resources.schema.fields]]
      name = "Hematopoietic immune system diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Nutritional and metabolic diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Mental illness and behavioral disorders"
      type = "string"

      [[resources.schema.fields]]
      name = "Nervous system diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Cardiovascular diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Respiratory system diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Gastrointestinal diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Diseases of the skin and subcutaneous"
      type = "string"

      [[resources.schema.fields]]
      name = "Musculoskeletal disorders"
      type = "string"

      [[resources.schema.fields]]
      name = "Urogenital tract diseases"
      type = "string"

      [[resources.schema.fields]]
      name = "Complications of pregnancy and childbirth"
      type = "string"

      [[resources.schema.fields]]
      name = "Congenital malformations and chromosomal"
      type = "string"

      [[resources.schema.fields]]
      name = "Diseases during the perinatal"
      type = "string"

      [[resources.schema.fields]]
      name = "Symptoms are vague and ill-defined conditions"
      type = "string"

      [[resources.schema.fields]]
      name = "Unintentional injuries"
      type = "string"

      [[resources.schema.fields]]
      name = "Unknown"
      type = "string"


