name = "nocrcd1693"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
frequency = "yearly"
category= "Health Sector Performance"

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "بنیاد رسانه خرد"

[[keywords]]
lang = "en" 
wordlist = ["death", "Iran", "diseases"]

[[keywords]]
lang = "fa" 
wordlist = ["مرک" , "ایران" , "مریضی"]

[author]
web = "https://www.sabteahval.ir/Upload/Modules/Contents/asset99/salnameh93.pdf"

  [[author.name]] 
  lang = "fa"
  text = "National Organisation for Civil Registration"

  [[author.name]]
  lang = "en"
  text = "National Organisation for Civil Registration"

[[title]]
lang = "en" 
text = "Registered deaths, by cause and province" 

[[title]]
lang = "fa"
text = "فوت‌های ثبت‌شده بر حسب علت فوت به تفکیک استانی "

[[description]]
lang = "fa"
text = "این مجموعه داده از جدول شماره ۱۱ در صفحه ۲۳۴ و ۲۳۵ از سالنامه آمارهای جمعیتی سازمان ثبت احوال کشور ۱۳۹۳ استخراج شده است.   "

[[description]]
lang = "en"
text = "This dataset has been extracted from the annual report of the National Organisation for Civil Registration (1393), Table 11, page 234-235."

[[resources]]

  url = "http://iod.dataset.s3.amazonaws.com/nocrd1693/NOCRCD1693fa.csv"

  [[resources.title]]
  lang = "en" 
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "National Organisation for Civil Registration" 
  web = "https://www.sabteahval.ir/Upload/Modules/Contents/asset99/salnameh93.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Author"
      type = "string"

      [[resources.schema.fields]]
      name = "Publisher"
      type = "string"

      [[resources.schema.fields]]
      name = "Title"
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "date"
