name = "nocrpo1715"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1392] 
category= ["population" , "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Marriage Statistics", "Divorce Statistics"]

[[keywords]]
lang = "fa" 
wordlist = ["آمار ازدواج", "آمار طلاق"]

[author]
web = "https://www.sabteahval.ir/Upload/Modules/Contents/asset99/salname92.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان ثبت احوال کشور"

  [[author.name]]
  lang = "en"
  text = "National organisation for civil registration"

[[title]]
lang = "en" 
text = "Figures of registered marriages and divorces, as per each province, between 1385 and 1392" 

[[title]]
lang = "fa"
text = "آمار ازدواج و طلاق ثبت شده به تفكيک استانی در سال‌های ۱۳۸۵ تا ۱۳۹۲"

[[description]]
lang = "fa"
text = "این داده از جدول ۱۱ در صفحه ۳۴۲،‌ سالنامه آمارهای جمعیتی سازمان ثبت احوال کشور ۱۳۹۲ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 11 on page 342, Demographics calendar of  National organisation for civil registration in year 1392."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/nocrpo1715fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/nocrpo1715en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Statistics marriages and divorces registered in separate provinces during 1385 to 1392."

  [[resources.title]]
  lang = "fa"
  text = "آمار ازدواج و طلاق ثبت شده به تفكيک استانی در سال‌های ۱۳۸۵ تا ۱۳۹۲"

  [[resources.sources]]
  name = "National organisation for civil registration" 
  web = "https://www.sabteahval.ir/Upload/Modules/Contents/asset99/salname92.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Provinces"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Divorce – 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Divorce – 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Divorce – 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Divorce – 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Divorce – 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Divorce – 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Divorce – 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Marriage – 1385"
      type = "string"


