name = "opecnre1722"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [2005 ,  2017] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["crude oil price", "OPEC"]

[[keywords]]
lang = "fa" 
wordlist = ["قیمت نفت خام", "OPEC"]

[author]
web = "https://www.quandl.com/data/OPEC/ORB-OPEC-Crude-Oil-Price"

  [[author.name]] 
  lang = "fa"
  text = "OPEC"

  [[author.name]]
  lang = "en"
  text = "Organization of Petroleum Exporters Countries"

[[title]]
lang = "en" 
text = "OPEC Crude oil price from 2005 to 2017" 

[[title]]
lang = "fa"
text = "قیمت نفت خام اوپک از سال ۲۰۰۵ تا ۲۰۱۷"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی اوپک گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of Organization of Petroleum Exporters Countries (OPEC)."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/opecnre1722fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/opecnre1722en.csv"

  [[resources.title]]
  lang = "en" 
  text = "OPEC Crude oil price from 2005 to 2017"

  [[resources.title]]
  lang = "fa"
  text = "قیمت نفت خام OPEC از سال ۲۰۰۵ تا ۲۰۱۷"

  [[resources.sources]]
  name = "Organization of Petroleum Exporters Countries" 
  web = "https://www.quandl.com/data/OPEC/ORB-OPEC-Crude-Oil-Price" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Date"
      type = "string"


