name = "pdspcbgs1732"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1387, 1387] 
category= ["budget"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Budget for year 1387", "Budget for sectors"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه سال ۱۳۸۷", "بودجه وزارتخانه‌ها"]

[author]
web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1387.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ريزی و نظارت راهبردی"

  [[author.name]]
  lang = "en"
  text = "President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "expenditures of main devices in 1387" 

[[title]]
lang = "fa"
text = "مصارف دستگاه‌های اصلی در سال ۱۳۸۷"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱-۲ در صفحات ۶۸ تا ۱۳۰، قانون بودجه دستگاه‌های اجرایی ۱۳۸۷ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 2-1 from pages 68 to 130, The 1387 executive budget."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1732fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1732en.csv"

  [[resources.title]]
  lang = "en" 
  text = "expenditures of main devices in 1387"

  [[resources.title]]
  lang = "fa"
  text = "مصارف دستگاه‌های اصلی در سال ۱۳۸۷"

  [[resources.sources]]
  name = "President Deputy Strategic Planning and Control" 
  web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1387.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "code"
      type = "string"

      [[resources.schema.fields]]
      name = "title"
      type = "string"

      [[resources.schema.fields]]
      name = "expenses – public"
      type = "string"

      [[resources.schema.fields]]
      name = "expenses – private"
      type = "string"

      [[resources.schema.fields]]
      name = "expenses – total"
      type = "string"

      [[resources.schema.fields]]
      name = "ownership of capital assets"
      type = "string"


