name = "pdspcbgs1717"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1388, 1388] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Public budget", "Welfare and Social Security", "Environment", "Education"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه دولت", "بودجه عمومی", "رفاه و تامین اجتماعی", "محیط زیست", "آموزش و پرورش"]

[author]
web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1388.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ریزی و نظارت راهبردی رییس جمهور"

  [[author.name]]
  lang = "en"
  text = "President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "Acquisition of Capital Assets credits disaggregated by affairs.chapter in 1388" 

[[title]]
lang = "fa"
text = "اعتبارات تملک دارایی‌های سرمایه‌ای بر حسب امور.فصل در سال ۱۳۸۸"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲-۷ در صفحات ۱۵۲ تا ۱۵۸، قانون بودجه سال ۱۳۸۸ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 7-2 on pages 151 to 158, The country's 1388 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1717fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1717en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Capital assets acquisition credits in terms of affairs and chapters in 1388"

  [[resources.title]]
  lang = "fa"
  text = "اعتبارات تملک دارایی‌های سرمایه‌ای بر حسب امور و فصل در سال ۱۳۸۸"

  [[resources.sources]]
  name = "President Deputy Strategic Planning and Control" 
  web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1388.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Affairs / Chapters"
      type = "string"

      [[resources.schema.fields]]
      name = "Acquisition of capital assets - national 
(million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Acquisition of capital assets - Provincial (million IRR)"
      type = "string"


