name = "pdspcbgs1721"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["budget", "education", "environment", "government", "welfare", "social security"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه", "آموزش", "محیط زیست", "دولت", "رفاه", "امنیت اجتماعی"]

[author]
web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1393.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ريزی و نظارت راهبردی رئيس جمهور"

  [[author.name]]
  lang = "en"
  text = "Iranian President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "Revenues, capital and financial assets divisions disaggregated by divisions, sections and components in 1393" 

[[title]]
lang = "fa"
text = "درآمدها، واگذاری دارایی‌های سرمایه‌ای و واگذاری دارایی‌های مالی بر حسب قسمت، بخش، بند، اجزا در سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۵ در صفحات ۶۹ تا ۸۰، قانون بودجه سال ۱۳۹۳ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 5 on pages 69 to 80, the country's 1393 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1721fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1721en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Revenues, capital and financial assets divisions disaggregated by divisions, sections and components in 1393"

  [[resources.title]]
  lang = "fa"
  text = "درآمدها، واگذاری دارایی‌های سرمایه‌ای و واگذاری دارایی‌های مالی بر حسب قسمت، بخش، بند، اجزا در سال ۱۳۹۳"

  [[resources.sources]]
  name = "Iranian President Deputy Strategic Planning and Control" 
  web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1393.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "code"
      type = "string"

      [[resources.schema.fields]]
      name = "title"
      type = "string"

      [[resources.schema.fields]]
      name = "public – national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "public – provincial (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "public – total (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "private – national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "private – provincial (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "private – total (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "total – national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "total – provincial (million IRR)"
      type = "string"


