name = "pdspcbgs1719"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1387, 1387] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["National capital assets acquisition", "Provincial capital assets acquisition", "Public Affairs", "Defense and security affairs", "Cultural and social affairs", "Economic Affairs"]

[[keywords]]
lang = "fa" 
wordlist = ["تملک دارایی‌های سرمایه‌ای ملی", "تملک دارایی‌های سرمایه‌ای استانی", "امور عمومی", "امور دفاعی و امنیتی", "اموراجتماعی وفرهنگی", "اموراقتصادی"]

[author]
web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1387.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ریزی و نظارت راهبردی رییس جمهور"

  [[author.name]]
  lang = "en"
  text = "President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "Capital assets acquisition credits in terms of affairs and chapters in 1387" 

[[title]]
lang = "fa"
text = "اعتبارات تملک دارایی‌های سرمایه‌ای بر حسب امور و فصل در سال ۱۳۸۷"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲-۷ در صفحات ۳۵۱ تا ۳۵۷، قانون بودجه سال ۱۳۸۷ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 7-2 on pages 351 to 357, The country's 1387 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1719fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1719en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Capital assets acquisition credits in terms of affairs and chapters in 1387"

  [[resources.title]]
  lang = "fa"
  text = "اعتبارات تملک دارایی‌های سرمایه‌ای بر حسب امور و فصل در سال ۱۳۸۷"

  [[resources.sources]]
  name = "President Deputy Strategic Planning and Control" 
  web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1387.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Affairs / Chapters"
      type = "string"

      [[resources.schema.fields]]
      name = "Acquisition of capital assets - national 
(million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Acquisition of capital assets - Provincial (million IRR)"
      type = "string"


