name = "pdspcbgs172"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1388, 1388] 
category= ["budget", "economics","energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["1388 Provincial annual budget"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه استان‌ها سال ۱۳۸۸"]

[author]
web = "http://iod.dataset.s3.amazonaws.com/Sources/pdspc65.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ريزی و نظارت راهبردی رئيس جمهور"

  [[author.name]]
  lang = "en"
  text = "Iranian President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "Macro picture of the annual provincial budget in year 1388" 

[[title]]
lang = "fa"
text = "تصوير كلان بودجه استانی در سال ۱۳۸۸"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱۰ در صفحات ۱۷۶ و ۱۷۷، قانون بودجه سال ۱۳۸۸ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 10 on pages 176 to 177, The country's 1388 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs172fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs172en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Macro picture of the annual provincial budget in year 1388"

  [[resources.title]]
  lang = "fa"
  text = "تصوير كلان بودجه استانی در سال ۱۳۸۸"

  [[resources.sources]]
  name = "Iranian President Deputy Strategic Planning and Control" 
  web = "http://iod.dataset.s3.amazonaws.com/Sources/pdspc65.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Income - general revenue - provincial revenue (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income - general revenue - national income - 2% of revenue from exports of crude oil and natural gas (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income – general revenue - national income - other (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income – general revenue - national income - Total (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income – general revenue - Total (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income - dedicated revenue (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget - cost - wages and benefits * (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget - cost - other (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget - cost – total (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget – acquisition of capital assets (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget – total (figures in million rials)"
      type = "string"


