name = "pdspcbgs171"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1395, 1395] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Budget for year 1395", "Budget for sectors"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه سال ۱۳۹۵", "بودجه وزارتخانه‌ها"]

[author]
web = "http://dlp.mporg.ir/LinkClick.aspx?fileticket=AyxnVMM4JZE%3d&tabid=40&mid=562"

  [[author.name]] 
  lang = "fa"
  text = "سازمان مدیریت و برنامه‌ریزی کشور"

  [[author.name]]
  lang = "en"
  text = "Management and Planning Organisation of Iran"

[[title]]
lang = "en" 
text = "The executive budget summary for the year 1395" 

[[title]]
lang = "fa"
text = "خلاصه بودجه دستگاه‌های اصلی در سال ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۷ در صفحات ۴۸ تا ۱۵۲، قانون بودجه سال ۱۳۹۵ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 7 on pages 48 to 152, The country's 1395 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs171fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs171en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The executive budget summary for the year 1395"

  [[resources.title]]
  lang = "fa"
  text = "خلاصه بودجه دستگاه‌های اصلی در سال ۱۳۹۵"

  [[resources.sources]]
  name = "Management and Planning Organisation of Iran" 
  web = "http://dlp.mporg.ir/LinkClick.aspx?fileticket=AyxnVMM4JZE%3d&tabid=40&mid=562" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Title / Device Code "
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs / performance in 1393 (All Figures in Million Rial IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs / approved in 1394 (All Figures in Million Rial IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs /estimates 1395/ entitlement (All Figures in Million Rial IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs /estimates 1395/ others (All Figures in Million Rial IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / costs /estimates 1395/ total (All Figures in Million Rial IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / dedicated 1395 (All Figures in Million Rial IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Acquisition of capital assets (All Figures in Million Rial IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Financial assets acquisition (All Figures in Million Rial IRR)"
      type = "string"


