name = "pdspcbgs1718"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1387, 1387] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Public budget", "Welfare and Social Security", "Environment", "Education"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه دولت", "بودجه عمومی", "رفاه و تامین اجتماعی", "محیط زیست", "آموزش و پرورش"]

[author]
web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1387.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ریزی و نظارت راهبردی رییس جمهور"

  [[author.name]]
  lang = "en"
  text = "President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "Estimates of credit costs disaggregated by affairs.chapter in year 1387" 

[[title]]
lang = "fa"
text = "برآورد اعتبارات هزینه‌ای بر حسب امور.فصل در سال ۱۳۸۷"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱-۷ در صفحات ۳۴۸ تا ۳۵۰، قانون بودجه سال ۱۳۸۷ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 7-1 on pages 348 to 350, The country's 1387 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1718fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1718en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Estimates of costs credits, according to the affairs and chapters in year 1387"

  [[resources.title]]
  lang = "fa"
  text = "برآورد اعتبارات هزینه‌ای بر حسب امور و فصل در سال ۱۳۸۷"

  [[resources.sources]]
  name = "President Deputy Strategic Planning and Control" 
  web = "http://irandataportal.syr.edu/wp-content/uploads/budget-1387.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Classification number"
      type = "string"

      [[resources.schema.fields]]
      name = "Subject"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - of public resources - national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - of public resources - Provincial (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - from private sources - National (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Cost - from private sources – Provincial (million IRR)"
      type = "string"


