name = "pdspcbgs174"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1390, 1390] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Provincial annual budget 1390"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه استان‌ها سال ۱۳۹۰"]

[author]
web = "http://iod.dataset.s3.amazonaws.com/Sources/pdspc67.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ريزی و نظارت راهبردی رئيس جمهور"

  [[author.name]]
  lang = "en"
  text = "Iranian President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "Macro picture of the annual provincial budget in year 1390" 

[[title]]
lang = "fa"
text = "تصوير كلان بودجه استانی سال ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱۰ در صفحات ۱۹۵ و ۱۹۶، قانون بودجه سال ۱۳۹۰ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 10 on pages 195 and 196, the country's 1390 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs174fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs174en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Macro picture of the annual provincial budget in year 1390"

  [[resources.title]]
  lang = "fa"
  text = "تصوير كلان بودجه استانی سال ۱۳۹۰"

  [[resources.sources]]
  name = "Iranian President Deputy Strategic Planning and Control" 
  web = "http://iod.dataset.s3.amazonaws.com/Sources/pdspc67.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province / Province Code"
      type = "string"

      [[resources.schema.fields]]
      name = "Income - general revenue - provincial revenue (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income - general revenue - national income - 2% of revenue from exports of crude oil and natural gas (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income – general revenue - national income - other (figures in million rials) "
      type = "string"

      [[resources.schema.fields]]
      name = "Income – general revenue - national income - Total (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income – general revenue - Total (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Income - dedicated revenue (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget - cost - wages and benefits (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget - cost - other (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget - cost – total (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget – acquisition of capital assets (figures in million rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Payout - public budget – total (figures in million rials)"
      type = "string"


