name = "pdspcbgs166"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Budget for year 1393", "Budget for sectors"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه سال ۱۳۹۳", "بودجه وزارتخانه‌ها"]

[author]
web = "http://iod.dataset.s3.amazonaws.com/Sources/pdspc70.pdf"

  [[author.name]] 
  lang = "fa"
  text = "معاونت برنامه‌ريزی و نظارت راهبردی رئيس جمهور"

  [[author.name]]
  lang = "en"
  text = "Iranian President Deputy Strategic Planning and Control"

[[title]]
lang = "en" 
text = "The executive budget summary for the year 1393" 

[[title]]
lang = "fa"
text = "خلاصه بودجه دستگاه‌های اصلی در سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۷ در صفحات ۸۳ تا ۱۷۴، قانون بودجه سال ۱۳۹۳ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 7 on pages 83 to 174, The country's 1393 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs166fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs166en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The executive budget summary for the year 1393"

  [[resources.title]]
  lang = "fa"
  text = "خلاصه بودجه دستگاه‌های اصلی در سال ۱۳۹۳"

  [[resources.sources]]
  name = "Iranian President Deputy Strategic Planning and Control" 
  web = "http://iod.dataset.s3.amazonaws.com/Sources/pdspc70.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Title / Device Code"
      type = "string"

      [[resources.schema.fields]]
      name = "ٍExpenditure / General costs / wages and benefits"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / General costs / other"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / General expenses / Total"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Price / Exclusive"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Price / Total"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Acquisition of capital assets"
      type = "string"

      [[resources.schema.fields]]
      name = "Expenditure / Financial assets acquisition"
      type = "string"


