name = "pdspcbgs1730"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["budget", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["budget", "education", "environment", "government", "welfare", "social security"]

[[keywords]]
lang = "fa" 
wordlist = ["بودجه", "آموزش", "محیط زیست", "دولت", "رفاه", "امنیت اجتماعی"]

[author]
web = "http://iod.dataset.s3.amazonaws.com/Sources/IOD082.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان مدیریت و برنامه‌ریزی کشور"

  [[author.name]]
  lang = "en"
  text = "Management and Planning Organisation of Iran"

[[title]]
lang = "en" 
text = "Revenues, capital and financial assets divisions disaggregated by divisions, sections and components in 1394" 

[[title]]
lang = "fa"
text = "درآمدها، واگذاری دارایی‌های سرمایه‌ای و واگذاری دارایی‌های مالی بر حسب قسمت، بخش، بند، اجزا در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۵ در صفحات ۵۵ تا ۶۷، قانون بودجه سال ۱۳۹۴ کل کشور، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 5 on pages 55 to 67, the country's 1394 budget law."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1730fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/pdspcbgs1730en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Revenues, capital and financial assets divisions disaggregated by divisions, sections and components in 1394"

  [[resources.title]]
  lang = "fa"
  text = "درآمدها، واگذاری دارایی‌های سرمایه‌ای و واگذاری دارایی‌های مالی بر حسب قسمت، بخش، بند، اجزا در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Management and Planning Organisation of Iran" 
  web = "http://iod.dataset.s3.amazonaws.com/Sources/IOD082.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "code"
      type = "string"

      [[resources.schema.fields]]
      name = "title"
      type = "string"

      [[resources.schema.fields]]
      name = "public – national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "public – provincial (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "public – total (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "private – national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "private – provincial (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "private – total (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "total – national (million IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "total – provincial (million IRR)"
      type = "string"


