name = "scico161"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["communications"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["information technology", "communication", "internet", "population"]

[[keywords]]
lang = "fa" 
wordlist = ["فناوری اطلاعات", "ارتباطات", "اینترنت", "جمعیت"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_tabkhveaafeve_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Population aged 6 and over, disaggregated by use of information and communicato technology and province in 1393" 

[[title]]
lang = "fa"
text = "جمعیت ۶ سال و بیشتر کشور برحسب استفاده از فناوری اطلاعات و ارتباطات به تفکیک استان در سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول ۵ در صفحه ۴۳، کیفیت هوا بر اساس شاخص AQI طی ماه‌های مختلف در سال ۱۳۹۰ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 5 on page 43, AQI Air Quality Index during different months in 1390."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/co/scico161fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/co/scico161en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Population aged 6 and over, disaggregated by use of information and communicato technology and province in 1393"

  [[resources.title]]
  lang = "fa"
  text = "جمعیت ۶ سال و بیشتر کشور برحسب استفاده از فناوری اطلاعات و ارتباطات به تفکیک استان در سال ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_tabkhveaafeve_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Total population"
      type = "string"

      [[resources.schema.fields]]
      name = "Mobile phone users"
      type = "string"

      [[resources.schema.fields]]
      name = "Computer users"
      type = "string"

      [[resources.schema.fields]]
      name = "Internet – internet users"
      type = "string"

      [[resources.schema.fields]]
      name = "Internet – internet penetration"
      type = "string"


