name = "sciehe177"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Employment", "Agriculture", "Industry", "Services"]

[[keywords]]
lang = "fa" 
wordlist = ["اشتغال", "کشاورزی", "صنعت", "خدمات"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The share of employed people aged 10 and over in major sectors of activity as per province divided by urban and rural areas in 1394" 

[[title]]
lang = "fa"
text = "سهم شاغلان ۱۰ ساله و بيشتر در بخش‌های عمده فعاليت برحسب استان به تفكيک نقاط شهری و روستايی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۲۳ در صفحه ۴۷،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 23 on page 47, Results of the 1394 Labour force survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe177fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe177en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The share of employed people aged 10 and over in major sectors of activity as per province divided by urban and rural areas in 1394"

  [[resources.title]]
  lang = "fa"
  text = "سهم شاغلان ۱۰ ساله و بيشتر در بخش‌های عمده فعاليت برحسب استان به تفكيک نقاط شهری و روستايی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Provinces"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture – Total"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture – Urban areas"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture – Rural areas"
      type = "string"

      [[resources.schema.fields]]
      name = "Industrial – Total"
      type = "string"

      [[resources.schema.fields]]
      name = "Industrial  – Urban areas"
      type = "string"

      [[resources.schema.fields]]
      name = "Industrial  – Rural areas"
      type = "string"

      [[resources.schema.fields]]
      name = "Services – Total"
      type = "string"

      [[resources.schema.fields]]
      name = "Services – Urban areas"
      type = "string"


