name = "scied1713"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394 ,  1395] 
category= ["education"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["number of students", "female students", "male students", "teaching personnel"]

[[keywords]]
lang = "fa" 
wordlist = ["تعداد دانش‌آموزان", "دانش‌آموزان دختر", "دانش‌آموزان پسر", "کارکنان آموزشی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_salname_keshvar_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Number of students and teaching personnel of offices and the ministry of education disaggregated by provinces for the academic year of 1394-1395" 

[[title]]
lang = "fa"
text = "دانش‌آموزان و كاركنان آموزشی، دفتری و اداری وزارت آموزش و پرورش برحسب استان، سال تحصيلی ۱۳۹۴-۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از صفحه ۶۵۲ جدول ۶-۱۷، سالنامه آماری کشور - ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the table 17-6 on page 652,Statistical Yearbook of the country - 1394"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1713fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1713en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Number of students and teaching personnel of offices and the ministry of education disaggregated by provinces for the academic year of 1394-1395"

  [[resources.title]]
  lang = "fa"
  text = "دانش‌آموزان و كاركنان آموزشی، دفتری و اداری وزارت آموزش و پرورش برحسب استان، سال تحصيلی ۱۳۹۴-۱۳۹۵"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_salname_keshvar_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Provinces"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of students"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of male students"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of female students"
      type = "string"

      [[resources.schema.fields]]
      name = "Educational personnel – Teachers"
      type = "string"


