name = "sciehe1740"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Economically active population", "Economically active and literate population", "Literate employed population", "Literate and unemployed population"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت فعال از لحاظ اقتصادی", "جمعیت فعال از لحاظ اقتصادی باسواد", "شاغل باسواد", "بیکار باسواد"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Relative distribution of literacy of active population aged 10 years and over disaggregated by activity status, gender, urban and rural areas in 1394" 

[[title]]
lang = "fa"
text = "توزيع نسبی برآورد باسوادی جمعيت فعال ۱۰ ساله و بيش‌تر بر حسب وضع فعاليت، جنس، نقاط شهری و روستايی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحه ۳۷ جدول ۸، نتایج آمارگیری نیروی کار - ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 8 on page 37, Results of the labor force survey in 1394."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1740fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1740en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Relative distribution of literacy of active population aged 10 years and over disaggregated by activity status, gender, urban and rural areas in 1394"

  [[resources.title]]
  lang = "fa"
  text = "توزيع نسبی برآورد باسوادی جمعيت فعال ۱۰ ساله و بيش‌تر بر حسب وضع فعاليت، جنس، نقاط شهری و روستايی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Economically active population"
      type = "string"

      [[resources.schema.fields]]
      name = "Male and Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Male"
      type = "string"

      [[resources.schema.fields]]
      name = "Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas"
      type = "string"


