name = "sciehe1713"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["economically active population", "employment", "unemployment"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت فعال", "بیکاری", "اشتغال"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Population aged 10 and over disaggregated by gender, age and ability to work, in 1394" 

[[title]]
lang = "fa"
text = "جمعیت ۱۰ ساله و بیشتر بر حسب جنس و سن و به تفکیک وضع فعالیت اقتصادی  در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۸ در صفحه ۸۳،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 8 on page 83, Results of the 1394 Labour force survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1713fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1713en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Population aged 10 and over disaggregated by gender, age and ability to work, in 1394"

  [[resources.title]]
  lang = "fa"
  text = "جمعیت ۱۰ ساله و بیشتر بر حسب جنس و سن و به تفکیک وضع فعالیت اقتصادی  در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Gender and age"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – total"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – able to work – total"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – able to work – employed"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – able to work – unemployed "
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – not able to work "
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – total"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – able to work – total"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – able to work – employed"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – able to work – unemployed "
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – not able to work "
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – total"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – able to work – total"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – able to work – employed"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – able to work – unemployed "
      type = "string"


