name = "sciehe167fa"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["employment", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = []

[[keywords]]
lang = "fa" 
wordlist = []

[author]
web = "https://drive.google.com/open?id=0B4viFwPm8_QKTTV2Ti1NaXhObFE"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = ""

[[title]]
lang = "en" 
text = "" 

[[title]]
lang = "fa"
text = "جمعیت ۱۰ ساله و بیشتر بر حسب جنس و وضع فعالیت اقتصادی به تفکیک وضع سواد، آخرین مدرک با دوره تحصیلی باسودان (سال ۱۳۹۳)"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱۰ در صفحه ۸۹ نتایج آمارگیری نیروی کار ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = ""

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "" 

  [[resources.url]]
  lang = "en"
  link = ""

  [[resources.title]]
  lang = "en" 
  text = ""

  [[resources.title]]
  lang = "fa"
  text = "جمعیت ۱۰ ساله و بیشتر بر حسب جنس و وضع فعالیت اقتصادی به تفکیک وضع سواد، آخرین مدرک با دوره تحصیلی باسودان (سال ۱۳۹۳)"

  [[resources.sources]]
  name = "" 
  web = "https://drive.google.com/open?id=0B4viFwPm8_QKTTV2Ti1NaXhObFE" 

  [resources.schema]
  format = "csv"


