name = "sciehe1741"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["women", "men", "urban", "rural", "economic activity", "employment"]

[[keywords]]
lang = "fa" 
wordlist = ["زنان", "مردان", "شهری", "روستایی", "فعالیت اقتصادی", "اشتغال"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Employed population of age 10 and above according to gender and age breakdown of the major groups of economic activity in 1394" 

[[title]]
lang = "fa"
text = "شاغلان ۱۰ ساله و بیش‌تر بر حسب جنس و سن به تفکیک گروه‌های عمده فعالیت اقتصادی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحات ۱۰۱ تا ۱۱۲ جدول ۱۲، نتایج آمارگیری نیروی کار - ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 12 on pages 101 to 112, Results of the labor force survey in 1394."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1741fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1741en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Employed population of age 10 and above according to gender and age breakdown of the major groups of economic activity in 1394"

  [[resources.title]]
  lang = "fa"
  text = "شاغلان ۱۰ ساله و بیش‌تر بر حسب جنس و سن به تفکیک گروه‌های عمده فعالیت اقتصادی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Area"
      type = "string"

      [[resources.schema.fields]]
      name = "Gender"
      type = "string"

      [[resources.schema.fields]]
      name = "Age"
      type = "string"

      [[resources.schema.fields]]
      name = "Total (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture, forestry and fishing (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Mining (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Industrial production (manufacturing) -  (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Electricity, gas, steam and air conditioning (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Water supply, waste management, sewage and filtration activities (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Building (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Wholesale, retail, repair of motor vehicles, motorcycles (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Transport and inventory (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Services activities related to providing accommodation and food (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Information and communication (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Financial and insurance activities (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Real estate activities (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Professional, scientific and technical activities (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Administrative and support service activities (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Public administration and defence, compulsory social security (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Education (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Health and social work activities (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Arts, entertainment and recreation (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Other services activities (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Activities of households as employers, separable activities of produce goods and services consumed by normal households for their consumption (person)"
      type = "string"

      [[resources.schema.fields]]
      name = "Organizational activities and abroad bodies (person)"
      type = "string"


