name = "sciehe1715"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["economically active population", "educated population", "university students", "graduates", "employment", "unemployment"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت فعال", "بیکاری", "جمعیت باسواد", "فارغ‌التحصیلان", "دانشگاهی", "اشتغال"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Graduated population or students amongst the population disaggregated by economic activity, in 1394" 

[[title]]
lang = "fa"
text = "جمعیت فارغ‌التحصیل یا در حال تحصیل به تفکیک وضع فعالیت اقتصادی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۱۱ در صفحه ۹۵،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 11 on page 95, Results of the 1394 Labour force survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1715fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1715en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Graduated population or students amongst the population disaggregated by economic activity, in 1394"

  [[resources.title]]
  lang = "fa"
  text = "جمعیت فارغ‌التحصیل یا در حال تحصیل به تفکیک وضع فعالیت اقتصادی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Sex and main fields of study"
      type = "string"

      [[resources.schema.fields]]
      name = "Total able and unable to work population – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – total – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – employed – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – unemployed – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Unable to work – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Total able and unable to work population – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – total – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – employed – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – unemployed – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Unable to work – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Total able and unable to work population – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – total – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – employed – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Able to work – unemployed – rural area"
      type = "string"


