name = "sciehe169"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["employment", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["employment", "private sector", "public sector", "سثط"]

[[keywords]]
lang = "fa" 
wordlist = ["اشتغال", "بخش خصوصی", "بخش عمومی", "جنس"]

[author]
web = "https://drive.google.com/open?id=0B4viFwPm8_QKTTV2Ti1NaXhObFE"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Distribution of workers aged 10 and over, disaggregated by employment status and sex (1393)" 

[[title]]
lang = "fa"
text = "توزيع نسبي براورد شاغلان ۱۰ ساله و بيشتر برحسب وضع شغلي به تفكيك جنس (سال ۱۳۹۳)"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱۷ در صفحه ۴۲ نتایج آمارگیری نیروی کار ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "This dataset was extracted from table 17, page 42, of the Labor Force Survey, 1393."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe169fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe169en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Distribution of workers aged 10 and over, disaggregated by employment status and sex (1393)"

  [[resources.title]]
  lang = "fa"
  text = "توزيع نسبي براورد شاغلان ۱۰ ساله و بيشتر برحسب وضع شغلي به تفكيك جنس (سال ۱۳۹۳)"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://drive.google.com/open?id=0B4viFwPm8_QKTTV2Ti1NaXhObFE" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Employment status"
      type = "string"

      [[resources.schema.fields]]
      name = "Men and women"
      type = "string"

      [[resources.schema.fields]]
      name = "Men"
      type = "string"


