name = "sciehe1618"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1391, 1391] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["unemployment", "employment", "labour market", "urban area", "rural area"]

[[keywords]]
lang = "fa" 
wordlist = ["بیکاری", "اشتغال", "بازار کار", "شهری", "روستایی"]

[author]
web = "http://lib.sci.org.ir/DIGLIB/getfile.aspx?fileid=8412"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Relative distribution of workers aged 10 and over, disaggregated by gender, rural and urban area in year 1391" 

[[title]]
lang = "fa"
text = "توزیع نسبی برآورد جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکیک جنس، نقاط شهری و روستایی در سال ۱۳۹۱"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۷ در صفحه ۳۳ نتایج آمارگیری نیروی کار ۱۳۹۱ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 7, page 33, of the 1391 Labour Force Survey"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1618fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1618en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Relative distribution of workers aged 10 and over, disaggregated by gender, rural and urban area in year 1391"

  [[resources.title]]
  lang = "fa"
  text = "توزیع نسبی برآورد جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکیک جنس، نقاط شهری و روستایی در سال ۱۳۹۱"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://lib.sci.org.ir/DIGLIB/getfile.aspx?fileid=8412" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Activity Status"
      type = "string"

      [[resources.schema.fields]]
      name = "Male & Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Male"
      type = "string"

      [[resources.schema.fields]]
      name = "Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban Areas"
      type = "string"


