name = "scied174"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1393] 
category= ["education"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Faculty members", "Students"]

[[keywords]]
lang = "fa" 
wordlist = ["اعضای هيئت علمی", "دانشجویان"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6121/heiat_elmi.xlsx"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The number of full-time faculty members to all students during the years 1384 to 1393" 

[[title]]
lang = "fa"
text = "نسبت تعداد اعضای هيئت علمی تمام وقت به كل دانشجويان طی سال‌های ۱۳۸۴ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied174fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied174en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The number of full-time faculty members to all students during the years 1384 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "نسبت تعداد اعضای هيئت علمی تمام وقت به كل دانشجويان طی سال‌های ۱۳۸۴ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6121/heiat_elmi.xlsx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Academic year"
      type = "string"

      [[resources.schema.fields]]
      name = "1384-85"
      type = "string"

      [[resources.schema.fields]]
      name = "1385-86"
      type = "string"

      [[resources.schema.fields]]
      name = "1386-87"
      type = "string"

      [[resources.schema.fields]]
      name = "1387-88"
      type = "string"

      [[resources.schema.fields]]
      name = "1388-89"
      type = "string"

      [[resources.schema.fields]]
      name = "1389-90"
      type = "string"

      [[resources.schema.fields]]
      name = "1390-91"
      type = "string"

      [[resources.schema.fields]]
      name = "1391-92"
      type = "string"


