name = "scies165"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["agriculture", "environment"]

[[keywords]]
lang = "fa" 
wordlist = ["کشاورزی", "محیط زیست"]

[author]
web = "http://www.amar.org.ir/Portals/0/keshavarzi93/results/agri93-99.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمارایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Quantity and area of exploitation of agricultural lands, disaggregated by irrigated agriculture, rainfed agriculture and province (1393)" 

[[title]]
lang = "fa"
text = "تعداد و مساحت اراضی زراعی بهره‌برداری‌ها به تفكيک آبی و ديم بر حسب استان (سال ۱۳۹۳)"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱۸ در صفحه ۵۵ نتايج تفصيلی سرشماری عمومی كشاورزی كل كشور ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 18, page 55, of the Detailed Results of the 1393 General Census of Agriculture."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/scies165fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/scies165en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Quantity and area of exploitation of agricultural lands, disaggregated by irrigated agriculture, rainfed agriculture and province (1393)"

  [[resources.title]]
  lang = "fa"
  text = "تعداد و مساحت اراضی زراعی بهره‌برداری‌ها به تفكيك آبی و ديم بر حسب استان (سال ۱۳۹۳)"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/keshavarzi93/results/agri93-99.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Rainfed agriculture – number of lands"
      type = "string"

      [[resources.schema.fields]]
      name = "Rainfed agriculture – area of the lands"
      type = "string"

      [[resources.schema.fields]]
      name = "Irrigated agriculture combined with rainfed agriculture – total number of lands"
      type = "string"

      [[resources.schema.fields]]
      name = "Irrigated agriculture combined with rainfed agriculture – total area of the lands"
      type = "string"

      [[resources.schema.fields]]
      name = "Irrigated agriculture combined with rainfed agriculture – total area of irrigated lands"
      type = "string"


