name = "scied1717"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393 ,  1394] 
category= ["education"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["graduates", "mathematical physics", "science", "humanities", "technical and vocational", "skill and knowledge"]

[[keywords]]
lang = "fa" 
wordlist = ["فارغ‌التحصیلان", "ریاضی فیزیک", "علوم تجربی", "علوم انسانی", "فنی و حرفه‌ای", "کار و دانش"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_salname_keshvar_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "High school graduates (diploma) in the second period disaggregated by academic courses from 1393 to 1394" 

[[title]]
lang = "fa"
text = "فارغ التحصیلان متوسطه (دیپلم) دوره دوم بر حسب شاخه تحصیلی به تفکیک استان - سال تحصیلی ۱۳۹۳ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحات ۶۶۷ و ۶۶۸ جدول ۱۸-۱۷، سالنامه آماری کشور - ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the table 17-18 on pages 667 & 668, Statistical Yearbook of the country - 1394"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1717fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1717en.csv"

  [[resources.title]]
  lang = "en" 
  text = "High school graduates (diploma) in the second period disaggregated by academic courses from 1393 to 1394"

  [[resources.title]]
  lang = "fa"
  text = "فارغ التحصیلان متوسطه (دیپلم) دوره دوم بر حسب شاخه تحصیلی به تفکیک استان - سال تحصیلی ۱۳۹۳ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_salname_keshvar_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province and academic year"
      type = "string"

      [[resources.schema.fields]]
      name = "All – Total"
      type = "string"

      [[resources.schema.fields]]
      name = "All – male"
      type = "string"

      [[resources.schema.fields]]
      name = "All – female"
      type = "string"

      [[resources.schema.fields]]
      name = "High school - Mathematical Physics – male"
      type = "string"

      [[resources.schema.fields]]
      name = "High school - Mathematical Physics – female"
      type = "string"

      [[resources.schema.fields]]
      name = "High school – Science – male"
      type = "string"

      [[resources.schema.fields]]
      name = "High school – Science – female"
      type = "string"

      [[resources.schema.fields]]
      name = "High school – Humanities – male"
      type = "string"

      [[resources.schema.fields]]
      name = "High school – Humanities – female"
      type = "string"

      [[resources.schema.fields]]
      name = "Technical and vocational – male"
      type = "string"

      [[resources.schema.fields]]
      name = "Technical and vocational – female"
      type = "string"

      [[resources.schema.fields]]
      name = "Skill and knowledge – male"
      type = "string"


