name = "sciehe166fa"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category = ["employment", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["employment","unemployment","women employment","Iran"]

[[keywords]]
lang = "fa" 
wordlist = ["بیکاری","اشتغال","اشتغال زنان"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/abstract/1393/ch_ntank_93.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = " نرخ بیکاری جمعیت ۱۰ساله و بیشتر برحسب استان به تفکیک جنس (سال ۱۳۹۳)" 

[[title]]
lang = "fa"
text = " نرخ بیکاری جمعیت ۱۰ساله و بیشتر برحسب استان به تفکیک جنس (سال ۱۳۹۳)"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۵ در صفحه ۴۹ نتایج آمارگیری نیروی کار ۱۳۹۳ استخراج شده است. "

[[description]]
lang = "en"
text = ""

[[resources]]

  url = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe166fa.csv"

  [[resources.title]]
  lang = "en" 
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/abstract/1393/ch_ntank_93.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Field_name"
      type = "string"
