name = "sciehe165"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["employment", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["economic participation", "unemployment", "employment", "population", "women's occupation"]

[[keywords]]
lang = "fa" 
wordlist = ["مشارکت اقتصادی", "بیکاری", "اشتغال", "جمعیت", "اشتغال زنان"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ank_93.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "" 

[[title]]
lang = "fa"
text = "برآورد نرخ مشارکت اقتصادی جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکیک جنس، نقاط شهری و روستایی
  (سال ۱۳۹۳)"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱۰ در صفحه ۳۸ نتایج آمارگیری نیروی کار ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = ""

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "" 

  [[resources.url]]
  lang = "en"
  link = ""

  [[resources.title]]
  lang = "en" 
  text = ""

  [[resources.title]]
  lang = "fa"
  text = "برآورد نرخ مشارکت اقتصادی جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکیک جنس، نقاط شهری و روستایی
  (سال ۱۳۹۳)"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ank_93.pdf" 

  [resources.schema]
  format = "csv"


