name = "sciehe1743"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1386, 1386] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["labor force", "unemployment", "work"]

[[keywords]]
lang = "fa" 
wordlist = ["نیروی کار", "بیکاری", "کار"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/abstract/niruye%20kar/ABS/Abs-nirooye%20kar-84-87-web.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Labor force indicators divided by gender, urban and rural areas in 1386" 

[[title]]
lang = "fa"
text = "شاخص‌های نيروی كار به تفكيک جنس، نقاط شهری و روستايی در سال ۱۳۸۶"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of Statistical Centre of Iran"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1743fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1743en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Labor force indicators divided by gender, urban and rural areas in 1386"

  [[resources.title]]
  lang = "fa"
  text = "شاخص‌های نيروی كار به تفكيک جنس، نقاط شهری و روستايی در سال ۱۳۸۶"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/abstract/niruye%20kar/ABS/Abs-nirooye%20kar-84-87-web.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "labor force indicator"
      type = "string"

      [[resources.schema.fields]]
      name = "whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "male"
      type = "string"

      [[resources.schema.fields]]
      name = "female"
      type = "string"

      [[resources.schema.fields]]
      name = "urban areas"
      type = "string"


