name = "scied161"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1367, 1394] 
category= ["education", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["education", "field of study", "gender"]

[[keywords]]
lang = "fa" 
wordlist = ["آموزش", "رشته‌ی تحصيلی", "جنس"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6363/daneshjo93-94..xlsx"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمارایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "University and high education centres students, students of Azad University, disaggregated by field of study, age and gender (1367-1393)" 

[[title]]
lang = "fa"
text = "دانشجويان دانشگاه‌ها و مراكز آموزش عالی و دانشگاه آزاد اسلامی برحسب گروه‌های عمده‌ی رشته‌ی تحصيلی و جنس (۱۳۶۷-۱۳۹۳)"

[[description]]
lang = "fa"
text = "این داده، نسخه‌ی تمیز شده‌ی فایل منتشر شده‌ی مرکز آمار ایران است."

[[description]]
lang = "en"
text = "Dataset cleaned from an Excel file published by the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied161fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied161en.csv"

  [[resources.title]]
  lang = "en" 
  text = "University and high education centres students, students of Azad University, disaggregated by field of study, age and gender (1367-1393)"

  [[resources.title]]
  lang = "fa"
  text = "دانشجويان دانشگاه‌ها و مراكز آموزش عالی و دانشگاه آزاد اسلامی برحسب گروه‌های عمده‌ی رشته‌ی تحصيلی و جنس (۱۳۶۷-۱۳۹۳)"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6363/daneshjo93-94..xlsx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Academic year"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – men "
      type = "string"

      [[resources.schema.fields]]
      name = "Total – women "
      type = "string"

      [[resources.schema.fields]]
      name = "Medicine – men "
      type = "string"

      [[resources.schema.fields]]
      name = "Medicine – women"
      type = "string"

      [[resources.schema.fields]]
      name = "Humanities – men "
      type = "string"

      [[resources.schema.fields]]
      name = "Humanities – women "
      type = "string"

      [[resources.schema.fields]]
      name = "Science – men "
      type = "string"

      [[resources.schema.fields]]
      name = "Science – women "
      type = "string"

      [[resources.schema.fields]]
      name = "Engineering – men "
      type = "string"

      [[resources.schema.fields]]
      name = "Engineering – women "
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture and Veterinary Medicine – men"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture and Veterinary Medicine – women"
      type = "string"

      [[resources.schema.fields]]
      name = "Arts – men "
      type = "string"


