name = "scied175"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1347, 1394] 
category= ["education", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["number of students", "preschool", "secondary school"]

[[keywords]]
lang = "fa" 
wordlist = ["تعداد دانش‌آموزان", "مقطع آمادگی", "مقطع متوسطه"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6274/daneshamoz.xlsx"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The total number of students of preschool and secondary school" 

[[title]]
lang = "fa"
text = "تعداد کل دانش‌آموزان از مقطع آمادگی تا متوسطه طی سال‌های ۱۳۴۷ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied175fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied175en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The total number of students of preschool and secondary school"

  [[resources.title]]
  lang = "fa"
  text = "تعداد کل دانش‌آموزان از مقطع آمادگی تا متوسطه طی سال‌های ۱۳۴۷ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6274/daneshamoz.xlsx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Preschool and high school students during 1386-1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Preschool and high school students during 1387-1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Preschool and high school students during 1388-1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Preschool and high school students during 1389-1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Preschool and high school students during 1390-1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Preschool and high school students during 1391-1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Preschool and high school students during 1392-1393"
      type = "string"


