name = "scied1711"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1375, 1389] 
category= ["education", "employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["researchers", "type of employment"]

[[keywords]]
lang = "fa" 
wordlist = ["محققان", "نوع اشتغال"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/2979/mohaghegh.xlsx"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Number of researchers disaggregated by type of employment from 1375 to 1389" 

[[title]]
lang = "fa"
text = "تعداد محققان به تفکیک نوع اشتغال طی سال‌های ۱۳۷۵ تا ۱۳۸۹"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1711fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1711en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Number of researchers disaggregated by type of employment from 1375 to 1389"

  [[resources.title]]
  lang = "fa"
  text = "تعداد محققان به تفکیک نوع اشتغال طی سال‌های ۱۳۷۵ تا ۱۳۸۹"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/2979/mohaghegh.xlsx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "1375"
      type = "string"

      [[resources.schema.fields]]
      name = "1377"
      type = "string"

      [[resources.schema.fields]]
      name = "1379"
      type = "string"

      [[resources.schema.fields]]
      name = "1381"
      type = "string"

      [[resources.schema.fields]]
      name = "1383"
      type = "string"

      [[resources.schema.fields]]
      name = "1385"
      type = "string"

      [[resources.schema.fields]]
      name = "1387"
      type = "string"

      [[resources.schema.fields]]
      name = "1388"
      type = "string"


