name = "sciehe165"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["employment", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["economic participation", "unemployment", "employment", "population", "women's occupation"]

[[keywords]]
lang = "fa" 
wordlist = ["مشارکت اقتصادی", "بیکاری", "اشتغال", "جمعیت", "اشتغال زنان"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ank_93.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Relative distribution of employed population of 15-64 years in terms of age groups disaggregated by gender, urban and rural areas in 1393" 

[[title]]
lang = "fa"
text = " توزيع نسبی برآورد جمعيت شاغل ۶۴-۱۵ ساله برحسب گروه‌های سنی به تفكيک جنس، نقاط شهری و روستايی  در سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱۰ در صفحه ۳۸ نتایج آمارگیری نیروی کار ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 10, page 38, of the 1393 Labour Force Survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe165fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe165en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Relative distribution of employed population of 15-64 years in terms of age groups disaggregated by gender, urban and rural areas in 1393"

  [[resources.title]]
  lang = "fa"
  text = "توزيع نسبی برآورد جمعيت شاغل ۶۴-۱۵ ساله برحسب گروه‌های سنی به تفكيک جنس، نقاط شهری و روستايی  در سال ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ank_93.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Age groups"
      type = "string"

      [[resources.schema.fields]]
      name = "Men and Women "
      type = "string"

      [[resources.schema.fields]]
      name = "Men "
      type = "string"

      [[resources.schema.fields]]
      name = "Women"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area"
      type = "string"


