name = "sciehe1738"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1395] 
category= ["employment", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Economic participation rate", "Active population", "The unemployment rate", "Youth unemployment rate", "Jobs created"]

[[keywords]]
lang = "fa" 
wordlist = ["نرخ مشارکت اقتصادی", "جمعیت فعال", "نرخ بیکاری", "نرخ بیکاری جوانان", "شغل ایجاد شده"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/abstract/1395/ch_ntank_sal95.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The major indexes of labor based on gender, urban and rural areas during 1384 to 1395" 

[[title]]
lang = "fa"
text = "شاخص‌های عمده نیروی کار بر حسب جنس، نقاط شهری و روستایی در طی سال‌های ۱۳۸۴ تا ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۱ در صفحه ۴، چکیده نتایج طرح آمارگیری نیروی کار سال ۱۳۹۵، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 1 on page 4, Summary results of the labor force survey plan year 1395."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1738fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1738en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The major indexes of labor based on gender, urban and rural areas during 1384 to 1395"

  [[resources.title]]
  lang = "fa"
  text = "شاخص‌های عمده نیروی کار بر حسب جنس، نقاط شهری و روستایی در طی سال‌های ۱۳۸۴ تا ۱۳۹۵"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/abstract/1395/ch_ntank_sal95.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Indicators of labor"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas- 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - 1384"
      type = "string"

      [[resources.schema.fields]]
      name = "Male- 1384"
      type = "string"

      [[resources.schema.fields]]
      name = "Female- 1384"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas- 1384"
      type = "string"


