name = "sciehe1716"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["economically active population", "higher education", "employment", "unemployment"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت فعال", "بیکاری", "تحصیلات عالی", "اشتغال"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Highly educated employees aged 10 and over in 1394" 

[[title]]
lang = "fa"
text = "شاغلان ۱۰ ساله و بیشتر دارای تحصیلات عالی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۲۱ در صفحه ۲۰۹،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 21 on page 209, Results of the 1394 Labour force survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1716fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1716en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Highly educated employees aged 10 and over in 1394"

  [[resources.title]]
  lang = "fa"
  text = "شاغلان ۱۰ ساله و بیشتر دارای تحصیلات عالی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Gender and main fields of study"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – total "
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Legislators, senior officials and managers"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Specialists"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Technicians and assistants"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Office workers"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Service workers, shop and market vendors"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Skilled workers in agricultural, forestry and fishing"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Artisans"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Operators for machines and devices, manufacturing workers"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Simple labourers"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – other"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – total "
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Legislators, senior officials and managers"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Specialists"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Technicians and assistants"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Office workers"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Service workers, shop and market vendors"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Skilled workers in agricultural, forestry and fishing"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Artisans"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Operators for machines and devices, manufacturing workers"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Simple labourers"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – other"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – total "
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Legislators, senior officials and managers"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Specialists"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Technicians and assistants"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Office workers"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Service workers, shop and market vendors"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Skilled workers in agricultural, forestry and fishing"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Artisans"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Operators for machines and devices, manufacturing workers"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – Simple labourers"
      type = "string"


