name = "sciehe162"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["employment", "unemployment", "employees"]

[[keywords]]
lang = "fa" 
wordlist = ["بیکاری", "بیکار", "اشتغال", "شاغل"]

[author]
web = "http://rc.majlis.ir/fa/report/show/985478"

  [[author.name]] 
  lang = "fa"
  text = "مرکز پژوهش‌های مجلس"

  [[author.name]]
  lang = "en"
  text = "Islamic Parliament Research Centre"

[[title]]
lang = "en" 
text = "Total number of unemployed in Iran" 

[[title]]
lang = "fa"
text = "تعداد بیکاران کل کشور"

[[description]]
lang = "fa"
text = "این داده از جدول ۵ صفحه ۱۰ ازبا نمايندگان در مجلس دهم
32بيكاری، اشتغال و بازار کار تهیه شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 5, page 10 of the With the MPs of the Tenth Parliament 32. Occupation and Labour Market"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe162fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe162en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Total number of unemployed in Iran"

  [[resources.title]]
  lang = "fa"
  text = "تعداد بیکاران کل کشور"

  [[resources.sources]]
  name = "Islamic Parliament Research Centre" 
  web = "http://rc.majlis.ir/fa/report/show/985478" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"


