name = "sciehe164"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["employment", "women", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Population", "Population in urban areas", "Population in rural areas"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت", "جمعیت شهری", "جمعیت روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ank_93.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Distribution of population aged 10 and over, disaggregated by ability to work, sex, urban and rural area in 1393" 

[[title]]
lang = "fa"
text = "توزیع نسبی برآورد جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکیک جنس، نقاط شهری و روستایی در سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۷ در صفحه ۳۶ نتایج آمارگیری نیروی کار ۱۳۹۳ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 7, page 36, of the 1393 Labour Force Survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe164fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe164en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Distribution of population aged 10 and over, disaggregated by ability to work, sex, urban and rural area (1393)"

  [[resources.title]]
  lang = "fa"
  text = "توزیع نسبی برآورد جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکیک جنس، نقاط شهری و روستایی (سال ۱۳۹۳)"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ank_93.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Occupation status"
      type = "string"

      [[resources.schema.fields]]
      name = "Men and women"
      type = "string"

      [[resources.schema.fields]]
      name = "Men"
      type = "string"

      [[resources.schema.fields]]
      name = "Women"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area"
      type = "string"


