name = "scied1714"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394 ,  1395] 
category= ["education"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["number of students", "female students", "male students", "institution", "class"]

[[keywords]]
lang = "fa" 
wordlist = ["تعداد دانش‌آموزان", "دانش‌آموزان دختر", "دانش‌آموزان پسر", "آموزشگاه", "کلاس"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_salname_keshvar_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Number of students and educational facilities for preschool level disaggregated by provinces - School year 1394-1395" 

[[title]]
lang = "fa"
text = "دانش آموزان و امکانات آموزشی دوره پیش‌دبستانی به تفکیک استان - سال تحصیلی ۱۳۹۴ تا ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از صفحه ۶۵۶ جدول ۹-۱۷، سالنامه آماری کشور - ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the table 17-9 on page 656,Statistical Yearbook of the country - 1394"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1714fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied1714en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Number of students and educational facilities for preschool level disaggregated by provinces - School year 1394-1395"

  [[resources.title]]
  lang = "fa"
  text = "دانش آموزان و امکانات آموزشی دوره پیش‌دبستانی به تفکیک استان - سال تحصیلی ۱۳۹۴ تا ۱۳۹۵"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_salname_keshvar_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of students"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of male students"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of female students"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of educational institutions"
      type = "string"


