name = "sciehe166"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
frequency = "yearly"
category= []

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = [""]

[[keywords]]
lang = "fa" 
wordlist = []

[author]
web = "https://drive.google.com/open?id=0B4viFwPm8_QKTTV2Ti1NaXhObFE"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "<AUTHOR_EN>"

[[title]]
lang = "en" 
text = "<TITLE_EN>" 

[[title]]
lang = "fa"
text = ""

[[description]]
lang = "fa"
text = ""

[[description]]
lang = "en"
text = ""

[[resources]]

  url = ""

  [[resources.title]]
  lang = "en" 
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "<SOURCE_NAME>" 
  web = "https://drive.google.com/open?id=0B4viFwPm8_QKTTV2Ti1NaXhObFE" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Field_name"
      type = "string"
