name = "sciehe1732"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Unemployment rate", "Economic participation rate", "Agriculture", "Industry", "Services", "Women", "Urban and Rural"]

[[keywords]]
lang = "fa" 
wordlist = ["نرخ بیکاری", "نرخ مشارکت اقتصادی", "کشاورزی", "صنعت", "خدمات", "زنان", "شهری و روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The major indices of work force in the population aged 10 and over as per gender and province in urban and rural areas and nationally in 1394" 

[[title]]
lang = "fa"
text = "شاخص‌های عمده‌ نيروی كار در جمعيت ۱۰ ساله و بيشتر به تفكيک جنس و استان در نقاط شهری و روستایی و کل کشور در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۴۶ در صفحات ۳۶۱ تا ۳۷۸،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 46 on pages 361 to 378, Results of the 1394 Labout forcet survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1732fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1732en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The major indices of work force in the population aged 10 and over as per gender and province in urban and rural areas and nationally in 1394"

  [[resources.title]]
  lang = "fa"
  text = "شاخص‌های عمده‌ نيروی كار در جمعيت ۱۰ ساله و بيشتر به تفكيک جنس و استان در نقاط شهری و روستایی و کل کشور در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Gender and province (figures in percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "Economic participation rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Employment rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Population rate of underemployment (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The unemployment rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Employment ratio (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Proportion of the population with underemployment (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of workers with normal working hours to 49 hours and more (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The underemployment rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in agriculture (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in industry (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the service sector (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the private sector (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the public sector (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Economic participation rate (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Employment rate (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Population rate of underemployment (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The unemployment rate (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Employment ratio (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Proportion of the population with underemployment (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of workers with normal working hours to 49 hours and more (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The underemployment rate (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in agriculture (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in industry (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the service sector (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the private sector (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the public sector (Urban areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Economic participation rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Employment rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Population rate of underemployment (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The unemployment rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Employment ratio (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "Proportion of the population with underemployment (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of workers with normal working hours to 49 hours and more (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The underemployment rate (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in agriculture (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in industry (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the service sector (Rural areas)"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of employment in the private sector (Rural areas)"
      type = "string"


