name = "scies173"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385 ,  1395] 
category= ["economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["GDP", "GDP at constant prices", "economic growth"]

[[keywords]]
lang = "fa" 
wordlist = ["gdp", "تولید ناخالص داخلی", "تولید ناخالص داخلی به قیمت ثابت", "رشد اقتصادی", "رشد اقتصادی بخش‌ها"]

[author]
web = "https://www.amar.org.ir/%D8%A2%D9%85%D8%A7%D8%B1%D9%87%D8%A7%DB%8C-%D9%85%D9%88%D8%B6%D9%88%D8%B9%DB%8C/%D8%AD%D8%B3%D8%A7%D8%A8-%D9%87%D8%A7%DB%8C-%D9%85%D9%84%DB%8C#3505598-----"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "GDP growth and value-added economic activities of the country in constant price series between 1385 to 1395" 

[[title]]
lang = "fa"
text = "رشد محصول ناخالص داخلی و ارزش افزوده رشته فعاليت‌های اقتصادی كشور به قيمت‌های ثابت ازسال ۱۳۸۵ تا ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، تب جدول‌ها و سری‌های زمانی- گروه حساب‌های ملی فصلی- فایل ۱۳۸۵ تا نیمه ۱۳۹۵ - جدول شماره ۴ فایل اکسل گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, table 4 of the excel flle from tables and time series tab."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/es/scies173fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/es/scies173en.csv"

  [[resources.title]]
  lang = "en" 
  text = "GDP growth and value-added economic activities of the country in constant price series between 1385 to 1395"

  [[resources.title]]
  lang = "fa"
  text = "رشد محصول ناخالص داخلی و ارزش افزوده رشته فعاليت‌های اقتصادی كشور به قيمت‌های ثابت ازسال ۱۳۸۵ تا ۱۳۹۵"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/%D8%A2%D9%85%D8%A7%D8%B1%D9%87%D8%A7%DB%8C-%D9%85%D9%88%D8%B6%D9%88%D8%B9%DB%8C/%D8%AD%D8%B3%D8%A7%D8%A8-%D9%87%D8%A7%DB%8C-%D9%85%D9%84%DB%8C#3505598-----" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year / Category"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture group – Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture – Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Fishing – Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Industrial group – Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Mining – Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Oil and natural gas extraction – Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Other mines - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Industry - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Providing water, electricity and natural gas - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Building - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Services group – Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Wholesale and retail, hotels and restaurants - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Transportation, warehousing and communications - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Financial intermediation - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Real estate, rental and business services - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Public affairs, education, health and social workers - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Social services, personal and household - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Total value added of activity - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "Net taxes on imports - Percentage"
      type = "string"

      [[resources.schema.fields]]
      name = "GDP (at market prices) - Percentage"
      type = "string"


