name = "sciehe1714"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["economically active population", "educated population", "employment", "unemployment"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت فعال", "جمعیت باسواد", "بیکاری", "اشتغال"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Population aged 10 and over disaggregated by gender, economic activity status and state of literacy, in 1394" 

[[title]]
lang = "fa"
text = "جمعیت ۱۰ ساله و بیشتر بر حسب جنس و وضع فعالیت اقتصادی به تفکیک وضع سواد در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۱۰ در صفحه ۸۹،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 10 on page 89, Results of the 1394 Labour force survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1714fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1714en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Population aged 10 and over disaggregated by gender, economic activity status and state of literacy, in 1394"

  [[resources.title]]
  lang = "fa"
  text = "جمعیت ۱۰ ساله و بیشتر بر حسب جنس و وضع فعالیت اقتصادی به تفکیک وضع سواد در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – literate and illiterate – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – literate – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Primary school – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Middle school – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Secondary school – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "High school diploma – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Associate degree – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Degree – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "MA and DVM degrees – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "PHD – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Non-formal literacy – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Illiterate – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – literate and illiterate – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – literate – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Primary school – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Middle school – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Secondary school – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "High school diploma – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Associate degree – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Degree – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "MA and DVM degrees – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "PHD – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Non-formal literacy – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Illiterate – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – literate and illiterate – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Total – literate – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Primary school – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Middle school – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Secondary school – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "High school diploma – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Associate degree – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Degree – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "MA and DVM degrees – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "PHD – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Non-formal literacy – rural area"
      type = "string"


