name = "sciehe1711"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment", "population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Unemployment rate", "Economic participation rate", "Agriculture", "Industry", "Services"]

[[keywords]]
lang = "fa" 
wordlist = ["نرخ بیکاری", "نرخ مشارکت اقتصادی", "کشاورزی", "صنعت", "خدمات"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The major indices of work force in the population aged 15 and over as per province in 1394" 

[[title]]
lang = "fa"
text = "شاخص‌های عمده‌ نيروی كار در جمعيت ۱۵ ساله و بيشتر به تفكيک استانی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۳۴ در صفحه ۶۰،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 34 on page 60, Results of the 1394 Labour force survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1711fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1711en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The major indices of work force in the population aged 15 and over as per province in 1394"

  [[resources.title]]
  lang = "fa"
  text = "شاخص‌های عمده‌ نيروی كار در جمعيت ۱۵ ساله و بيشتر به تفكيک استانی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Provinces"
      type = "string"

      [[resources.schema.fields]]
      name = "Economic participation rate"
      type = "string"

      [[resources.schema.fields]]
      name = "The unemployment rate"
      type = "string"

      [[resources.schema.fields]]
      name = "Employment ratio"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of agricultural employment"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of industrial employment"
      type = "string"

      [[resources.schema.fields]]
      name = "The share of service employment"
      type = "string"


