name = "sciehe176"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["The economic participation rate", "Women", "Urban", "rural"]

[[keywords]]
lang = "fa" 
wordlist = ["نرخ مشارکت اقتصادی", "زنان", "شهری", "روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Economic participation rate of the population aged 10 and over by province, gender, urban and rural areas in 1394" 

[[title]]
lang = "fa"
text = "نرخ مشاركت اقتصادی جمعيت ۱۰ ساله و بيشتر برحسب استان به تفكيک جنس، نقاط شهری و روستايی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۲۲ در صفحه ۴۶،‌ نتایج آمارگیری نیروی کار در سال ۱۳۹۴ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 22 on page 46, Results of the 1394 Labour force survey."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe176fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe176en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Economic participation rate of the population aged 10 and over by province, gender, urban and rural areas in 1394"

  [[resources.title]]
  lang = "fa"
  text = "نرخ مشاركت اقتصادی جمعيت ۱۰ ساله و بيشتر برحسب استان به تفكيک جنس، نقاط شهری و روستايی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Provinces"
      type = "string"

      [[resources.schema.fields]]
      name = "Total Male & Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Total Male"
      type = "string"

      [[resources.schema.fields]]
      name = "Total Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas Male & Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas Male"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban areas Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas Male & Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural areas Male"
      type = "string"


