name = "sciehe163fa"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1394] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["employment", "unemployment", "Iran"]

[[keywords]]
lang = "fa" 
wordlist = ["بیکاری", "اشتغال"]

[author]
web = "http://rc.majlis.ir/fa/report/show/985478"

  [[author.name]] 
  lang = "fa"
  text = "مرکز پژوهش‌های مجلس"

  [[author.name]]
  lang = "en"
  text = "Islamic Parliament Research Center"

[[title]]
lang = "en" 
text = "Unemployment rate (1384 - 1394)" 

[[title]]
lang = "fa"
text = "نرخ بیکاری در ایران"

[[description]]
lang = "fa"
text = "این مجموعه داده از نمودار شماره ۶ از گزارش مرکز پژوهش‌های مجلس و به نقل از مرکز آمار تهیه شده است"

[[description]]
lang = "en"
text = ""

[[resources]]

  url = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe163fa.csv"

  [[resources.title]]
  lang = "en" 
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "Islamic Parliament Research Center" 
  web = "http://rc.majlis.ir/fa/report/show/985478" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Field_name"
      type = "string"
