name = "sciehe174"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1372, 1393] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Non-food expenditure"]

[[keywords]]
lang = "fa" 
wordlist = ["هزينه‌های غيرخوراكی"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6224/hazine_ghyrekhoraki.nakhales.u.dahak.xls"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The average gross annual non-food expenditure of urban and rural households in each of the years 1372 to 1393 the annual cost deciles" 

[[title]]
lang = "fa"
text = "متوسط‌ انواع‌ هزينه‌های غيرخوراكی ناخالص سالانه‌ی ‌يک ‌خانوار شهری و روستایی ‌در هر يک از دهک‌های ‌هزينه‌ی سالانه طی سال‌های ۱۳۷۲ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مركز آمار ايران، نتايج طرح آمارگيری ازهزينه و درآمد خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of Statistical Center of Iran, the results of the cost and income census."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe174fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe174en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average gross annual non-food expenditure of urban and rural households in each of the years 1372 to 1393 the annual cost deciles"

  [[resources.title]]
  lang = "fa"
  text = "متوسط‌ انواع‌ هزينه‌های غيرخوراكی ناخالص سالانه‌ی ‌يک ‌خانوار شهری و روستایی ‌در هر يک از دهک‌های ‌هزينه‌ی سالانه طی سال‌های ۱۳۷۲ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6224/hazine_ghyrekhoraki.nakhales.u.dahak.xls" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Years (Figures in Thousand Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "1372"
      type = "string"

      [[resources.schema.fields]]
      name = "1373"
      type = "string"

      [[resources.schema.fields]]
      name = "1374"
      type = "string"

      [[resources.schema.fields]]
      name = "1375"
      type = "string"

      [[resources.schema.fields]]
      name = "1376"
      type = "string"

      [[resources.schema.fields]]
      name = "1377"
      type = "string"

      [[resources.schema.fields]]
      name = "1378"
      type = "string"

      [[resources.schema.fields]]
      name = "1379"
      type = "string"

      [[resources.schema.fields]]
      name = "1380"
      type = "string"

      [[resources.schema.fields]]
      name = "1381"
      type = "string"

      [[resources.schema.fields]]
      name = "1382"
      type = "string"

      [[resources.schema.fields]]
      name = "1383"
      type = "string"

      [[resources.schema.fields]]
      name = "1384"
      type = "string"

      [[resources.schema.fields]]
      name = "1385"
      type = "string"

      [[resources.schema.fields]]
      name = "1386"
      type = "string"

      [[resources.schema.fields]]
      name = "1387"
      type = "string"

      [[resources.schema.fields]]
      name = "1388"
      type = "string"

      [[resources.schema.fields]]
      name = "1389"
      type = "string"

      [[resources.schema.fields]]
      name = "1390"
      type = "string"

      [[resources.schema.fields]]
      name = "1391"
      type = "string"

      [[resources.schema.fields]]
      name = "1392"
      type = "string"


