name = "sciehe1737"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["employment", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Literate inactive population", "Quaification", "Women", "Urban", "Rural"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت غیرفعال باسواد", "مدرک تحصیلی", "زنان", "شهری", "روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Literate inactive population of 10 years and over in course or qualification terms disaggregated by gender and province in 1394" 

[[title]]
lang = "fa"
text = "جمعیت ۱۰ ساله و بیش‌تر غیرفعال باسواد برحسب دوره یا مدرک تحصیلی به تفکیک جنس و استان در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول شماره  ۴۳ در صفحات ۳۰۷ تا ۳۲۴، نتایج آمارگیری نیروی کار ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from Table 43 on pages 307 to 324, Results of the labor force survey in 1394."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1737fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1737en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Literate inactive population of 10 years and over in course or qualification terms disaggregated by gender and province in 1394"

  [[resources.title]]
  lang = "fa"
  text = "جمعیت ۱۰ ساله و بیش‌تر غیرفعال باسواد برحسب دوره یا مدرک تحصیلی به تفکیک جنس و استان در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_ank_94.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Gender and province"
      type = "string"

      [[resources.schema.fields]]
      name = "Total (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Primary (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Middle school (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Secondary (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "High school diploma (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Diploma and BA (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Master's degree or higher (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Literacy and non-formal (all country) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Total (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Primary (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Middle school (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Secondary (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "High school diploma (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Diploma and BA (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Master's degree or higher (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Literacy and non-formal (urban areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Total (rural areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Primary (rural areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Middle school (rural areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Secondary (rural areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "High school diploma (rural areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Diploma and BA (rural areas) – Person"
      type = "string"

      [[resources.schema.fields]]
      name = "Master's degree or higher (rural areas) – Person"
      type = "string"


