name = "sciehe163"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1394] 
frequency = "yearly"
category= []

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = [<WORD_LIST_EN>]

[[keywords]]
lang = "fa" 
wordlist = ["بیکاری", "بیکار", "اشتغال", "شاغل"]

[author]
web = "http://rc.majlis.ir/fa/report/show/985478"

  [[author.name]] 
  lang = "fa"
  text = "مرکز پژوهش‌های مجلس"

  [[author.name]]
  lang = "en"
  text = "<AUTHOR_EN>"

[[title]]
lang = "en" 
text = "<TITLE_EN>" 

[[title]]
lang = "fa"
text = "نرخ بیکاری (درصد)"

[[description]]
lang = "fa"
text = ""

[[description]]
lang = "en"
text = ""

[[resources]]

  url = ""

  [[resources.title]]
  lang = "en" 
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "<SOURCE_NAME>" 
  web = "http://rc.majlis.ir/fa/report/show/985478" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Field_name"
      type = "string"
