name = "sciehe1746"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1389, 1389] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["labor force", "unemployment", "work", "urban population", "rural poplulation"]

[[keywords]]
lang = "fa" 
wordlist = ["نیروی کار", "بیکاری", "کار", "جمعیت شهری", "جمعیت روستایی"]

[author]
web = "نتایج آمارگیری نیروی کار ۱۳۸۹"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "estimation rate of 10 years old and more unemployees based on age groups divided by gender, urban and rural areas in 1389" 

[[title]]
lang = "fa"
text = "برآورد نرخ بیکاری جمعیت ۱۰ ساله و بیشتر بر حسب گروههای سنی به تفکیک جنس، نقاط شهری و روستایی در سال ۱۳۸۹"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of Statistical Centre of Iran"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1746fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1746en.csv"

  [[resources.title]]
  lang = "en" 
  text = "estimation rate of 10 years old and more unemployees based on age groups divided by gender, urban and rural areas in 1389"

  [[resources.title]]
  lang = "fa"
  text = "برآورد نرخ بیکاری جمعیت ۱۰ ساله و بیشتر بر حسب گروههای سنی به تفکیک جنس، نقاط شهری و روستایی در سال ۱۳۸۹"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "نتایج آمارگیری نیروی کار ۱۳۸۹" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "major age groups"
      type = "string"

      [[resources.schema.fields]]
      name = "male and female"
      type = "string"

      [[resources.schema.fields]]
      name = "male"
      type = "string"

      [[resources.schema.fields]]
      name = "female"
      type = "string"

      [[resources.schema.fields]]
      name = "urban areas"
      type = "string"


