name = "scied171"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1367, 1393] 
category= ["education", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Male students,", "Female students,", "Student population"]

[[keywords]]
lang = "fa" 
wordlist = ["دانشجوی مرد،", "دانشجوی زن،", "جمعیت دانشجویان"]

[author]
web = "https://www.amar.org.ir/%D9%BE%D8%A7%DB%8C%DA%AF%D8%A7%D9%87-%D9%87%D8%A7-%D9%88-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%87%D8%A7/%D8%B3%D8%B1%DB%8C%D9%87%D8%A7%DB%8C-%D8%B2%D9%85%D8%A7%D9%86%DB%8C/agentType/ViewType/PropertyTypeID/19"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Students of univercities and higher education centers and Islamic Azad University students in major groups according to their field of study and gender" 

[[title]]
lang = "fa"
text = "دانشجويان دانشگاه‌ها و مراكز آموزش عالی و دانشگاه آزاد اسلامی برحسب گروه‌های عمده‌ی رشته‌ی تحصيلی و جنس"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied171fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ed/scied171en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Students of univercities and higher education centers and Islamic Azad University students in major groups according to their field of study and gender"

  [[resources.title]]
  lang = "fa"
  text = "دانشجويان دانشگاه‌ها و مراكز آموزش عالی و دانشگاه آزاد اسلامی برحسب گروه‌های عمده‌ی رشته‌ی تحصيلی و جنس"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/%D9%BE%D8%A7%DB%8C%DA%AF%D8%A7%D9%87-%D9%87%D8%A7-%D9%88-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%87%D8%A7/%D8%B3%D8%B1%DB%8C%D9%87%D8%A7%DB%8C-%D8%B2%D9%85%D8%A7%D9%86%DB%8C/agentType/ViewType/PropertyTypeID/19" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Group/School Year"
      type = "string"

      [[resources.schema.fields]]
      name = "1367-1368 "
      type = "string"

      [[resources.schema.fields]]
      name = "1368-1369 "
      type = "string"

      [[resources.schema.fields]]
      name = "1369-1370 "
      type = "string"

      [[resources.schema.fields]]
      name = "1370-1371 "
      type = "string"

      [[resources.schema.fields]]
      name = "1371-1372 "
      type = "string"

      [[resources.schema.fields]]
      name = "1372-1373 "
      type = "string"

      [[resources.schema.fields]]
      name = "1373-1374  "
      type = "string"

      [[resources.schema.fields]]
      name = "1374-1375 "
      type = "string"

      [[resources.schema.fields]]
      name = "1375-1376 "
      type = "string"

      [[resources.schema.fields]]
      name = "1376-1377 "
      type = "string"

      [[resources.schema.fields]]
      name = "1377-1378 "
      type = "string"

      [[resources.schema.fields]]
      name = "1378-1379 "
      type = "string"

      [[resources.schema.fields]]
      name = "1379-1380 "
      type = "string"

      [[resources.schema.fields]]
      name = "1380-1381 "
      type = "string"

      [[resources.schema.fields]]
      name = "1381-1382 "
      type = "string"

      [[resources.schema.fields]]
      name = "1382-1383 "
      type = "string"

      [[resources.schema.fields]]
      name = "1383-1384 "
      type = "string"

      [[resources.schema.fields]]
      name = "1384-1385 "
      type = "string"

      [[resources.schema.fields]]
      name = "1385-1386 "
      type = "string"

      [[resources.schema.fields]]
      name = "1386-1387 "
      type = "string"

      [[resources.schema.fields]]
      name = "1387-1388 "
      type = "string"

      [[resources.schema.fields]]
      name = "1388-1389 "
      type = "string"

      [[resources.schema.fields]]
      name = "1389-1390 "
      type = "string"

      [[resources.schema.fields]]
      name = "1390-1391"
      type = "string"

      [[resources.schema.fields]]
      name = "1391-1392"
      type = "string"

      [[resources.schema.fields]]
      name = "1392-1393"
      type = "string"


