name = "sciehe1619"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1391, 1391] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["unemployment", "employment", "labour market", "urban area", "rural area"]

[[keywords]]
lang = "fa" 
wordlist = ["بیکاری", "اشتغال", "بازار کار", "شهری", "روستایی"]

[author]
web = "http://lib.sci.org.ir/DIGLIB/getfile.aspx?fileid=8412"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The estimated population of 10 years and over, disaggregated by sex, rural and urban area (1391)" 

[[title]]
lang = "fa"
text = "برآورد نرخ مشارکت اقتصادی جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکفک جنس، نقاط شهری و روستایی(سال ۱۳۹۱)"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۹ در صفحه ۳۴ نتایج آمارگیری نیروی کار ۱۳۹۱ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 9, page 34, of the 1391 Labour Force Survey"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1619fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/sciehe1619en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The estimated population of 10 years and over, disaggregated by sex, rural and urban area (1391)"

  [[resources.title]]
  lang = "fa"
  text = "برآورد نرخ مشارکت اقتصادی جمعیت ۱۰ساله و بیشتر بر حسب وضع فعالیت به تفکفک جنس، نقاط شهری و روستایی(سال ۱۳۹۱)"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://lib.sci.org.ir/DIGLIB/getfile.aspx?fileid=8412" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Age"
      type = "string"

      [[resources.schema.fields]]
      name = "Male & Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Male"
      type = "string"

      [[resources.schema.fields]]
      name = "Female"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban Areas"
      type = "string"


