name = "scien175"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1375 ,  1393] 
category= ["environment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["amount of pollutants and greenhouse gas emissions from the industrial sector", "share of the transport sector in environmental degradation"]

[[keywords]]
lang = "fa" 
wordlist = ["مقدار انتشار گازهای آلاینده و گلخانه‌ای از بخش صنعت", "سهم بخش حمل و نقل در تخریب محیط زیست"]

[author]
web = "https://www.amar.org.ir/پایگاه-ها-و-سامانه-ها/سریهای-زمانی/agentType/ViewType/PropertyTypeID/1601"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The amount of pollutants and greenhouse gas emissions from the industrial sector from 1375 to 1393" 

[[title]]
lang = "fa"
text = "مقدار انتشار گازهای آلاینده و گلخانه‌ای از بخش صنعت از سال ۱۳۷۵ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل مقدار انتشار گازهای آلاینده و گلخانه‌ای از بخش صنعت گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, the amount of pollutants and greenhouse gas emissions from the industrial sector file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/en/scien175fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/en/scien175en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The amount of pollutants and greenhouse gas emissions from the industrial sector from 1375 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "مقدار انتشار گازهای آلاینده و گلخانه‌ای از بخش صنعت از سال ۱۳۷۵ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/پایگاه-ها-و-سامانه-ها/سریهای-زمانی/agentType/ViewType/PropertyTypeID/1601" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Nox - Tons"
      type = "string"

      [[resources.schema.fields]]
      name = "SO2 – Tons"
      type = "string"

      [[resources.schema.fields]]
      name = "CO2 – Tons"
      type = "string"

      [[resources.schema.fields]]
      name = "SO3 – Tons"
      type = "string"

      [[resources.schema.fields]]
      name = "CO – Tons"
      type = "string"

      [[resources.schema.fields]]
      name = "CH4 – Tons"
      type = "string"

      [[resources.schema.fields]]
      name = "SPM – Tons"
      type = "string"


