name = "sciho173"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1383 ,  1387] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Tenancy", "Housing ownership"]

[[keywords]]
lang = "fa" 
wordlist = ["اجاره نشینی", "نحوه تصرف مسکن"]

[author]
web = "https://amar.sci.org.ir/Detail.aspx?Ln=F&no=264971&S=SS"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The way of acquiring homes used by rural household in each expense decile between 1383 and 1387" 

[[title]]
lang = "fa"
text = "نحوه تصرف مسکن مورد استفاده خانوار روستایی در هریک از گروه‌های هزینه طی سال‌های ۱۳۸۳ تا  ۱۳۸۷"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho173fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho173en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The way of acquiring homes used by rural household in each expense decile between 1383 and 1387"

  [[resources.title]]
  lang = "fa"
  text = "نحوه تصرف مسکن مورد استفاده خانوار روستایی در هریک از گروه‌های هزینه طی سال‌های ۱۳۸۳ تا  ۱۳۸۷"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://amar.sci.org.ir/Detail.aspx?Ln=F&no=264971&S=SS" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Housing ownership of used household"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) Total"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 7,200,000 Rials & less"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 7,200,001 – 9,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 9,000,001 – 12,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 12,000,001 – 16,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 16,500,001 – 19,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 19,500,001 – 24,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 24,000,001 – 30,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 30,000,001 – 45,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 45,000,001 – 60,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1383) 60,000,001 Rials & more"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) Total"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 7,200,000 Rials & less"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 7,200,001 – 9,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 9,000,001 – 12,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 12,000,001 – 16,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 16,500,001 – 19,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 19,500,001 – 24,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 24,000,001 – 30,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 30,000,001 – 45,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 45,000,001 – 60,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1384) 60,000,001 Rials & more"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) Total"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 7,200,000 Rials & less"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 7,200,001 – 9,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 9,000,001 – 12,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 12,000,001 – 16,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 16,500,001 – 19,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 19,500,001 – 24,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 24,000,001 – 30,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 30,000,001 – 45,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 45,000,001 – 60,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1385) 60,000,001 Rials & more"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) Total"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 7,200,000 Rials & less"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 7,200,001 – 9,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 9,000,001 – 12,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 12,000,001 – 16,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 16,500,001 – 19,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 19,500,001 – 24,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 24,000,001 – 30,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 30,000,001 – 45,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 45,000,001 – 60,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1386) 60,000,001 Rials & more"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) Total"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 7,200,000 Rials & less"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 7,200,001 – 9,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 9,000,001 – 12,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 12,000,001 – 16,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 16,500,001 – 19,500,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 19,500,001 – 24,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 24,000,001 – 30,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 30,000,001 – 45,000,000"
      type = "string"

      [[resources.schema.fields]]
      name = "(1387) 45,000,001 – 60,000,000"
      type = "string"


