name = "scihsp171"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1367, 1394] 
category= ["education", "women"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["The number of students", "Medical", "Humanities studies", "Basic sciences", "Engineering", "Agriculture and veterinary", "Art"]

[[keywords]]
lang = "fa" 
wordlist = ["تعداد دانشجویان", "پزشكی", "علوم انسانی", "علوم پايه", "فنی مهندسی", "كشاورزی و دامپزشكی", "هنر"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6363/daneshjo93-94..xlsx"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The number of students in universities and higher education centers and Azad Islamic University in terms of major education groups and gender during the years 1367 to 1394" 

[[title]]
lang = "fa"
text = "تعداد دانشجويان دانشگاه‌ها و مراكز آموزش عالی و دانشگاه آزاد اسلامی برحسب گروه‌های عمده‌ی رشته‌ی تحصيلی و جنسیت طی سال‌های ۱۳۶۷ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/hsp/scihsp171fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/hsp/scihsp171en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The number of students in universities and higher education centers and Azad Islamic University in terms of major education groups and gender during the years 1367 to 1394"

  [[resources.title]]
  lang = "fa"
  text = "تعداد دانشجويان دانشگاه‌ها و مراكز آموزش عالی و دانشگاه آزاد اسلامی برحسب گروه‌های عمده‌ی رشته‌ی تحصيلی و جنسیت طی سال‌های ۱۳۶۷ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/6363/daneshjo93-94..xlsx" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Group / Academic year"
      type = "string"

      [[resources.schema.fields]]
      name = "1367-1368 "
      type = "string"

      [[resources.schema.fields]]
      name = "1368-1369 "
      type = "string"

      [[resources.schema.fields]]
      name = "1369-1370 "
      type = "string"

      [[resources.schema.fields]]
      name = "1370-1371 "
      type = "string"

      [[resources.schema.fields]]
      name = "1371-1372 "
      type = "string"

      [[resources.schema.fields]]
      name = "1372-1373 "
      type = "string"

      [[resources.schema.fields]]
      name = "1373-1374  "
      type = "string"

      [[resources.schema.fields]]
      name = "1374-1375 "
      type = "string"

      [[resources.schema.fields]]
      name = "1375-1376 "
      type = "string"

      [[resources.schema.fields]]
      name = "1376-1377 "
      type = "string"

      [[resources.schema.fields]]
      name = "1377-1378 "
      type = "string"

      [[resources.schema.fields]]
      name = "1378-1379 "
      type = "string"

      [[resources.schema.fields]]
      name = "1379-1380 "
      type = "string"

      [[resources.schema.fields]]
      name = "1380-1381 "
      type = "string"

      [[resources.schema.fields]]
      name = "1381-1382 "
      type = "string"

      [[resources.schema.fields]]
      name = "1382-1383 "
      type = "string"

      [[resources.schema.fields]]
      name = "1383-1384 "
      type = "string"

      [[resources.schema.fields]]
      name = "1384-1385 "
      type = "string"

      [[resources.schema.fields]]
      name = "1385-1386 "
      type = "string"

      [[resources.schema.fields]]
      name = "1386-1387 "
      type = "string"

      [[resources.schema.fields]]
      name = "1387-1388 "
      type = "string"

      [[resources.schema.fields]]
      name = "1388-1389 "
      type = "string"

      [[resources.schema.fields]]
      name = "1389-1390 "
      type = "string"

      [[resources.schema.fields]]
      name = "1390-1391"
      type = "string"

      [[resources.schema.fields]]
      name = "1391-1392"
      type = "string"

      [[resources.schema.fields]]
      name = "1392-1393"
      type = "string"


