name = "sciho175"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1386, 1393] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Housing", "Residential infrastructure", "Housing for urban households"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن", "زیربنای مسکونی", "مسکن خانوار شهری"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_aahvdkhsh_93.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The percentage of urban households as per the land area of the residence of the household in each of the annual expense deciles between 1386 and 1393" 

[[title]]
lang = "fa"
text = "درصد خانوارها‌ی شهری بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهک‌های هزينه سالانه در طی سال‌های ۱۳۸۶ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۸-۱ در صفحه ۶۸، نتايج آمارگيری از هزينه و درآمد خانوارهای شهری سال ۱۳۹۳، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 28-1 on page 68, the results of surveys of expenditure and income of urban households in 1393."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho175fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho175en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The percentage of urban households as per the land area of the residence of the household in each of the annual expense deciles between 1386 and 1393"

  [[resources.title]]
  lang = "fa"
  text = "درصد خانوارها‌ی شهری بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهک‌های هزينه سالانه در طی سال‌های ۱۳۸۶ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_aahvdkhsh_93.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "The average floor area of residence (sqm)"
      type = "string"

      [[resources.schema.fields]]
      name = "Total"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile"
      type = "string"


