name = "sciho1722"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1374 ,  1394] 
category= ["housing", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["average price of building materials"]

[[keywords]]
lang = "fa" 
wordlist = ["متوسط قيمت مصالح ساختمانی"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/ساختمان-و-مسکن#48839---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The average prices of construction materials of the second half of 1374 to the first half of 1394" 

[[title]]
lang = "fa"
text = "متوسط قيمت مصالح ساختمانی منتخب نيمه دوم ۱۳۷۴ تا نيمه اول ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل متوسط قيمت مصالح ساختمانی منتخب سالانه گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, annual average of the prices of building materials file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1722fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1722en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average prices of construction materials of the second half of 1374 to the first half of 1394"

  [[resources.title]]
  lang = "fa"
  text = "متوسط قيمت مصالح ساختمانی منتخب نيمه دوم ۱۳۷۴ تا نيمه اول ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/ساختمان-و-مسکن#48839---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1374 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1375 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1375 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1376 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1376 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1377 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1377 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1378 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1378 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1379 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1379 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1380 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1380 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1381 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1381 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1382 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1382 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1383 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1383 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1384 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1384 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1385 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1385 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1386 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1386 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1387 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1387 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1388 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1388 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1389 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1389 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1390 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1390 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1391 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1391 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1392 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1392 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1393 (Rials)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1393 (Rials)"
      type = "string"


