name = "sciho1724"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1372 ,  1394] 
category= ["housing", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["the average rent for a square meter of residential units"]

[[keywords]]
lang = "fa" 
wordlist = ["متوسط اجاره‌بهای يک متر مربع واحد مسكونی"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/ساختمان-و-مسکن"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The average rent for a square meter of residential units in selected cities from 1372 to 1394" 

[[title]]
lang = "fa"
text = "متوسط اجاره‌بهای يک متر مربع واحد مسكونی برحسب شهرهای منتخب كشور از سال ۱۳۷۲ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل متوسط اجاره‌بهای يک متر مربع واحد مسكونی برحسب شهرهای منتخب كشور سالانه گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, average rent for a square meter of residential units annually in selected cities file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1724fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1724en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average rent for a square meter of residential units in selected cities from 1372 to 1394"

  [[resources.title]]
  lang = "fa"
  text = "متوسط اجاره‌بهای يک متر مربع واحد مسكونی برحسب شهرهای منتخب كشور از سال ۱۳۷۲ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/ساختمان-و-مسکن" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1372 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1372 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1373 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1373 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1374 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1374 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1375 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1375 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1376 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1376 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1377 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1377 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1378 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1378 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1379 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1379 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1380 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1380 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1381 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1381 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1382 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1382 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1383 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1383 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1384 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1384 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1385 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1385 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1386 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1386 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1387 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1387 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1388 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1388 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1389 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1389 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1390 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1390 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1391 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1391 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1392 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1392 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "First half 1393 (thousands IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "Second half 1393 (thousands IRR)"
      type = "string"


