name = "sciho1714"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [۱۳۸۹, ۱۳۸۹] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Housing", "Residential infrastructure", "Housing for rural households"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن", "زیربنای مسکونی", "مسکن خانوار روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/abstract/1389/n_h_r89.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The percentage of rural households in terms of ground area of households' place of residence in each deciles of 1389 annual costs" 

[[title]]
lang = "fa"
text = "درصد خانوارها‌ی روستايی بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهک‌های هزينه سالانه در ۱۳۸۹"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۸-۱ در صفحه ۷۰، نتايج آمارگيری از هزينه و درآمد خانوارهای روستایی سال ۱۳۸۹، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 28-1 on page 80, the results of surveys of expenditure and income of rural households in 1389."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "" 

  [[resources.url]]
  lang = "en"
  link = ""

  [[resources.title]]
  lang = "en" 
  text = "The percentage of rural households in terms of ground area of households' place of residence in each deciles of 1389 annual costs"

  [[resources.title]]
  lang = "fa"
  text = "درصد خانوارها‌ی روستايی بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهک‌های هزينه سالانه در ۱۳۸۹"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/abstract/1389/n_h_r89.pdf" 

  [resources.schema]
  format = "csv"


