name = "sciho1710"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1391, 1391] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Housing", "Residential infrastructure", "Housing for rural households"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن", "زیربنای مسکونی", "مسکن خانوار روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1391/n_hdr_91.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The percentage of rural households in terms of ground area of households' place of residence in each deciles of 1391  annual costs" 

[[title]]
lang = "fa"
text = "درصد خانوارها‌ی روستایی بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهك‌های هزينه سالانه در سال ۱۳۹۱" 

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۸-۱ در صفحه ۶۸، نتايج آمارگيری از هزينه و درآمد خانوارهای روستایی سال ۱۳۹۱، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from table 28-1 on page 68, the results of surveys of expenditure and income of rural households in 1391."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1710fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1710en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The percentage of rural households in terms of ground area of households' place of residence in each deciles of 1391  annual costs"

  [[resources.title]]
  lang = "fa"
  text = "درصد خانوارها‌ی روستایی بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهك‌های هزينه سالانه در سال ۱۳۹۱"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1391/n_hdr_91.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Average ground area of residence of households (sqm) "
      type = "string"

      [[resources.schema.fields]]
      name = "Total"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile"
      type = "string"


