name = "sciho176"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1386, 1393] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Housing", "Residential infrastructure", "Rural households"]

[[keywords]]
lang = "fa" 
wordlist = ["مسکن", "زیربنای مسکونی", "خانوار روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ahvdkhr_93.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The percentage of rural households in terms of ground area of households' place of residence in each deciles of 1393  annual costs" 

[[title]]
lang = "fa"
text = "درصد خانوارها‌ی روستایی بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهک‌های هزينه سالانه در سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۸-۱ در صفحه ۶۸، نتايج آمارگير هزينه و درآمد خانوارهای روستایی
سال ۱۳۹۳، استخراج شده است."

[[description]]
lang = "en"
text = "داده‌های مربوط به سال ۱۳۹۳، از جدول شماره ۲۸-۱ در صفحه ۶۸، <a href='http&#58;https;//www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ahvdkhr_93.pdf'> نتايج آمارگير هزينه و درامد خانوارهای روستایی

سال ۱۳۹۳ <a>، استخراج شده است."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho176fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho176en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The percentage of rural households in terms of ground area of households' place of residence in each deciles of 1393  annual costs"

  [[resources.title]]
  lang = "fa"
  text = "درصد خانوارها‌ی روستایی بر حسب سطح زيربنای محل سكونت خانوار در هر يک از دهک‌های هزينه سالانه در سال ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1393/n_ahvdkhr_93.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "The average floor area of residence (sqm)"
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Tenth decile 1393 "
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Tenth decile 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Tenth decile 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Tenth decile 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Tenth decile 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Tenth decile 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Tenth decile 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Total 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "The first decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Second decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Third decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Fourth decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Fifth decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Sixth decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Seventh decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Eighth decile 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Ninth decile 1386"
      type = "string"


