name = "sciho1726"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1335 ,  1390] 
category= ["housing", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["number of urban households by occupation location", "number of rural households by occupation location", "land and building", "building", "rental", "versus service", "tenancy deposit", "free of charge property"]

[[keywords]]
lang = "fa" 
wordlist = ["تعداد خانوارشهری برحسب نحوه‌ تصرف محل سكونت", "تعداد خانوارروستایی برحسب نحوه‌ تصرف محل سكونت", "ملكی عرصه و اعيان", "ملكی اعيان", "اجاره‌ای", "در برابر خدمت", "رهنی", "ملک مجانی"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/ساختمان-و-مسکن"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The number of standard households living in terms of ownership of the property of residence from 1335 to 1390" 

[[title]]
lang = "fa"
text = "تعداد خانوارهای معمولی ساكن برحسب نحوه‌ تصرف محل سكونت خانوار از سال ۱۳۳۵ تا ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل تعداد خانوارهای معمولی ساكن برحسب نحوه‌ تصرف محل سكونت خانوار گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, the number of standard households living in terms of ownership of the property of residence file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1726fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1726en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The number of standard households living in terms of ownership of the property of residence from 1335 to 1390"

  [[resources.title]]
  lang = "fa"
  text = "تعداد خانوارهای معمولی ساكن برحسب نحوه‌ تصرف محل سكونت خانوار از سال ۱۳۳۵ تا ۱۳۹۰"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/ساختمان-و-مسکن" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – land and building"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – building"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – rental"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – versus a service"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – Tenancy deposit"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – endowment"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – free of charge"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – others"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban – undeclared"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – land and building"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – building"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – rental"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – versus a service"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – tenancy deposit"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – endowment"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – free grants"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – non property assets and free of charge"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – free of charge"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural – others"
      type = "string"


