name = "sciho1730"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1390 ,  1394] 
category= ["housing"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Residential rental prices in Tehran"]

[[keywords]]
lang = "fa" 
wordlist = ["قیمت اجاره مسکونی در تهران"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_eghvemdsht_94-4.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The average monthly rent plus three percent deposit to rent a sqm of residentail in Tehran from 1390 to 1394" 

[[title]]
lang = "fa"
text = "متوسط مبلغ اجاره ماهانه به علاوه سه درصد ودیعـه پرداختـی بـرای اجـاره یـک مترمربـع زیربنـای مسـکونی در شـهر تهران از ۱۳۹۰ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحات ۳۲ و ۳۳ جدول ۶، اطلاعات قیمت و اجاره در شهر تهران - زمستان ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the table 6 on pages 32 & 33, Purchase and rental prices of residentail housing in Tehran, Winter 1396"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1730fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ho/sciho1730en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average monthly rent plus three percent deposit to rent a sqm of residentail in Tehran from 1390 to 1394"

  [[resources.title]]
  lang = "fa"
  text = "متوسط مبلغ اجاره ماهانه به علاوه سه درصد ودیعـه پرداختـی بـرای اجـاره یـک مترمربـع زیربنـای مسـکونی در شـهر تهران از ۱۳۹۰ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/fulltext/1394/n_eghvemdsht_94-4.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Title"
      type = "string"

      [[resources.schema.fields]]
      name = "Spring 1390 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Summer 1390 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Autumn 1390 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Winter 1390 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Spring 1391 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Summer 1391 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Autumn 1391 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Winter 1391 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Spring 1392 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Summer 1392 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Autumn 1392 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Winter 1392 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Spring 1393 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Summer 1393 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Autumn 1393 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Winter 1393 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Spring 1394 – Thousands IRR"
      type = "string"

      [[resources.schema.fields]]
      name = "Summer 1394 – Thousands IRR"
      type = "string"


