name = "scinre178"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1380 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["total primary energy supply", "final energy consumption", "primary energy production", "energy imports"]

[[keywords]]
lang = "fa" 
wordlist = ["عرضه كل انرژی اوليه", "مصرف نهایی انرژی", "تولید انرژی اولیه", "واردات انرژی"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The total primary energy supply, final consumption, primary energy production and energy imports from 1380 to 1393" 

[[title]]
lang = "fa"
text = "عرضه کل انرژی اولیه، مصرف نهایی، تولید انرژی اولیه و واردات انرژی از سال ۱۳۸۰ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل عرضه کل انرژی اولیه، مصرف نهایی، تولید انرژی اولیه و واردات انرژی گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, The total primary energy supply, final consumption, primary energy production and energy imports file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre178fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre178en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The total primary energy supply, final consumption, primary energy production and energy imports from 1380 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "عرضه کل انرژی اولیه، مصرف نهایی، تولید انرژی اولیه و واردات انرژی از سال ۱۳۸۰ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "The total primary energy supply (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Final energy consumption (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Primary energy production (million barrels of oil equivalent)"
      type = "string"


