name = "scinre174"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1367 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price of light crude oil in Iran", "price of heavy crude oil in Iran"]

[[keywords]]
lang = "fa" 
wordlist = ["قیمت نفت خام سبک ایران", "قیمت نفت خام سنگین ایران"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Spot prices of light and heavy crude oil of Iran from 1367 to 1393" 

[[title]]
lang = "fa"
text = "قیمت‌های اسپات نفت خام سبک و سنگین ایران از سال ۱۳۶۷ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل قیمت‌های اسپات نفت خام سبک و سنگین ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, spot crude oil prices of light and heavy file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre174fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre174en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Spot prices of light and heavy crude oil of Iran from 1367 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "قیمت‌های اسپات نفت خام سبک و سنگین ایران از سال ۱۳۶۷ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Iranian light crude oil (US dollar / barrel)"
      type = "string"


