name = "scinre172"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["household electricity consumption", "general power consumption", "commercial power consumption", "industrial power consumption", "power consumption of transport", "agricultural power consumption"]

[[keywords]]
lang = "fa" 
wordlist = ["مصرف برق خانگی", "مصرف برق عمومی", "مصرف برق تجاری", "مصرف برق صنعتی", "مصرف برق حمل و نقل", "مصرف برق کشاورزی"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Power consumption in different sectors from 1384 to 1393" 

[[title]]
lang = "fa"
text = "مصرف برق به تفکیک بخش‌های مختلف از سال ۱۳۸۴ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل مصرف برق به تفکیک بخش‌های مختلف گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, electricity consumption in various sectors file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre172fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre172en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Power consumption in different sectors from 1384 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "مصرف برق به تفکیک بخش‌های مختلف از سال ۱۳۸۴ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Household (GWH)"
      type = "string"

      [[resources.schema.fields]]
      name = "Public (GWH)"
      type = "string"

      [[resources.schema.fields]]
      name = "Commercial (GWH)"
      type = "string"

      [[resources.schema.fields]]
      name = "Industrial (GWH)"
      type = "string"

      [[resources.schema.fields]]
      name = "Transportation (GWH)"
      type = "string"

      [[resources.schema.fields]]
      name = "Agricultural (GWH)"
      type = "string"

      [[resources.schema.fields]]
      name = "Other consumptions (GWH)"
      type = "string"


