name = "scinre176"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1377 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["production of conventional gasoline and MTBE"]

[[keywords]]
lang = "fa" 
wordlist = ["توليد بنزين معمولی و MTBE"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Regular gasoline and MTBE production in refineries of Iran from 1377 to 1393" 

[[title]]
lang = "fa"
text = "توليد بنزين معمولی و MTBE در پالايشگاه‌های كشور از سال ۱۳۷۷ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل توليد بنزين معمولی و MTBE در پالايشگاه‌های كشور گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, regular gasoline and MTBE production in refineries file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre176fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre176en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Regular gasoline and MTBE production in refineries of Iran from 1377 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "توليد بنزين معمولی و MTBE در پالايشگاه‌های كشوراز سال ۱۳۷۷ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"


