name = "scinre1721"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1370 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["total of mines", "silica", "chromite", "decorative stone", "limestone", "manganese", "lead and zinc", "ironstone", "copper", "coal"]

[[keywords]]
lang = "fa" 
wordlist = ["کل معادن", "سيليس", "كروميت", "سنگ‌های تزئينی", "سنگ آهک", "منگنز", "سرب و روی", "سنگ آهن", "مس", "زغال سنگ"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/صنعت-و-معدن#49048---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Investment value, operating mines in the country according to the type of activity from 1370 to 1393" 

[[title]]
lang = "fa"
text = "ارزش سرمایه‌گذاری معادن در حال بهره‌برداری کشور برحسب نوع فعاليت معدن از سال ۱۳۷۰ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل ارزش سرمایه‌گذاری معادن در حال بهره‌برداری کشور برحسب نوع فعاليت معدن گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, Investment value operating mines in the country according to the type of activity file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1721fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1721en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Investment value, operating mines in the country according to the type of activity from 1370 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "ارزش سرمایه‌گذاری معادن در حال بهره‌برداری کشور برحسب نوع فعاليت معدن از سال ۱۳۷۰ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/صنعت-و-معدن#49048---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "Total of mines"
      type = "string"

      [[resources.schema.fields]]
      name = "Manganese"
      type = "string"

      [[resources.schema.fields]]
      name = "Silica"
      type = "string"

      [[resources.schema.fields]]
      name = "Copper"
      type = "string"

      [[resources.schema.fields]]
      name = "gypsum"
      type = "string"

      [[resources.schema.fields]]
      name = "Decorative stone"
      type = "string"

      [[resources.schema.fields]]
      name = "Chromite"
      type = "string"

      [[resources.schema.fields]]
      name = "ironstone"
      type = "string"

      [[resources.schema.fields]]
      name = "Lead and zinc"
      type = "string"

      [[resources.schema.fields]]
      name = "Coal"
      type = "string"

      [[resources.schema.fields]]
      name = "Limestone"
      type = "string"


