name = "scinre179"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1389 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["LPG consumption", "fuel consumption", "kerosene consumption", "gas oil consumption", "fuel oil consumption"]

[[keywords]]
lang = "fa" 
wordlist = ["مصرف گاز مایع", "مصرف بنزین", "مصرف نفت سفید", "مصرف نفت گاز", "مصرف نفت کوره"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Consumption of oil products (except Refinery utilization) from 1389 to 1393 million liters" 

[[title]]
lang = "fa"
text = "مصرف فرآورده‌های عمده نفتی (بجز مصرف پالایشگاه‌ها) از سال ۱۳۸۹ تا ۱۳۹۳ میلیون لیتر"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل مصرف فرآورده‌های عمده نفتی (بجز مصرف پالایشگاه‌ها)  گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, consumption of petroleum products (except Refinery utilization) file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre179fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre179en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Consumption of oil products (except Refinery utilization) from 1389 to 1393 million liters"

  [[resources.title]]
  lang = "fa"
  text = "مصرف فرآورده‌های عمده نفتی (بجز مصرف پالایشگاه‌ها) از سال ۱۳۸۹ تا ۱۳۹۳ میلیون لیتر"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Liquefied petroleum gas (million liters)"
      type = "string"

      [[resources.schema.fields]]
      name = "Gasoline (million liters)"
      type = "string"

      [[resources.schema.fields]]
      name = "Kerosene (million liters)"
      type = "string"

      [[resources.schema.fields]]
      name = "Petroleum gas (million liters)"
      type = "string"

      [[resources.schema.fields]]
      name = "Gas furnaces (million liters)"
      type = "string"


