name = "scinre1712"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1344 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["subscribers of electricity", "domestic sales of electricity", "length of power lines"]

[[keywords]]
lang = "fa" 
wordlist = ["مشتركان برق", "مقدار فروش داخلی انرژی برق", "طول خطوط برق"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The length of power lines, the number of subscribers and the domestic amount of electric energy of institutions affiliated to the Ministry of Energy from 1344 to 1393" 

[[title]]
lang = "fa"
text = "طول خطوط انتقال برق، تعداد مشتركان و مقدار فروش داخلی انرژی برق مؤسسات تابع وزارت نيرو از سال ۱۳۴۴ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل طول خطوط انتقال برق، تعداد مشتركان و مقدار فروش داخلي انرژی برق مؤسسات تابع وزارت نيرو گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, the length of power lines, the number of subscribers and the domestic amount of electric energy of institutions affiliated to the Ministry of Energy file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1712fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1712en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The length of power lines, the number of subscribers and the domestic amount of electric energy of institutions affiliated to the Ministry of Energy from 1344 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "طول خطوط انتقال برق، تعداد مشتركان و مقدار فروش داخلی انرژی برق مؤسسات تابع وزارت نيرو از سال ۱۳۴۴ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Subscribers (thousand subscribers)"
      type = "string"

      [[resources.schema.fields]]
      name = "Domestic electricity sales (million kWh)"
      type = "string"

      [[resources.schema.fields]]
      name = "Length of lines (km circuit) - transmission line - 400 kV"
      type = "string"

      [[resources.schema.fields]]
      name = "Length of lines (km circuit) - transmission line - 230 kV"
      type = "string"

      [[resources.schema.fields]]
      name = "Length of lines (km circuit) - 132 kV distribution line above"
      type = "string"


