name = "scinre1715"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1377 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["liquefied gas production", "light fuel oil production", "heavy fuel oil production", "gas oil production", "white oil production"]

[[keywords]]
lang = "fa" 
wordlist = ["توليد گاز مایع", "توليد نفت کوره سبک", "توليد نفت کوره سنگین", "توليد نفت گاز", "توليد نفت سفید"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Production of oil products in Iran refineries from 1377 to 1393" 

[[title]]
lang = "fa"
text = "توليد فرآورده‌های نفتی در پالايشگاه‌های كشور از سال ۱۳۷۷ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل توليد فرآورده‌های نفتی در پالايشگاه‌های كشور گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, Production of oil products in refineries file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1715fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1715en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Production of oil products in Iran refineries from 1377 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "توليد فرآورده‌های نفتی در پالايشگاه‌های كشور از سال ۱۳۷۷ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Liquefied petroleum gas (cubic meters per day)"
      type = "string"

      [[resources.schema.fields]]
      name = "Light fuel oil (cubic meters per day)"
      type = "string"

      [[resources.schema.fields]]
      name = "Heavy fuel oil (cubic meters per day)"
      type = "string"

      [[resources.schema.fields]]
      name = "Petroleum gas (cubic meters per day)"
      type = "string"


