name = "scinre177"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1355 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["crude oil production"]

[[keywords]]
lang = "fa" 
wordlist = ["مقدار توليد نفت خام"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The amount of crude oil production from 1355 to 1393" 

[[title]]
lang = "fa"
text = "مقدار تولید نفت خام از سال ۱۳۵۵ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل مقدار توليد نفت خام  گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, crude oil production file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre177fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre177en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The amount of crude oil production from 1355 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "مقدار تولید نفت خام از سال ۱۳۵۵ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"


