name = "scinre1711"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["consumption of energy in transport", "consumption of energy in agriculture", "consumption of energy in the industry", "consumption of energy in the domestic sector, public and commercial"]

[[keywords]]
lang = "fa" 
wordlist = ["مصرف انر‌ژی در حمل و نقل", "مصرف انر‌ژی در کشاورزی", "مصرف انر‌ژی در صنعت", "مصرف انر‌ژی در بخش خانگی، عمومی و تجاری"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Energy consumption in different sectors from 1384 to 1393" 

[[title]]
lang = "fa"
text = "مصرف انرژی به تفکیک بخش‌های مختلف از سال ۱۳۸۴ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل مصرف انرژی به تفکیک بخش‌های مختلف گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, energy consumption in various sectors file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1711fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1711en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Energy consumption in different sectors from 1384 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "مصرف انرژی به تفکیک بخش‌های مختلف از سال ۱۳۸۴ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Domestic, public and commercial (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Industrial (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Transport (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Non-energy consumption (million barrels of oil equivalent)"
      type = "string"


