name = "scinre1710"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1380 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["consumption of petroleum products in transport", "consumption of petroleuml products in agriculture", "consumption of petroleuml products in the industry", "consumption of petroleum products in the domestic sector, public and commercial", "non-energy consumption of petroleum products"]

[[keywords]]
lang = "fa" 
wordlist = ["مصرف فرآورده‌های نفتی در حمل و نقل", "مصرف فرآورده‌های نفتی در کشاورزی", "مصرف فرآورده‌های نفتی در صنعت", "مصرف فرآورده‌های نفتی در بخش خانگی، عمومی و تجاری", "مصرف فرآورده‌های نفتی درمصارف غیر انرژی"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Consumption of petroleum products in different sectors from 1380 to 1393" 

[[title]]
lang = "fa"
text = "مصرف فرآورده‌های نفتی در بخش‌های مختلف از سال ۱۳۸۰ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل مصرف فرآورده‌های نفتی در بخش‌های مختلف گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, consumption of petroleum products (except Refinery utilization) file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1710fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1710en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Consumption of petroleum products in different sectors from 1380 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "مصرف فرآورده‌های نفتی در بخش‌های مختلف از سال ۱۳۸۰ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Transport (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Industry (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Domestic, public and commercial (million barrels of oil equivalent)"
      type = "string"

      [[resources.schema.fields]]
      name = "Non-energy consumption (million barrels of oil equivalent)"
      type = "string"


