name = "scinre1713"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1368 ,  1393] 
category= ["energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["price of electricity", "household electricity prices", "public electricity bills", "electricity prices for agricultural", "industrial electricity prices"]

[[keywords]]
lang = "fa" 
wordlist = ["بهای برق", "بهای برق خانگی", "بهای برق عمومی", "بهای برق کشاورزی", "بهای برق صنعتی"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The average consumer price of electricity in different sectors from 1368 to 1393" 

[[title]]
lang = "fa"
text = "متوسط بهای برق در بخش مختلف مصرف کننده از سال ۱۳۶۸ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل متوسط بهای برق در بخش مختلف مصرف کننده گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, the average consumer price of electricity in different sectors file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1713fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nre/scinre1713en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average consumer price of electricity in different sectors from 1368 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "متوسط بهای برق در بخش مختلف مصرف کننده از سال ۱۳۶۸ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/انرژی#48317---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Household (Rial kWh)"
      type = "string"

      [[resources.schema.fields]]
      name = "Public (Rial kWh)"
      type = "string"

      [[resources.schema.fields]]
      name = "Agriculture (Rial kWh)"
      type = "string"

      [[resources.schema.fields]]
      name = "Industry (Rial kWh)"
      type = "string"

      [[resources.schema.fields]]
      name = "Other consumptions (Rial kWh)"
      type = "string"


