name = "scipo174"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385, 1395] 
category= ["population", "employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["household", "population", "urban area", "rural area", "non-resident", "province"]

[[keywords]]
lang = "fa" 
wordlist = ["خانوار", "جمعیت", "نقاط شهری", "نقاط روستايی", "غیرساکن", "استان"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/baravord/household85-95.xls"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Estimates and forecasts of regional households, disaggregated by residency, urban and rural areas from 1385 until 1395 (figures in thousand households)" 

[[title]]
lang = "fa"
text = "برآورد و پیش بینی خانوار استان‌های كشور به تفكيک نقاط شهری و روستايی وغیرساکن از سال ۱۳۸۵ تا ۱۳۹۵ ( ارقام به هزار خانوار )"

[[description]]
lang = "fa"
text = "این داده، نسخه‌ی تمیز شده‌ی فایل منتشر شده‌ی مرکز آمار ایران است."

[[description]]
lang = "en"
text = "Dataset cleaned from an Excel file published by the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo174fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo174en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Estimates and forecasts of regional households, disaggregated by residency, urban and rural areas from 1385 until 1395 (figures in thousand households)"

  [[resources.title]]
  lang = "fa"
  text = "برآورد و پیش بینی خانوار استان‌های كشور به تفكيک نقاط شهری و روستايی وغیرساکن از سال ۱۳۸۵ تا ۱۳۹۵ ( ارقام به هزار خانوار )"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/baravord/household85-95.xls" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Provinces"
      type = "string"

      [[resources.schema.fields]]
      name = "1385*Whole country"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1386 "
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1387"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1388"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1389"
      type = "string"

      [[resources.schema.fields]]
      name = " 1390* Whole country"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1391"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1392"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1393"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1394"
      type = "string"

      [[resources.schema.fields]]
      name = " Whole country1395"
      type = "string"

      [[resources.schema.fields]]
      name = " 1385* Urban area"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area 1386"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area 1387"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "1389"
      type = "string"

      [[resources.schema.fields]]
      name = "1390* Urban area"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area1391"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area 1392"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area 1393"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area 1394"
      type = "string"

      [[resources.schema.fields]]
      name = " Urban area 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "1385*Rural area and non-resident"
      type = "string"

      [[resources.schema.fields]]
      name = " Rural area and non-resident1386"
      type = "string"

      [[resources.schema.fields]]
      name = " Rural area and non-resident1387"
      type = "string"

      [[resources.schema.fields]]
      name = " Rural area and non-resident1388"
      type = "string"

      [[resources.schema.fields]]
      name = " Rural area and non-resident1389"
      type = "string"

      [[resources.schema.fields]]
      name = "1390*Rural area and non-resident"
      type = "string"

      [[resources.schema.fields]]
      name = " Rural area and non-resident1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area and non-resident1392"
      type = "string"

      [[resources.schema.fields]]
      name = " Rural area and non-resident1393"
      type = "string"

      [[resources.schema.fields]]
      name = " Rural area and non-resident1394"
      type = "string"


