name = "scipo1718"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Country divisions", "Province", "County", "District", "Rural district", "City", "Village"]

[[keywords]]
lang = "fa" 
wordlist = ["تقسیمات کشوری", "استان", "شهرستان", "بخش", "دهستان", "شهر", "آبادی"]

[author]
web = "https://www.amar.org.ir/فرادادهها/تقسیمات-کشوری"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Country divisions for year 1394" 

[[title]]
lang = "fa"
text = "تقسیمات کشوری سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of Statistical Centre of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1718fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1718en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Country divisions for year 1394"

  [[resources.title]]
  lang = "fa"
  text = "تقسیمات کشوری سال ۱۳۹۴"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/فرادادهها/تقسیمات-کشوری" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Statistical Address"
      type = "string"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "County"
      type = "string"

      [[resources.schema.fields]]
      name = "District"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural district"
      type = "string"

      [[resources.schema.fields]]
      name = "City"
      type = "string"


