name = "scipo161"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1365, 1385] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["population", "ability to work", "urban area", "rural area"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت", "فعال", "شهری", "روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/census/1385/results/country_1385_general.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Distribution of population aged 10 and over, disaggregated by ability to work, urban and rural area, from 1365 until 1385" 

[[title]]
lang = "fa"
text = " توزیع جمعیت ۱۰ ساله و بیش‌تر بر حسب وضع فعالیت در نقاط شهری و روستایی از ۱۳۶۵ تا ۱۳۸۵"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۲-۱ از نتایج کلی سرشماری عمومی نفوس و مسکن ۱۳۸۵ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 1-22 of the 1385 General Census of Population and Housing"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo161fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo161en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Distribution of population aged 10 and over, disaggregated by ability to work, urban and rural area"

  [[resources.title]]
  lang = "fa"
  text = "توزیع جمعیت ۱۰ ساله و بیش‌تر بر حسب وضع فعالیت در نقاط شهری و روستایی"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/census/1385/results/country_1385_general.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = ""
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "10 year old population (1000 people)"
      type = "string"

      [[resources.schema.fields]]
      name = "Active (percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "Inactive (percentage)"
      type = "string"


