name = "scipo172"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1335, 1390] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["The country population"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت کشور"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/2865/jamiat_keshvar.xls"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Country's population from 1335 to 1390" 

[[title]]
lang = "fa"
text = "جمعيت كشور از سال ۱۳۳۵ تا ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است. این جدول شامل جمعیت در سال‌های ۱۳۳۵، ۱۳۴۵، ۱۳۵۵، ۱۳۶۵، ۱۳۷۵، ۱۳۸۵ و ۱۳۹۰ است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran. This table contains the population in the years 1335, 1345, 1355, 1365, 1375, 1385 and 1390."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo172fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo172en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Country's population from 1335 to 1390"

  [[resources.title]]
  lang = "fa"
  text = "جمعيت كشور از سال ۱۳۳۵ تا ۱۳۹۰"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/2865/jamiat_keshvar.xls" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description/Year"
      type = "string"

      [[resources.schema.fields]]
      name = "1335"
      type = "string"

      [[resources.schema.fields]]
      name = "1345"
      type = "string"

      [[resources.schema.fields]]
      name = "1355"
      type = "string"

      [[resources.schema.fields]]
      name = "1365"
      type = "string"

      [[resources.schema.fields]]
      name = "1375"
      type = "string"

      [[resources.schema.fields]]
      name = "1385"
      type = "string"


