name = "scipo161"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1365, 1385] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["population"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت", "فعال", "شهری", "روستایی"]

[author]
web = "https://drive.google.com/open?id=0B4viFwPm8_QKWHpvUFR6aXhmbGs"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "test"

[[title]]
lang = "en" 
text = "test" 

[[title]]
lang = "fa"
text = "توزیع جمعیت ۱۰ ساله و بیش‌تر بر حسب وضع فعالیت در نقاط شهری و روستایی"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۲-۱ از نتایج کلی سرشماری عمومی نفوس و مسکن ۱۳۸۵ استخراج شده است."

[[description]]
lang = "en"
text = ""

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo161fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo161en.csv"

  [[resources.title]]
  lang = "en" 
  text = ""

  [[resources.title]]
  lang = "fa"
  text = "توزیع جمعیت ۱۰ ساله و بیش‌تر بر حسب وضع فعالیت در نقاط شهری و روستایی"

  [[resources.sources]]
  name = "" 
  web = "https://drive.google.com/open?id=0B4viFwPm8_QKWHpvUFR6aXhmbGs" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = ""
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "10 year old population (1000 people)"
      type = "string"

      [[resources.schema.fields]]
      name = "Active (percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "Inactive (percentage)"
      type = "string"


