name = "scipo1716"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1393, 1393] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Area of the province", "Number of counties", "Number of districts", "Number of cities", "Number of rural districts", "Number of villages"]

[[keywords]]
lang = "fa" 
wordlist = ["مساحت استان‌ها", "تعداد شهرستان‌ها", "تعداد بخش‌ها", "تعداد شهر‌ها", "تعداد دهستان‌ها", "تعداد آبادی‌ها"]

[author]
web = "https://www.amar.org.ir/%D8%B5%D9%81%D8%AD%D8%A7%D8%AA-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86%DB%8C/%D8%A7%D8%B3%D8%AA%D8%A7%D9%86-%D9%87%D8%A7-%D8%AF%D8%B1-%DB%8C%DA%A9-%D9%86%DA%AF%D8%A7%D9%87"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Provinces information based on administrative divisions of Iran in year 1393" 

[[title]]
lang = "fa"
text = "اطلاعات استانی براساس تقسیمات کشوری سال ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of Statistical Centre of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1716fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1716en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Provinces information based on administrative divisions of Iran in year 1393"

  [[resources.title]]
  lang = "fa"
  text = "اطلاعات استانی براساس تقسیمات کشوری سال ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/%D8%B5%D9%81%D8%AD%D8%A7%D8%AA-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86%DB%8C/%D8%A7%D8%B3%D8%AA%D8%A7%D9%86-%D9%87%D8%A7-%D8%AF%D8%B1-%DB%8C%DA%A9-%D9%86%DA%AF%D8%A7%D9%87" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Provinces"
      type = "string"

      [[resources.schema.fields]]
      name = "Area (Km2)"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of county"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of district"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of city"
      type = "string"

      [[resources.schema.fields]]
      name = "Number of rural district"
      type = "string"


