name = "scipo1710"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1335, 1390] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["The number of people in the household"]

[[keywords]]
lang = "fa" 
wordlist = ["تعداد افراد در خانوار"]

[author]
web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/2876/motevaset_tedad_khanevar.xls"

  [[author.name]] 
  lang = "fa"
  text = "مرکزآمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The average household size in the country (family size) from 1335 to 1390" 

[[title]]
lang = "fa"
text = "متوسط تعداد افراد در خانوار کشور (بعد خانوار) از سال ۱۳۳۵ تا ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده، نسخه‌ی تمیز شده‌ی فایل منتشر شده‌ی مرکز آمار ایران است."

[[description]]
lang = "en"
text = "Dataset cleaned from an Excel file published by the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1710fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1710en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The average household size in the country (family size) from 1335 to 1390"

  [[resources.title]]
  lang = "fa"
  text = "متوسط تعداد افراد در خانوار کشور (بعد خانوار) از سال ۱۳۳۵ تا ۱۳۹۰"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://www.amar.org.ir/Portals/0/PropertyAgent/461/Files/2876/motevaset_tedad_khanevar.xls" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description (Person)"
      type = "string"

      [[resources.schema.fields]]
      name = "1335"
      type = "string"

      [[resources.schema.fields]]
      name = "1345"
      type = "string"

      [[resources.schema.fields]]
      name = "1355"
      type = "string"

      [[resources.schema.fields]]
      name = "1365"
      type = "string"

      [[resources.schema.fields]]
      name = "1370"
      type = "string"

      [[resources.schema.fields]]
      name = "1375"
      type = "string"

      [[resources.schema.fields]]
      name = "1385"
      type = "string"


