name = "scipo1719"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1345 ,  1390] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["country divisions", "county", "district", "rural district", "city"]

[[keywords]]
lang = "fa" 
wordlist = ["تقسیمات کشوری", "شهرستان", "بخش", "دهستان", "شهر "]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/جمعیت#48524---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The number of county, district, city and rural districts according to country divisions from 1345 to 1390" 

[[title]]
lang = "fa"
text = "تعداد شهرستان، بخش، شهر و دهستان بر اساس تقسيمات كشوری از سال ۱۳۴۵ تا ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل تعداد شهرستان، بخش، شهر و دهستان بر اساس تقسيمات كشوری گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, The number of county, district, city and rural districts according to country divisions file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1719fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo1719en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The number of county, district, city and rural districts according to country divisions from 1345 to 1390"

  [[resources.title]]
  lang = "fa"
  text = "تعداد شهرستان، بخش، شهر و دهستان بر اساس تقسيمات كشوری از سال ۱۳۴۵ تا ۱۳۹۰"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/جمعیت#48524---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Description"
      type = "string"

      [[resources.schema.fields]]
      name = "1345"
      type = "string"

      [[resources.schema.fields]]
      name = "1346"
      type = "string"

      [[resources.schema.fields]]
      name = "1347"
      type = "string"

      [[resources.schema.fields]]
      name = "1348"
      type = "string"

      [[resources.schema.fields]]
      name = "1349"
      type = "string"

      [[resources.schema.fields]]
      name = "1350"
      type = "string"

      [[resources.schema.fields]]
      name = "1351"
      type = "string"

      [[resources.schema.fields]]
      name = "1352"
      type = "string"

      [[resources.schema.fields]]
      name = "1353"
      type = "string"

      [[resources.schema.fields]]
      name = "1354"
      type = "string"

      [[resources.schema.fields]]
      name = "1355"
      type = "string"

      [[resources.schema.fields]]
      name = "1356"
      type = "string"

      [[resources.schema.fields]]
      name = "1357"
      type = "string"

      [[resources.schema.fields]]
      name = "1358"
      type = "string"

      [[resources.schema.fields]]
      name = "1359"
      type = "string"

      [[resources.schema.fields]]
      name = "1360"
      type = "string"

      [[resources.schema.fields]]
      name = "1361"
      type = "string"

      [[resources.schema.fields]]
      name = "1362"
      type = "string"

      [[resources.schema.fields]]
      name = "1363"
      type = "string"

      [[resources.schema.fields]]
      name = "1364"
      type = "string"

      [[resources.schema.fields]]
      name = "1365"
      type = "string"

      [[resources.schema.fields]]
      name = "1366"
      type = "string"

      [[resources.schema.fields]]
      name = "1367"
      type = "string"

      [[resources.schema.fields]]
      name = "1368"
      type = "string"

      [[resources.schema.fields]]
      name = "1369"
      type = "string"

      [[resources.schema.fields]]
      name = "1370"
      type = "string"

      [[resources.schema.fields]]
      name = "1371"
      type = "string"

      [[resources.schema.fields]]
      name = "1372"
      type = "string"

      [[resources.schema.fields]]
      name = "1373"
      type = "string"

      [[resources.schema.fields]]
      name = "1374"
      type = "string"

      [[resources.schema.fields]]
      name = "1375"
      type = "string"

      [[resources.schema.fields]]
      name = "1376"
      type = "string"

      [[resources.schema.fields]]
      name = "1377"
      type = "string"

      [[resources.schema.fields]]
      name = "1378"
      type = "string"

      [[resources.schema.fields]]
      name = "1379"
      type = "string"

      [[resources.schema.fields]]
      name = "1380"
      type = "string"

      [[resources.schema.fields]]
      name = "1381"
      type = "string"

      [[resources.schema.fields]]
      name = "1382"
      type = "string"

      [[resources.schema.fields]]
      name = "1383"
      type = "string"

      [[resources.schema.fields]]
      name = "1384"
      type = "string"

      [[resources.schema.fields]]
      name = "1385"
      type = "string"


