name = "scipo164"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1335, 1385] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["population", "urban area", "rural area"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت", "شهری", "روستایی"]

[author]
web = "https://www.amar.org.ir/Portals/0/census/1385/results/country_1385_general.pdf"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Population indicators, disaggregated by rural/urban area between 1335 and 1385" 

[[title]]
lang = "fa"
text = "گزیده شاخص‌های جمعیتی کشور برحسب نقاط شهری و روستایی از ۱۳۳۵ تا ۱۳۸۵"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۵-۱ از نتایج کلی سرشماری عمومی نفوس و مسکن ۱۳۸۵ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 1-5 of the 1385 General Census of Population and Housing"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo164fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo164en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Population indicators, disaggregated by rural/urban area between 1335 and 1385"

  [[resources.title]]
  lang = "fa"
  text = "گزیده شاخص‌های جمعیتی کشور برحسب نقاط شهری و روستایی طی سال‌های ۱۳۳۵-۱۳۸۵"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/census/1385/results/country_1385_general.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Male and female population – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Male population (% of total) – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Female population (% of total) – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Sex ratio – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Household – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Average household size – whole country"
      type = "string"

      [[resources.schema.fields]]
      name = "Male and female population – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Male population (% of total) – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Female population (% of total) – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Sex ratio – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Household – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Average household size – urban area"
      type = "string"

      [[resources.schema.fields]]
      name = "Male and female population – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Male population (% of total) – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Female population (% of total) – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Sex ratio – rural area"
      type = "string"

      [[resources.schema.fields]]
      name = "Household – rural area"
      type = "string"


