name = "scipo162fa"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1365, 1385] 
category= ["population", "employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["emplyment", "unemplyment"]

[[keywords]]
lang = "fa" 
wordlist = [ "بیکاری", "شهری", "روستایی", "اشتغال"]

[author]
web = "https://www.amar.org.ir/%D8%AE%D8%A7%D9%86%D9%87/%D8%B5%D9%81%D8%AD%D9%87-%D8%A7%D8%B5%D9%84%DB%8C-%D9%81%D8%B1%D9%88%D8%B4%DA%AF%D8%A7%D9%87-%D9%85%D8%AC%D8%A7%D8%B2%D9%8A/ProdID/83"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Employment data, disaggregated by rural/urban (1365 - 1385)" 

[[title]]
lang = "fa"
text = "توزیع جمعیت فعال ۱۰ ساله و بیش‌تر بر حسب شاغل و بیکار در نقاط شهری و روستایی "

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۳-۱ از نتایج کلی سرشماری عمومی نفوس و مسکن ۱۳۸۵ استخراج شده است."

[[description]]
lang = "en"
text = ""

[[resources]]

  url = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo162fa.csv"

  [[resources.title]]
  lang = "en" 
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/%D8%AE%D8%A7%D9%86%D9%87/%D8%B5%D9%81%D8%AD%D9%87-%D8%A7%D8%B5%D9%84%DB%8C-%D9%81%D8%B1%D9%88%D8%B4%DA%AF%D8%A7%D9%87-%D9%85%D8%AC%D8%A7%D8%B2%D9%8A/ProdID/83" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Field_name"
      type = "string"
