name = "scipo161"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1365, 1385] 
frequency = "yearly"
category= [population ]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = [<WORD_LIST_EN>]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت", "فعال", "شهری", "روستایی"]

[author]
web = "https://drive.google.com/open?id=0B4viFwPm8_QKWHpvUFR6aXhmbGs"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "<AUTHOR_EN>"

[[title]]
lang = "en" 
text = "<TITLE_EN>" 

[[title]]
lang = "fa"
text = "توزیع جمعیت ۱۰ ساله و بیش‌تر بر حسب وضع فعالیت در نقاط شهری و روستایی"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۲-۱ از نتایج کلی سرشماری عمومی نفوس و مسکن ۱۳۸۵ استخراج شده است."

[[description]]
lang = "en"
text = ""

[[resources]]

  url = ""

  [[resources.title]]
  lang = "en" 
  text = "Database"

  [[resources.title]]
  lang = "fa"
  text = "Database"

  [[resources.sources]]
  name = "<SOURCE_NAME>" 
  web = "https://drive.google.com/open?id=0B4viFwPm8_QKWHpvUFR6aXhmbGs" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Field_name"
      type = "string"
