name = "scipo167"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385, 1395] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["The country population", "Population by province"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت کشور", "جمعیت استان"]

[author]
web = "https://www.amar.org.ir/Portals/0/Files/baravord/b_ostani_85-95.xls"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Estimated and projected population of province and urban and rural areas from 1385 to 1395" 

[[title]]
lang = "fa"
text = "برآورد و پیش‌بینی جمعیت کشور به تفکیک استان و مناطق شهری و روستایی از سال ۱۳۸۵ تا ۱۳۹۵"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo167fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo167en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Estimated and projected population of province and urban and rural areas from 1385 to 1395"

  [[resources.title]]
  lang = "fa"
  text = "برآورد و پیش‌بینی جمعیت کشور به تفکیک استان و مناطق شهری و روستایی از سال ۱۳۸۵ تا ۱۳۹۵"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/Files/baravord/b_ostani_85-95.xls" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province (Digits in thousands)ی"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "All 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban 1395"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1385"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1386"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1387"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1389"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1390"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1393"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural and nonresident 1394"
      type = "string"


