name = "scipo166"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385 ,  1390] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["The unemployment rate", "population growth rate", "Economic participation rate by province", "Population by province"]

[[keywords]]
lang = "fa" 
wordlist = ["نرخ بیکاری", "نرخ رشد جمعیت", "نرخ مشارکت اقتصادی استان", "جمعیت استان"]

[author]
web = "https://www.amar.org.ir/%D8%B5%D9%81%D8%AD%D8%A7%D8%AA-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86%DB%8C/%D8%B4%D8%A7%D8%AE%D8%B5-%D9%87%D8%A7%DB%8C-%DA%A9%D9%84%DB%8C%D8%AF%DB%8C-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86-%D9%87%D8%A7"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The population growth rate from 1385 to 1390 broken down by province" 

[[title]]
lang = "fa"
text = "نرخ رشد جمعیت به تفکیک استان از سال ۱۳۸۵ تا ۱۳۹۰"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo166fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo166en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The population growth rate from 1385 to 1390 broken down by province"

  [[resources.title]]
  lang = "fa"
  text = "نرخ رشد جمعیت به تفکیک استان از سال ۱۳۸۵ تا ۱۳۹۰"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/%D8%B5%D9%81%D8%AD%D8%A7%D8%AA-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86%DB%8C/%D8%B4%D8%A7%D8%AE%D8%B5-%D9%87%D8%A7%DB%8C-%DA%A9%D9%84%DB%8C%D8%AF%DB%8C-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86-%D9%87%D8%A7" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Province"
      type = "string"

      [[resources.schema.fields]]
      name = "Population"
      type = "string"

      [[resources.schema.fields]]
      name = "Population growth rate"
      type = "string"

      [[resources.schema.fields]]
      name = "The unemployment rate"
      type = "string"

      [[resources.schema.fields]]
      name = "Economic participation rate"
      type = "string"

      [[resources.schema.fields]]
      name = "Literacy rate"
      type = "string"


