name = "scipo165"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [, ] 
category= ["population"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["household", "population", "urban area", "rural area"]

[[keywords]]
lang = "fa" 
wordlist = ["خانوار", "جمعیت", "شهری", "روستایی"]

[author]
web = "http://nnt.sci.org.ir/sites/Apps/yearbook/Lists/year_book_req/Item/newifs.aspx?List=97c00882-734c-4417-831a-633d795b18ce&RootFolder=&Web=f9aca984-16ee-4860-8c00-bb43c696d32d"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Household and population of Tehran's province, disaggregated by residency" 

[[title]]
lang = "fa"
text = "خانوار و جمعیت شهرستان‌های استان تهران بر حسب ساکن و غیرساکن (1390)"

[[description]]
lang = "fa"
text = "این داده از جدول ۲-۶ صفحه ۲۳ از سالنامه آماری استان تهران ۱۳۹۳ تهیه شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 2-6, page 23, of the 1393 Statistical Yearbook"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo165fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/po%20/scipo165en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Household and population of Tehran's province, disaggregated by residency"

  [[resources.title]]
  lang = "fa"
  text = "خانوار و جمعیت شهرستان‌های استان تهران بر حسب ساکن و غیرساکن (1390)"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "http://nnt.sci.org.ir/sites/Apps/yearbook/Lists/year_book_req/Item/newifs.aspx?List=97c00882-734c-4417-831a-633d795b18ce&RootFolder=&Web=f9aca984-16ee-4860-8c00-bb43c696d32d" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = ""
      type = "string"

      [[resources.schema.fields]]
      name = "Total households"
      type = "string"

      [[resources.schema.fields]]
      name = "Total population"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area - resident households"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – resident population"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – resident households"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area – resident population"
      type = "string"

      [[resources.schema.fields]]
      name = "Non-resident households"
      type = "string"


