name = "scipo162"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1365, 1385] 
category= ["population", "employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = []

[[keywords]]
lang = "fa" 
wordlist = ["شاغل", "بیکار", "بیکاری", "شهری", "روستایی", "اشتغال"]

[author]
web = "https://drive.google.com/open?id=0B4viFwPm8_QKWHpvUFR6aXhmbGs"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = ""

[[title]]
lang = "en" 
text = "" 

[[title]]
lang = "fa"
text = "توزیع جمعیت فعال ۱۰ ساله و بیش‌تر بر حسب شاغل و بیکار در نقاط شهری و روستایی"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۳-۱ از نتایج کلی سرشماری عمومی نفوس و مسکن ۱۳۸۵ استخراج شده است."

[[description]]
lang = "en"
text = ""

[[resources]]

  [[url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo162fa.csv" 

  [[url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo162en.csv"

  [[resources.title]]
  lang = "en" 
  text = ""

  [[resources.title]]
  lang = "fa"
  text = "توزیع جمعیت فعال ۱۰ ساله و بیش‌تر بر حسب شاغل و بیکار در نقاط شهری و روستایی"

  [[resources.sources]]
  name = "" 
  web = "https://drive.google.com/open?id=0B4viFwPm8_QKWHpvUFR6aXhmbGs" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = ""
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Ten year old population (1000 people)"
      type = "string"

      [[resources.schema.fields]]
      name = "Employed (percentage)"
      type = "string"


