name = "scipo162"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1365, 1385] 
category= ["population", "employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["occupation" , "unemployment" , "urban area" , "rural area"]

[[keywords]]
lang = "fa" 
wordlist = ["شاغل", "بیکار", "بیکاری", "شهری", "روستایی", "اشتغال"]

[author]
web = "https://drive.google.com/open?id=0B4viFwPm8_QKWHpvUFR6aXhmbGs"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "Distribution of population aged 10 and over, disaggregated by occupation, urban and rural area" 

[[title]]
lang = "fa"
text = "توزیع جمعیت فعال ۱۰ ساله و بیش‌تر بر حسب شاغل و بیکار در نقاط شهری و روستایی"

[[description]]
lang = "fa"
text = "این داده از جدول شماره ۲۳-۱ از نتایج کلی سرشماری عمومی نفوس و مسکن ۱۳۸۵ استخراج شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 1-23 of the 1385 General Census of Population and Housing."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo162fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/nocrd1693/scipo162en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Distribution of population aged 10 and over, disaggregated by occupation, urban and rural area"

  [[resources.title]]
  lang = "fa"
  text = "توزیع جمعیت فعال ۱۰ ساله و بیش‌تر بر حسب شاغل و بیکار در نقاط شهری و روستایی"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/Portals/0/census/1385/results/country_1385_general.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country -Ten year old population (1000 people)"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country - Employed (percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "Whole country – Unemployed (percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area -Ten year old population (1000 people)"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area - Employed (percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – Unemployed (percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area -Ten year old population (1000 people)"
      type = "string"

      [[resources.schema.fields]]
      name = "Rural area - Employed (percentage)"
      type = "string"


