name = "scitn171"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1385 ,  1393] 
category= ["transport", "population", "health"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["all accidents", "fatal accidents", "accidents leading to injury", "accidents resulting in damage", "accidents within the city", "suburban accidents"]

[[keywords]]
lang = "fa" 
wordlist = ["کل تصادفات", "تصادفات منجر به فوت", "تصادفات منجر به جرح", "تصادفات منجر به خسارت", "تصادفات درون شهری", "تصادفات برون شهری"]

[author]
web = "https://www.amar.org.ir/آمارهای-موضوعی/حمل-و-نقل-انبارداری-و-ارتباطات#48735---"

  [[author.name]] 
  lang = "fa"
  text = "مرکز آمار ایران"

  [[author.name]]
  lang = "en"
  text = "Statistical Centre of Iran"

[[title]]
lang = "en" 
text = "The number of accidents and casualties vehicle resulting in death, injury and damage to the road transport from 1385 to 1393" 

[[title]]
lang = "fa"
text = "تعداد تصادفات و تلفات انسانی وسايل نقليه منجر به فوت، جرح و خسارت در حمل و نقل جاده‌ای از سال ۱۳۸۵ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی مرکز آمار ایران، فایل تعداد تصادفات و تلفات انسانی وسايل نقليه منجر به فوت، جرح و خسارت در حمل و نقل جاده‌ای گرفته شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from the official website of the Statistical Center of Iran, number of accidents and casualties vehicle resulting in death, injury and damage in road transport file."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/tn/scitn171fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/tn/scitn171en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The number of accidents and casualties vehicle resulting in death, injury and damage to the road transport from 1385 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "تعداد تصادفات و تلفات انسانی وسايل نقليه منجر به فوت، جرح و خسارت در حمل و نقل جاده‌ای از سال ۱۳۸۵ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Statistical Centre of Iran" 
  web = "https://www.amar.org.ir/آمارهای-موضوعی/حمل-و-نقل-انبارداری-و-ارتباطات#48735---" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - all accidents"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - deaths - number of accidents (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "All – result to death – number of death"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - leading to injury - the number of accidents (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - leading to injury - the number of injured"
      type = "string"

      [[resources.schema.fields]]
      name = "Total - leads to damage (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area - all accidents"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – result to deaths - number of accidents (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area – result to death – number of death"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area - leading to injury - the number of accidents (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area - leading to injury - the number of injured"
      type = "string"

      [[resources.schema.fields]]
      name = "Urban area - leads to damage (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "Suburban area - all accidents"
      type = "string"

      [[resources.schema.fields]]
      name = "Suburban area – result to deaths - number of accidents (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "Suburban area – result to death – number of death"
      type = "string"

      [[resources.schema.fields]]
      name = "Suburban area - leading to injury - the number of accidents (counts)"
      type = "string"

      [[resources.schema.fields]]
      name = "Suburban area - leading to injury - the number of injured"
      type = "string"


