name = "smbgs1748-shiraz_municipality_annual_budget-1394"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["budget and government spending"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Shiraz", "budget", "municipality"]

[[keywords]]
lang = "fa" 
wordlist = ["شیراز", "بودجه", "شهرداری"]

[author]
web = "http://www.shiraz.ir/bundles/FileRepository/279/cat9793/587b3c3791ae7.pdf"

  [[author.name]] 
  lang = "fa"
  text = "شهرداری شیراز"

  [[author.name]]
  lang = "en"
  text = "Shiraz municipality"

[[title]]
lang = "en" 
text = "Determining the current and developmental contribution of revenues and resources of Shiraz municipality in 1394" 

[[title]]
lang = "fa"
text = "تعیین سهم اعتبارات جاری و عمرانی از درآمدها و منابع تامین اعتبار شهرداری شیراز سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از جدول ۲-۴ صفحه ۲۵ تا ۲۹ گزارش بودجه مصوب سال ۱۳۹۴ شهرداری شیراز گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from table 4-2 on pages 25 to 29, the Shiraz municipality approved annual budget report for 1394"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/smbgs1748-shiraz_municipality_annual_budget-1394-fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bgs/smbgs1748-shiraz_municipality_annual_budget-1394-en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Determining the current and developmental contribution of revenues and resources of Shiraz municipality in 1394"

  [[resources.title]]
  lang = "fa"
  text = "تعیین سهم اعتبارات جاری و عمرانی از درآمدها و منابع تامین اعتبار شهرداری شیراز سال ۱۳۹۴"

  [[resources.sources]]
  name = "Shiraz municipality" 
  web = "http://www.shiraz.ir/bundles/FileRepository/279/cat9793/587b3c3791ae7.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "code"
      type = "string"

      [[resources.schema.fields]]
      name = "description"
      type = "string"

      [[resources.schema.fields]]
      name = "total credit (thousand IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "current credits – share (percentage)"
      type = "string"

      [[resources.schema.fields]]
      name = "current credits – amount (thousand IRR)"
      type = "string"

      [[resources.schema.fields]]
      name = "development credits – share (percentage)"
      type = "string"


