name = "tpotd179"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1393] 
category= ["trade", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Imports", "Imported principles", "Foreign business", "Foreign Trade"]

[[keywords]]
lang = "fa" 
wordlist = ["وادرات", "مبادی وارداتی", "تجارت خارجی", "بازرگانی خارجی"]

[author]
web = "http://www.tpo.ir/uploads/amalkarde-12-mahe_9363.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان توسعه تجارت ایران"

  [[author.name]]
  lang = "en"
  text = "Trade Promotion Organization of Iran"

[[title]]
lang = "en" 
text = "The number of items and the countries of imported goods during 1384 to 1393" 

[[title]]
lang = "fa"
text = "تعداد اقلام و مبادی وارداتی طی سال‌های ۱۳۸۴ تا ۱۳۹۳"

[[description]]
lang = "fa"
text = "این داده از صفحه ۱۵، گزارش عملکرد تجارت خارجی کشور سال ۱۳۹۳، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from page 15, Report of country's foreign trade performance in 1393."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd179fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd179en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The number of items and the countries of imported goods during 1384 to 1393"

  [[resources.title]]
  lang = "fa"
  text = "تعداد اقلام و مبادی وارداتی طی سال‌های ۱۳۸۴ تا ۱۳۹۳"

  [[resources.sources]]
  name = "Trade Promotion Organization of Iran" 
  web = "http://www.tpo.ir/uploads/amalkarde-12-mahe_9363.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "1384"
      type = "string"

      [[resources.schema.fields]]
      name = "1385"
      type = "string"

      [[resources.schema.fields]]
      name = "1386"
      type = "string"

      [[resources.schema.fields]]
      name = "1387"
      type = "string"

      [[resources.schema.fields]]
      name = "1388"
      type = "string"

      [[resources.schema.fields]]
      name = "1389"
      type = "string"

      [[resources.schema.fields]]
      name = "1390"
      type = "string"

      [[resources.schema.fields]]
      name = "1391"
      type = "string"

      [[resources.schema.fields]]
      name = "1392"
      type = "string"


