name = "tpotd172"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["trade", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Imports", "Imported principles", "Foreign business", "Foreign Trade"]

[[keywords]]
lang = "fa" 
wordlist = ["وادرات", "مبادی وارداتی", "تجارت خارجی", "بازرگانی خارجی"]

[author]
web = "http://www.tpo.ir/uploads/amalkarde-tejarat-khareji-12mahe94_16341.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان توسعه تجارت ایران"

  [[author.name]]
  lang = "en"
  text = "Trade Promotion Organization of Iran"

[[title]]
lang = "en" 
text = "Ten main items imported in 1394" 

[[title]]
lang = "fa"
text = "ده قلم عمده وارداتی در سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحه ۱۳، گزارش عملکرد تجارت خارجی کشور سال ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from page 13, Report of country's foreign trade performance in 1394."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd172fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd172en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Ten main items imported in 1394"

  [[resources.title]]
  lang = "fa"
  text = "ده قلم عمده وارداتی در سال ۱۳۹۴"

  [[resources.sources]]
  name = "Trade Promotion Organization of Iran" 
  web = "http://www.tpo.ir/uploads/amalkarde-tejarat-khareji-12mahe94_16341.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Rating in 1394"
      type = "string"

      [[resources.schema.fields]]
      name = "Good’s Caption"
      type = "string"

      [[resources.schema.fields]]
      name = "The value of imports in 1394 (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Percentage of value of total imports"
      type = "string"

      [[resources.schema.fields]]
      name = "Base price (dollars per ton)"
      type = "string"

      [[resources.schema.fields]]
      name = "Percentage ratio compared to the 1393 base price"
      type = "string"


