name = "tpotd1717"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1392, 1392] 
category= ["trade", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Imports", "Imported principles", "Foreign business", "Foreign Trade"]

[[keywords]]
lang = "fa" 
wordlist = ["وادرات", "مبادی وارداتی", "تجارت خارجی", "بازرگانی خارجی"]

[author]
web = "http://www.tpo.ir/uploads/modiranarshad-12mah-92_3536.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان توسعه تجارت ایران"

  [[author.name]]
  lang = "en"
  text = "Trade Promotion Organization of Iran"

[[title]]
lang = "en" 
text = "The main countries of imports in year 1392" 

[[title]]
lang = "fa"
text = "مهمترین مبادی وارداتی سال ۱۳۹۲"

[[description]]
lang = "fa"
text = "این داده از صفحه ۲۲، گزارش عملکرد تجارت خارجی کشور سال ۱۳۹۲، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from page 22, Report of country's foreign trade performance in 1392."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd1717fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd1717en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The main countries of imports in year 1392"

  [[resources.title]]
  lang = "fa"
  text = "مهمترین مبادی وارداتی سال ۱۳۹۲"

  [[resources.sources]]
  name = "Trade Promotion Organization of Iran" 
  web = "http://www.tpo.ir/uploads/modiranarshad-12mah-92_3536.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Rating in 1392"
      type = "string"

      [[resources.schema.fields]]
      name = "Country’s name"
      type = "string"

      [[resources.schema.fields]]
      name = "The value of imports in 1392 (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Percentage of value of total imports"
      type = "string"

      [[resources.schema.fields]]
      name = "Percentage ratio of values in comparison with 1391"
      type = "string"


