name = "tpotd1744"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1388, 1388] 
category= ["trade"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["business partners", "10 nusiness partner", "non-oil exports", "Importation"]

[[keywords]]
lang = "fa" 
wordlist = ["شرکای تجاری", "۱۰ شریک تجاری", "صادرات غیرنفتی", "واردات"]

[author]
web = "http://www.tpo.ir/uploads/modiran_arshad_88_5121.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان توسعه تجارت ایران"

  [[author.name]]
  lang = "en"
  text = "Trade Promotion Organization of Iran"

[[title]]
lang = "en" 
text = "Iran's largest trading partners in terms of import value in 1388" 

[[title]]
lang = "fa"
text = "بزرگترین شرکای تجاری ایران از لحاظ ارزش واردات درسال  ۱۳۸۸"

[[description]]
lang = "fa"
text = "این داده از صفحه ۲۶، گزارش مدیران ارشد سال ۱۳۸۸، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from page 26, Senior managers expert reports in 1388."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd1744fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd1744en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Iran's largest trading partners in terms of import value in 1388"

  [[resources.title]]
  lang = "fa"
  text = "بزرگترین شرکای تجاری ایران از لحاظ ارزش واردات درسال  ۱۳۸۸"

  [[resources.sources]]
  name = "Trade Promotion Organization of Iran" 
  web = "http://www.tpo.ir/uploads/modiran_arshad_88_5121.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Rating in 1388"
      type = "string"

      [[resources.schema.fields]]
      name = "Country Name"
      type = "string"

      [[resources.schema.fields]]
      name = "The value of imports in 1388 - million dollars"
      type = "string"

      [[resources.schema.fields]]
      name = "Percentage of value of total imports"
      type = "string"

      [[resources.schema.fields]]
      name = "Value changes percentage comparing to 1387"
      type = "string"


