name = "tpotd176"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1384, 1394] 
category= ["trade", "economics", "energy"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Imports", "Imported principles", "Foreign business", "Foreign Trade"]

[[keywords]]
lang = "fa" 
wordlist = ["وادرات", "مبادی وارداتی", "تجارت خارجی", "بازرگانی خارجی"]

[author]
web = "http://www.tpo.ir/uploads/amalkarde-tejarat-khareji-12mahe94_16341.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان توسعه تجارت ایران"

  [[author.name]]
  lang = "en"
  text = "Trade Promotion Organization of Iran"

[[title]]
lang = "en" 
text = "Import and export ratios during 1384 to 1394" 

[[title]]
lang = "fa"
text = "نسبت‌های صادرات و واردات در سال‌های ۱۳۸۴ تا ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحه ۲۲، گزارش عملکرد تجارت خارجی کشور سال ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from page 22, Report of country's foreign trade performance in 1394."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd176fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd176en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Import and export ratios during 1384 to 1394"

  [[resources.title]]
  lang = "fa"
  text = "نسبت‌های صادرات و واردات طی سال‌های ۱۳۸۴ تا ۱۳۹۴"

  [[resources.sources]]
  name = "Trade Promotion Organization of Iran" 
  web = "http://www.tpo.ir/uploads/amalkarde-tejarat-khareji-12mahe94_16341.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year"
      type = "string"

      [[resources.schema.fields]]
      name = "The ratio of non-oil exports to imports (without gas condensate)"
      type = "string"

      [[resources.schema.fields]]
      name = "The ratio of non-oil exports to imports (with gas condensate)"
      type = "string"

      [[resources.schema.fields]]
      name = "The ratio of imports to non-oil exports (without gas condensate)"
      type = "string"


