name = "tpotd1721"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1391, 1391] 
category= ["trade", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Imports", "Imported principles", "Foreign business", "Foreign Trade"]

[[keywords]]
lang = "fa" 
wordlist = ["وادرات", "مبادی وارداتی", "تجارت خارجی", "بازرگانی خارجی"]

[author]
web = "http://www.tpo.ir/uploads/modiran_arshad_91_5118.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان توسعه تجارت ایران"

  [[author.name]]
  lang = "en"
  text = "Trade Promotion Organization of Iran"

[[title]]
lang = "en" 
text = "The main countries of imports in year 1391" 

[[title]]
lang = "fa"
text = "مهمترین مبادی وارداتی سال ۱۳۹۱"

[[description]]
lang = "fa"
text = "این داده از صفحه ۲۷، گزارش مدیران ارشد بر اساس آمار کارشناسی نشده گمرک سال ۱۳۹۱، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from page 27, Senior managers expert reports based on non experts customs statistics in 1391."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd1721fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd1721en.csv"

  [[resources.title]]
  lang = "en" 
  text = "The main countries of imports in year 1391"

  [[resources.title]]
  lang = "fa"
  text = "مهمترین مبادی وارداتی سال ۱۳۹۱"

  [[resources.sources]]
  name = "Trade Promotion Organization of Iran" 
  web = "http://www.tpo.ir/uploads/modiran_arshad_91_5118.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Rating in 1391"
      type = "string"

      [[resources.schema.fields]]
      name = "Country’s name"
      type = "string"

      [[resources.schema.fields]]
      name = "The value of imports in 1391 (million dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Percentage of value of total imports"
      type = "string"

      [[resources.schema.fields]]
      name = "Percentage ratio of values in comparison with 1390"
      type = "string"


