name = "tpotd171"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1394, 1394] 
category= ["trade", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["Imports", "Imported principles", "Foreign business", "Foreign Trade"]

[[keywords]]
lang = "fa" 
wordlist = ["وادرات", "مبادی وارداتی", "تجارت خارجی", "بازرگانی خارجی"]

[author]
web = "http://www.tpo.ir/uploads/amalkarde-tejarat-khareji-12mahe94_16341.pdf"

  [[author.name]] 
  lang = "fa"
  text = "سازمان توسعه تجارت ایران"

  [[author.name]]
  lang = "en"
  text = "Trade Promotion Organization of Iran"

[[title]]
lang = "en" 
text = "Import of goods statistics in 1394" 

[[title]]
lang = "fa"
text = "آمار واردات کالا طی سال ۱۳۹۴"

[[description]]
lang = "fa"
text = "این داده از صفحه ۱۲، گزارش عملکرد تجارت خارجی کشور سال ۱۳۹۴، استخراج شده است."

[[description]]
lang = "en"
text = "Dataset exctracted from page 12, Report of country's foreign trade performance in 1394."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd171fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/td/tpotd171en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Import of goods statistics in 1394"

  [[resources.title]]
  lang = "fa"
  text = "آمار واردات کالا طی سال ۱۳۹۴"

  [[resources.sources]]
  name = "Trade Promotion Organization of Iran" 
  web = "http://www.tpo.ir/uploads/amalkarde-tejarat-khareji-12mahe94_16341.pdf" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Year 1394 - Weight (thousands tons)"
      type = "string"

      [[resources.schema.fields]]
      name = "Year 1394 - Value (millions of dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Year 1393 - Weight (thousands tons)"
      type = "string"

      [[resources.schema.fields]]
      name = "Year 1393 - Value (millions of dollars)"
      type = "string"

      [[resources.schema.fields]]
      name = "Ratio percentage - Weight (thousands tons)"
      type = "string"


