name = "tsetmcbf1724-list_saman_bank_shareholders-1396"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1396, 1396] 
category= ["banking", "economics"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["bank", "banking", "share", "shareholders", "stock", "credit union", "Saman bank"]

[[keywords]]
lang = "fa" 
wordlist = ["بانک", "بانکداری", "سهام", "سهامداران", "بورس", "موسسات اعتباری", "بانک سامان"]

[author]
web = "http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=38179358042686391#"

  [[author.name]] 
  lang = "fa"
  text = "بورس اوراق بهادار تهران"

  [[author.name]]
  lang = "en"
  text = "Tehran Securities Exchange Technology Management Company"

[[title]]
lang = "en" 
text = "List of sharholders for Saman bank in 1396" 

[[title]]
lang = "fa"
text = "فهرست سهامداران بانک سامان در سال ۱۳۹۶"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی شرکت مدیریت فناوری بورس تهران گرفته‌ شده‌است."

[[description]]
lang = "en"
text = "Dataset extracted from the website of Tehran securities exchange technology management company"

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/bf/tsetmcbf1724-list_saman_bank_shareholders-1396-fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/bf/tsetmcbf1724-list_saman_bank_shareholders-1396-en.csv"

  [[resources.title]]
  lang = "en" 
  text = "List of sharholders for Saman bank in 1396"

  [[resources.title]]
  lang = "fa"
  text = "فهرست سهامداران بانک سامان در سال ۱۳۹۶"

  [[resources.sources]]
  name = "Tehran Securities Exchange Technology Management Company" 
  web = "http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=38179358042686391#" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "list of shareholders"
      type = "string"

      [[resources.schema.fields]]
      name = "shares"
      type = "string"

      [[resources.schema.fields]]
      name = " ownership percentage"
      type = "string"


