name = "twbehe1744"
license = "CC-BY-NC"
 
indexed_at = "2016-09-19" 
period = [1990, 2016] 
category= ["employment"]

[[maintainer]]
lang = "en" 
text = "Small Media Foundation"

[[maintainer]]
lang = "fa" 
text = "اسمال مدیا"

[[keywords]]
lang = "en" 
wordlist = ["male", "population", "global", "labor force"]

[[keywords]]
lang = "fa" 
wordlist = ["جمعیت", "مردان"]

[author]
web = "http://data.worldbank.org/indicator/SL.TLF.CACT.MA.ZS"

  [[author.name]] 
  lang = "fa"
  text = "بانک جهانی"

  [[author.name]]
  lang = "en"
  text = "The World Bank"

[[title]]
lang = "en" 
text = "Global Labor force participation rate for male ages 15 and over, from 1990 to 2016" 

[[title]]
lang = "fa"
text = "نرخ مشارکت جهانی نیروی کار برای مردان سن ۱۵ و بیش در سال‌های ۱۹۹۰ تا ۲۰۱۶"

[[description]]
lang = "fa"
text = "این داده از سایت رسمی بانک جهانی گرفته شده است."

[[description]]
lang = "en"
text = "Dataset extracted from the official website of The World Bank."

[[resources]]

  [[resources.url]] 
  lang = "fa"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/twbehe1744fa.csv" 

  [[resources.url]]
  lang = "en"
  link = "http://iod.dataset.s3.amazonaws.com/ehe/twbehe1744en.csv"

  [[resources.title]]
  lang = "en" 
  text = "Global Labor force participation rate for male ages 15 and over, from 1990 to 2016"

  [[resources.title]]
  lang = "fa"
  text = "نرخ مشارکت جهانی نیروی کار برای مردان سن ۱۵ و بیش در سال‌های ۱۹۹۰ تا ۲۰۱۶"

  [[resources.sources]]
  name = "The World Bank" 
  web = "http://data.worldbank.org/indicator/SL.TLF.CACT.MA.ZS" 

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Country Name"
      type = "string"

      [[resources.schema.fields]]
      name = "1990 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1991 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1992 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1993 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1994 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1995 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1996 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1997 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1998 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "1999 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2000 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2001 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2002 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2003 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2004 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2005 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2006 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2007 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2008 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2009 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2010 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2011 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2012 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2013 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2014 (percent)"
      type = "string"

      [[resources.schema.fields]]
      name = "2015 (percent)"
      type = "string"


